// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Policy for aggregation of multiple scalar plot values.
/// 
/// This is used for lines in plots when the X axis distance of individual points goes below a single pixel,
/// i.e. a single pixel covers more than one tick worth of data. It can greatly improve performance
/// (and readability) in such situations as it prevents overdraw.
/// </summary>
public enum AggregationPolicyValue : byte
{
    Invalid = 0,
    Off,
    Average,
    Max,
    Min,
    MinMax,
    MinMaxAverage,
}

/// <summary>
/// Policy for aggregation of multiple scalar plot values.
/// 
/// This is used for lines in plots when the X axis distance of individual points goes below a single pixel,
/// i.e. a single pixel covers more than one tick worth of data. It can greatly improve performance
/// (and readability) in such situations as it prevents overdraw.
/// </summary>
public readonly record struct AggregationPolicy(AggregationPolicyValue Value) : ILoggable<AggregationPolicy>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.AggregationPolicy");

    public static IArrowArray ToArrow(ReadOnlySpan<AggregationPolicy> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
