// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A color multiplier, usually applied to a whole entity, e.g. a mesh.
/// </summary>
public readonly record struct AlbedoFactor(Datatypes.Rgba32 AlbedoFactorValue) : ILoggable<AlbedoFactor>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.AlbedoFactor");

    public static IArrowArray ToArrow(ReadOnlySpan<AlbedoFactor> data)
    {
        var inner = new Datatypes.Rgba32[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].AlbedoFactorValue;
        return Datatypes.Rgba32.ToArrow(inner);
    }
}
