// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The annotation context provides additional information on how to display entities.
/// 
/// Entities can use [datatypes.ClassId]s and [datatypes.KeypointId]s to provide annotations, and
/// the labels and colors will be looked up in the appropriate
/// annotation context. We use the *first* annotation context we find in the
/// path-hierarchy when searching up through the ancestors of a given entity
/// path.
/// </summary>
public readonly record struct AnnotationContext(ClassDescriptionMapElem[] ClassMap) : ILoggable<AnnotationContext>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.AnnotationContext");

    public static IArrowArray ToArrow(ReadOnlySpan<AnnotationContext> data)
    {
        // Flatten all inner arrays and build offsets for ListArray
        var allItems = new System.Collections.Generic.List<ClassDescriptionMapElem>();
        var offsets = new Int32Array.Builder();
        offsets.Append(0);
        foreach (var v in data)
        {
            foreach (var item in v.ClassMap)
                allItems.Add(item);
            offsets.Append(allItems.Count);
        }
        var valuesArray = ClassDescriptionMapElem.ToArrow(allItems.ToArray());
        var offsetsArray = offsets.Build();
        var listType = new Apache.Arrow.Types.ListType(
            new Apache.Arrow.Field("item", valuesArray.Data.DataType, false));
        var listData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, offsetsArray.ValueBuffer },
            new[] { valuesArray.Data });
        return new ListArray(listData);
    }
}
