// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The length of an axis in local units of the space.
/// </summary>
public readonly record struct AxisLength(float Length) : ILoggable<AxisLength>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.AxisLength");

    public static IArrowArray ToArrow(ReadOnlySpan<AxisLength> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Length);
        return builder.Build();
    }
}
