// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A binary blob of data.
/// </summary>
public readonly record struct Blob(Datatypes.Blob Data) : ILoggable<Blob>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Blob");

    public static IArrowArray ToArrow(ReadOnlySpan<Blob> data)
    {
        var inner = new Datatypes.Blob[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Data;
        return Datatypes.Blob.ToArrow(inner);
    }
}
