// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A mapping of channel IDs to their respective message counts.
/// 
/// Used in MCAP statistics to track how many messages were recorded per channel.
/// </summary>
public readonly record struct ChannelMessageCounts(Datatypes.ChannelCountPair[] Counts) : ILoggable<ChannelMessageCounts>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ChannelMessageCounts");

    public static IArrowArray ToArrow(ReadOnlySpan<ChannelMessageCounts> data)
    {
        // Flatten all inner arrays and build offsets for ListArray
        var allItems = new System.Collections.Generic.List<Datatypes.ChannelCountPair>();
        var offsets = new Int32Array.Builder();
        offsets.Append(0);
        foreach (var v in data)
        {
            foreach (var item in v.Counts)
                allItems.Add(item);
            offsets.Append(allItems.Count);
        }
        var valuesArray = Datatypes.ChannelCountPair.ToArrow(allItems.ToArray());
        var offsetsArray = offsets.Build();
        var listType = new Apache.Arrow.Types.ListType(
            new Apache.Arrow.Field("item", valuesArray.Data.DataType, false));
        var listData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, offsetsArray.ValueBuffer },
            new[] { valuesArray.Data });
        return new ListArray(listData);
    }
}
