// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 16-bit ID representing an MCAP channel.
/// 
/// Used to identify specific channels within an MCAP file.
/// </summary>
public readonly record struct ChannelId(ushort Id) : ILoggable<ChannelId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ChannelId");

    public static IArrowArray ToArrow(ReadOnlySpan<ChannelId> data)
    {
        var builder = new UInt16Array.Builder();
        foreach (var v in data)
            builder.Append(v.Id);
        return builder.Build();
    }
}
