// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 16-bit ID representing a type of semantic class.
/// 
/// </summary>
public readonly record struct ClassId(Datatypes.ClassId Id) : ILoggable<ClassId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ClassId");

    public static IArrowArray ToArrow(ReadOnlySpan<ClassId> data)
    {
        var inner = new Datatypes.ClassId[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Id;
        return Datatypes.ClassId.ToArrow(inner);
    }
}
