// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Configures how a clear operation should behave - recursive or not.
/// </summary>
public readonly record struct ClearIsRecursive(bool Recursive) : ILoggable<ClearIsRecursive>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ClearIsRecursive");

    public static IArrowArray ToArrow(ReadOnlySpan<ClearIsRecursive> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.Recursive);
        return builder.Build();
    }
}
