// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// An RGBA color with unmultiplied/separate alpha, in sRGB gamma space with linear alpha.
/// 
/// The color is stored as a 32-bit integer, where the most significant
/// byte is `R` and the least significant byte is `A`.
/// 
/// </summary>
public readonly record struct Color(Rgba32 Rgba) : ILoggable<Color>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Color");

    public static IArrowArray ToArrow(ReadOnlySpan<Color> data)
    {
        var inner = new Rgba32[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Rgba;
        return Rgba32.ToArrow(inner);
    }
}
