// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Colormap for mapping scalar values within a given range to a color.
/// 
/// This provides a number of popular pre-defined colormaps.
/// In the future, the Rerun Viewer will allow users to define their own colormaps,
/// but currently the Viewer is limited to the types defined here.
/// </summary>
public enum ColormapValue : byte
{
    Invalid = 0,
    Grayscale,
    Inferno,
    Magma,
    Plasma,
    Turbo,
    Viridis,
    CyanToYellow,
    Spectral,
    Twilight,
}

/// <summary>
/// Colormap for mapping scalar values within a given range to a color.
/// 
/// This provides a number of popular pre-defined colormaps.
/// In the future, the Rerun Viewer will allow users to define their own colormaps,
/// but currently the Viewer is limited to the types defined here.
/// </summary>
public readonly record struct Colormap(ColormapValue Value) : ILoggable<Colormap>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Colormap");

    public static IArrowArray ToArrow(ReadOnlySpan<Colormap> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
