// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A generic count value.
/// 
/// Used for counting various entities like messages, schemas, channels, etc.
/// </summary>
public readonly record struct Count(ulong Value) : ILoggable<Count>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Count");

    public static IArrowArray ToArrow(ReadOnlySpan<Count> data)
    {
        var builder = new UInt64Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
