// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The world->depth map scaling factor.
/// 
/// This measures how many depth map units are in a world unit.
/// For instance, if a depth map uses millimeters and the world uses meters,
/// this value would be `1000`.
/// 
/// Note that the only effect on 2D views is the physical depth values shown when hovering the image.
/// In 3D views on the other hand, this affects where the points of the point cloud are placed.
/// </summary>
public readonly record struct DepthMeter(float Value) : ILoggable<DepthMeter>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.DepthMeter");

    public static IArrowArray ToArrow(ReadOnlySpan<DepthMeter> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
