// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Draw order of 2D elements. Higher values are drawn on top of lower values.
/// 
/// An entity can have only a single draw order component.
/// Within an entity draw order is governed by the order of the components.
/// 
/// Draw order for entities with the same draw order is generally undefined.
/// </summary>
public readonly record struct DrawOrder(float Value) : ILoggable<DrawOrder>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.DrawOrder");

    public static IArrowArray ToArrow(ReadOnlySpan<DrawOrder> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
