// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A path to an entity, usually to reference some data that is part of the target entity.
/// </summary>
public readonly record struct EntityPath(Datatypes.EntityPath Value) : ILoggable<EntityPath>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.EntityPath");

    public static IArrowArray ToArrow(ReadOnlySpan<EntityPath> data)
    {
        var inner = new Datatypes.EntityPath[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return Datatypes.EntityPath.ToArrow(inner);
    }
}
