// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// How a geometric shape is drawn and colored.
/// </summary>
public enum FillModeValue : byte
{
    Invalid = 0,
    MajorWireframe,
    DenseWireframe,
    Solid,
    TransparentFillMajorWireframe,
}

/// <summary>
/// How a geometric shape is drawn and colored.
/// </summary>
public readonly record struct FillMode(FillModeValue Value) : ILoggable<FillMode>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.FillMode");

    public static IArrowArray ToArrow(ReadOnlySpan<FillMode> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
