// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// How much a primitive fills out the available space.
/// 
/// Used for instance to scale the points of the point cloud created from [archetypes.DepthImage] projection in 3D views.
/// Valid range is from 0 to max float although typically values above 1.0 are not useful.
/// 
/// Defaults to 1.0.
/// </summary>
public readonly record struct FillRatio(float Value) : ILoggable<FillRatio>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.FillRatio");

    public static IArrowArray ToArrow(ReadOnlySpan<FillRatio> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
