// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A gamma correction value to be used with a scalar value or color.
/// 
/// Used to adjust the gamma of a color or scalar value between 0 and 1 before rendering.
/// `new_value = old_value ^ gamma`
/// 
/// Must be a positive number.
/// Defaults to 1.0 unless otherwise specified.
/// </summary>
public readonly record struct GammaCorrection(float Gamma) : ILoggable<GammaCorrection>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.GammaCorrection");

    public static IArrowArray ToArrow(ReadOnlySpan<GammaCorrection> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Gamma);
        return builder.Build();
    }
}
