// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// An edge in a graph connecting two nodes.
/// </summary>
public readonly record struct GraphEdge(Utf8Pair Edge) : ILoggable<GraphEdge>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.GraphEdge");

    public static IArrowArray ToArrow(ReadOnlySpan<GraphEdge> data)
    {
        var inner = new Utf8Pair[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Edge;
        return Utf8Pair.ToArrow(inner);
    }
}
