// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A string-based ID representing a node in a graph.
/// </summary>
public readonly record struct GraphNode(Datatypes.Utf8 Id) : ILoggable<GraphNode>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.GraphNode");

    public static IArrowArray ToArrow(ReadOnlySpan<GraphNode> data)
    {
        var inner = new Datatypes.Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Id;
        return Datatypes.Utf8.ToArrow(inner);
    }
}
