// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies if a graph has directed or undirected edges.
/// </summary>
public enum GraphTypeValue : byte
{
    Invalid = 0,
    Undirected,
    Directed,
}

/// <summary>
/// Specifies if a graph has directed or undirected edges.
/// </summary>
public readonly record struct GraphType(GraphTypeValue Value) : ILoggable<GraphType>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.GraphType");

    public static IArrowArray ToArrow(ReadOnlySpan<GraphType> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
