// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The metadata describing the contents of a [components.ImageBuffer].
/// </summary>
public readonly record struct ImageFormat(Datatypes.ImageFormat ImageFormatValue) : ILoggable<ImageFormat>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ImageFormat");

    public static IArrowArray ToArrow(ReadOnlySpan<ImageFormat> data)
    {
        var inner = new Datatypes.ImageFormat[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].ImageFormatValue;
        return Datatypes.ImageFormat.ToArrow(inner);
    }
}
