// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A buffer that is known to store image data.
/// 
/// To interpret the contents of this buffer, see, [components.ImageFormat].
/// </summary>
public readonly record struct ImageBuffer(Datatypes.Blob Buffer) : ILoggable<ImageBuffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ImageBuffer");

    public static IArrowArray ToArrow(ReadOnlySpan<ImageBuffer> data)
    {
        var inner = new Datatypes.Blob[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Buffer;
        return Datatypes.Blob.ToArrow(inner);
    }
}
