// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The distance from the camera origin to the image plane when the projection is shown in a 3D viewer.
/// 
/// This is only used for visualization purposes, and does not affect the projection itself.
/// </summary>
public readonly record struct ImagePlaneDistance(float ImageFromCamera) : ILoggable<ImagePlaneDistance>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ImagePlaneDistance");

    public static IArrowArray ToArrow(ReadOnlySpan<ImagePlaneDistance> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.ImageFromCamera);
        return builder.Build();
    }
}
