// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Whether the entity can be interacted with.
/// 
/// Non interactive components are still visible, but mouse interactions in the view are disabled.
/// </summary>
public readonly record struct Interactive(bool InteractiveValue) : ILoggable<Interactive>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Interactive");

    public static IArrowArray ToArrow(ReadOnlySpan<Interactive> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.InteractiveValue);
        return builder.Build();
    }
}
