// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies how values between data points are interpolated in time series.
/// </summary>
public enum InterpolationModeValue : byte
{
    Invalid = 0,
    Linear,
    StepAfter,
    StepBefore,
    StepMid,
}

/// <summary>
/// Specifies how values between data points are interpolated in time series.
/// </summary>
public readonly record struct InterpolationMode(InterpolationModeValue Value) : ILoggable<InterpolationMode>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.InterpolationMode");

    public static IArrowArray ToArrow(ReadOnlySpan<InterpolationMode> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
