// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 16-bit ID representing a type of semantic keypoint within a class.
/// 
/// 
/// </summary>
public readonly record struct KeypointId(Datatypes.KeypointId Id) : ILoggable<KeypointId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.KeypointId");

    public static IArrowArray ToArrow(ReadOnlySpan<KeypointId> data)
    {
        var inner = new Datatypes.KeypointId[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Id;
        return Datatypes.KeypointId.ToArrow(inner);
    }
}
