// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A map of string keys to string values.
/// 
/// This component can be used to attach arbitrary metadata or annotations to entities.
/// Each key-value pair is stored as a UTF-8 string mapping.
/// </summary>
public readonly record struct KeyValuePairs(Utf8Pair[] Pairs) : ILoggable<KeyValuePairs>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.KeyValuePairs");

    public static IArrowArray ToArrow(ReadOnlySpan<KeyValuePairs> data)
    {
        // Flatten all inner arrays and build offsets for ListArray
        var allItems = new System.Collections.Generic.List<Utf8Pair>();
        var offsets = new Int32Array.Builder();
        offsets.Append(0);
        foreach (var v in data)
        {
            foreach (var item in v.Pairs)
                allItems.Add(item);
            offsets.Append(allItems.Count);
        }
        var valuesArray = Utf8Pair.ToArrow(allItems.ToArray());
        var offsetsArray = offsets.Build();
        var listType = new Apache.Arrow.Types.ListType(
            new Apache.Arrow.Field("item", valuesArray.Data.DataType, false));
        var listData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, offsetsArray.ValueBuffer },
            new[] { valuesArray.Data });
        return new ListArray(listData);
    }
}
