// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Length, or one-dimensional size.
/// 
/// Measured in its local coordinate system; consult the archetype in use to determine which
/// axis or part of the entity this is the length of.
/// </summary>
public readonly record struct Length(float LengthValue) : ILoggable<Length>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Length");

    public static IArrowArray ToArrow(ReadOnlySpan<Length> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.LengthValue);
        return builder.Build();
    }
}
