// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A line strip in 3D space.
/// 
/// A line strip is a list of points connected by line segments. It can be used to draw
/// approximations of smooth curves.
/// 
/// The points will be connected in order, like so:
/// ```text
/// 2------3     5
/// /        \   /
/// 0----1          \ /
/// 4
/// ```
/// </summary>
public readonly record struct LineStrip3D(Vec3D[] Points) : ILoggable<LineStrip3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.LineStrip3D");

    public static IArrowArray ToArrow(ReadOnlySpan<LineStrip3D> data)
    {
        // Flatten all inner arrays and build offsets for ListArray
        var allItems = new System.Collections.Generic.List<Vec3D>();
        var offsets = new Int32Array.Builder();
        offsets.Append(0);
        foreach (var v in data)
        {
            foreach (var item in v.Points)
                allItems.Add(item);
            offsets.Append(allItems.Count);
        }
        var valuesArray = Vec3D.ToArrow(allItems.ToArray());
        var offsetsArray = offsets.Build();
        var listType = new Apache.Arrow.Types.ListType(
            new Apache.Arrow.Field("item", valuesArray.Data.DataType, false));
        var listData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, offsetsArray.ValueBuffer },
            new[] { valuesArray.Data });
        return new ListArray(listData);
    }
}
