// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Linear speed, used for translation speed for example.
/// </summary>
public readonly record struct LinearSpeed(double Speed) : ILoggable<LinearSpeed>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.LinearSpeed");

    public static IArrowArray ToArrow(ReadOnlySpan<LinearSpeed> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Speed);
        return builder.Build();
    }
}
