// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Filter used when a single texel/pixel of an image is displayed larger than a single screen pixel.
/// 
/// This happens when zooming into an image, when displaying a low-resolution image in a large area,
/// or when viewing an image up close in 3D space.
/// </summary>
public enum MagnificationFilterValue : byte
{
    Invalid = 0,
    Nearest,
    Linear,
    Bicubic,
}

/// <summary>
/// Filter used when a single texel/pixel of an image is displayed larger than a single screen pixel.
/// 
/// This happens when zooming into an image, when displaying a low-resolution image in a large area,
/// or when viewing an image up close in 3D space.
/// </summary>
public readonly record struct MagnificationFilter(MagnificationFilterValue Value) : ILoggable<MagnificationFilter>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.MagnificationFilter");

    public static IArrowArray ToArrow(ReadOnlySpan<MagnificationFilter> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
