// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Radius of a marker of a point in e.g. a 2D plot, measured in UI points.
/// </summary>
public readonly record struct MarkerSize(float Value) : ILoggable<MarkerSize>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.MarkerSize");

    public static IArrowArray ToArrow(ReadOnlySpan<MarkerSize> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
