// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// The visual appearance of a point in e.g. a 2D plot.
/// </summary>
public enum MarkerShapeValue : byte
{
    Invalid = 0,
    Circle,
    Diamond,
    Square,
    Cross,
    Plus,
    Up,
    Down,
    Left,
    Right,
    Asterisk,
}

/// <summary>
/// The visual appearance of a point in e.g. a 2D plot.
/// </summary>
public readonly record struct MarkerShape(MarkerShapeValue Value) : ILoggable<MarkerShape>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.MarkerShape");

    public static IArrowArray ToArrow(ReadOnlySpan<MarkerShape> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
