// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A standardized media type (RFC2046, formerly known as MIME types), encoded as a string.
/// 
/// The complete reference of officially registered media types is maintained by the IANA and can be
/// consulted at <https://www.iana.org/assignments/media-types/media-types.xhtml>.
/// </summary>
public readonly record struct MediaType(Datatypes.Utf8 Value) : ILoggable<MediaType>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.MediaType");

    public static IArrowArray ToArrow(ReadOnlySpan<MediaType> data)
    {
        var inner = new Datatypes.Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return Datatypes.Utf8.ToArrow(inner);
    }
}
