// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Determines which faces of a mesh are rendered.
/// 
/// For this purpose, we assume that the winding order of vertices in a mesh is
/// consistent and that front faces are defined as those with vertices in counter clockwise order.
/// </summary>
public enum MeshFaceRenderingValue : byte
{
    Invalid = 0,
    DoubleSided,
    Front,
    Back,
}

/// <summary>
/// Determines which faces of a mesh are rendered.
/// 
/// For this purpose, we assume that the winding order of vertices in a mesh is
/// consistent and that front faces are defined as those with vertices in counter clockwise order.
/// </summary>
public readonly record struct MeshFaceRendering(MeshFaceRenderingValue Value) : ILoggable<MeshFaceRendering>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.MeshFaceRendering");

    public static IArrowArray ToArrow(ReadOnlySpan<MeshFaceRendering> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
