// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A display name, typically for an entity or a item like a plot series.
/// </summary>
public readonly record struct Name(Utf8 Value) : ILoggable<Name>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Name");

    public static IArrowArray ToArrow(ReadOnlySpan<Name> data)
    {
        var inner = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return Utf8.ToArrow(inner);
    }
}
