// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Degree of transparency ranging from 0.0 (fully transparent) to 1.0 (fully opaque).
/// 
/// The final opacity value may be a result of multiplication with alpha values as specified by other color sources.
/// Unless otherwise specified, the default value is 1.
/// </summary>
public readonly record struct Opacity(float OpacityValue) : ILoggable<Opacity>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Opacity");

    public static IArrowArray ToArrow(ReadOnlySpan<Opacity> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.OpacityValue);
        return builder.Build();
    }
}
