// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Camera projection, from image coordinates to view coordinates.
/// 
/// Child from parent.
/// Image coordinates from camera view coordinates.
/// 
/// Example:
/// ```text
/// 1496.1     0.0  980.5
/// 0.0  1496.1  744.5
/// 0.0     0.0    1.0
/// ```
/// </summary>
public readonly record struct PinholeProjection(Datatypes.Mat3x3 ImageFromCamera) : ILoggable<PinholeProjection>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.PinholeProjection");

    public static IArrowArray ToArrow(ReadOnlySpan<PinholeProjection> data)
    {
        var inner = new Datatypes.Mat3x3[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].ImageFromCamera;
        return Datatypes.Mat3x3.ToArrow(inner);
    }
}
