// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// An infinite 3D plane represented by a unit normal vector and a distance.
/// 
/// Any point P on the plane fulfills the equation `dot(xyz, P) - d = 0`,
/// where `xyz` is the plane's normal and `d` the distance of the plane from the origin.
/// This representation is also known as the Hesse normal form.
/// 
/// Note: although the normal will be passed through to the
/// datastore as provided, when used in the Viewer, planes will always be normalized.
/// I.e. the plane with xyz = (2, 0, 0), d = 1 is equivalent to xyz = (1, 0, 0), d = 0.5
/// </summary>
public readonly record struct Plane3D(Datatypes.Plane3D Xyzd) : ILoggable<Plane3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Plane3D");

    public static IArrowArray ToArrow(ReadOnlySpan<Plane3D> data)
    {
        var inner = new Datatypes.Plane3D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Xyzd;
        return Datatypes.Plane3D.ToArrow(inner);
    }
}
