// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A position in 3D space.
/// </summary>
public readonly record struct Position3D(Vec3D Xyz) : ILoggable<Position3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Position3D");

    public static IArrowArray ToArrow(ReadOnlySpan<Position3D> data)
    {
        var inner = new Vec3D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Xyz;
        return Vec3D.ToArrow(inner);
    }
}
