// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The radius of something, e.g. a point.
/// 
/// Internally, positive values indicate scene units, whereas negative values
/// are interpreted as UI points.
/// 
/// UI points are independent of zooming in Views, but are sensitive to the application UI scaling.
/// at 100% UI scaling, UI points are equal to pixels
/// The Viewer's UI scaling defaults to the OS scaling which typically is 100% for full HD screens and 200% for 4k screens.
/// </summary>
public readonly record struct Radius(float Value) : ILoggable<Radius>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Radius");

    public static IArrowArray ToArrow(ReadOnlySpan<Radius> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
