// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 1D range, specifying a lower and upper bound.
/// </summary>
public readonly record struct Range1D(Datatypes.Range1D Range) : ILoggable<Range1D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Range1D");

    public static IArrowArray ToArrow(ReadOnlySpan<Range1D> data)
    {
        var inner = new Datatypes.Range1D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Range;
        return Datatypes.Range1D.ToArrow(inner);
    }
}
