// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Pixel resolution width & height, e.g. of a camera sensor.
/// 
/// Typically in integer units, but for some use cases floating point may be used.
/// </summary>
public readonly record struct Resolution(Datatypes.Vec2D ResolutionValue) : ILoggable<Resolution>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Resolution");

    public static IArrowArray ToArrow(ReadOnlySpan<Resolution> data)
    {
        var inner = new Datatypes.Vec2D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].ResolutionValue;
        return Datatypes.Vec2D.ToArrow(inner);
    }
}
