// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 3D rotation expressed as a quaternion.
/// 
/// Note: although the x,y,z,w components of the quaternion will be passed through to the
/// datastore as provided, when used in the Viewer, quaternions will always be normalized.
/// If normalization fails the rotation is treated as an invalid transform.
/// </summary>
public readonly record struct RotationQuat(Quaternion Quaternion) : ILoggable<RotationQuat>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.RotationQuat");

    public static IArrowArray ToArrow(ReadOnlySpan<RotationQuat> data)
    {
        var inner = new Quaternion[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Quaternion;
        return Quaternion.ToArrow(inner);
    }
}
