// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// 3D rotation represented by a rotation around a given axis.
/// 
/// If normalization of the rotation axis fails the rotation is treated as an invalid transform, unless the
/// angle is zero in which case it is treated as an identity.
/// </summary>
public readonly record struct RotationAxisAngle(Datatypes.RotationAxisAngle Rotation) : ILoggable<RotationAxisAngle>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.RotationAxisAngle");

    public static IArrowArray ToArrow(ReadOnlySpan<RotationAxisAngle> data)
    {
        var inner = new Datatypes.RotationAxisAngle[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Rotation;
        return Datatypes.RotationAxisAngle.ToArrow(inner);
    }
}
