// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A scalar value, encoded as a 64-bit floating point.
/// 
/// Used for time series plots.
/// </summary>
public readonly record struct Scalar(double Value) : ILoggable<Scalar>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Scalar");

    public static IArrowArray ToArrow(ReadOnlySpan<Scalar> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
