// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 3D scale factor.
/// 
/// A scale of 1.0 means no scaling.
/// A scale of 2.0 means doubling the size.
/// Each component scales along the corresponding axis.
/// </summary>
public readonly record struct Scale3D(Datatypes.Vec3D Scale) : ILoggable<Scale3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Scale3D");

    public static IArrowArray ToArrow(ReadOnlySpan<Scale3D> data)
    {
        var inner = new Datatypes.Vec3D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Scale;
        return Datatypes.Vec3D.ToArrow(inner);
    }
}
