// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 16-bit unique identifier for a schema within the MCAP file.
/// </summary>
public readonly record struct SchemaId(ushort Id) : ILoggable<SchemaId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.SchemaId");

    public static IArrowArray ToArrow(ReadOnlySpan<SchemaId> data)
    {
        var builder = new UInt16Array.Builder();
        foreach (var v in data)
            builder.Append(v.Id);
        return builder.Build();
    }
}
