// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Whether the entity's [components.Text] label is shown.
/// 
/// The main purpose of this component existing separately from the labels themselves
/// is to be overridden when desired, to allow hiding and showing from the viewer and
/// blueprints.
/// </summary>
public readonly record struct ShowLabels(bool ShowLabelsValue) : ILoggable<ShowLabels>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ShowLabels");

    public static IArrowArray ToArrow(ReadOnlySpan<ShowLabels> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.ShowLabelsValue);
        return builder.Build();
    }
}
