// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The width of a stroke specified in UI points.
/// </summary>
public readonly record struct StrokeWidth(float Width) : ILoggable<StrokeWidth>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.StrokeWidth");

    public static IArrowArray ToArrow(ReadOnlySpan<StrokeWidth> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Width);
        return builder.Build();
    }
}
