// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies which dimension to use for width.
/// </summary>
public readonly record struct TensorWidthDimension(Datatypes.TensorDimensionSelection Dimension) : ILoggable<TensorWidthDimension>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TensorWidthDimension");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorWidthDimension> data)
    {
        var inner = new Datatypes.TensorDimensionSelection[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Dimension;
        return Datatypes.TensorDimensionSelection.ToArrow(inner);
    }
}
