// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies a concrete index on a tensor dimension.
/// </summary>
public readonly record struct TensorDimensionIndexSelection(Datatypes.TensorDimensionIndexSelection Selection) : ILoggable<TensorDimensionIndexSelection>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TensorDimensionIndexSelection");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorDimensionIndexSelection> data)
    {
        var inner = new Datatypes.TensorDimensionIndexSelection[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Selection;
        return Datatypes.TensorDimensionIndexSelection.ToArrow(inner);
    }
}
