// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// An N-dimensional array of numbers.
/// 
/// The number of dimensions and their respective lengths is specified by the `shape` field.
/// The dimensions are ordered from outermost to innermost. For example, in the common case of
/// a 2D RGB Image, the shape would be `[height, width, channel]`.
/// 
/// These dimensions are combined with an index to look up values from the `buffer` field,
/// which stores a contiguous array of typed values.
/// </summary>
public readonly record struct TensorData(Datatypes.TensorData Data) : ILoggable<TensorData>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TensorData");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorData> data)
    {
        var inner = new Datatypes.TensorData[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Data;
        return Datatypes.TensorData.ToArrow(inner);
    }
}
