// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies which dimension to use for height.
/// </summary>
public readonly record struct TensorHeightDimension(TensorDimensionSelection Dimension) : ILoggable<TensorHeightDimension>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TensorHeightDimension");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorHeightDimension> data)
    {
        var inner = new TensorDimensionSelection[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Dimension;
        return TensorDimensionSelection.ToArrow(inner);
    }
}
