// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 2D texture UV coordinate.
/// 
/// Texture coordinates specify a position on a 2D texture.
/// A range from 0-1 covers the entire texture in the respective dimension.
/// Unless configured otherwise, the texture repeats outside of this range.
/// Rerun uses top-left as the origin for UV coordinates.
/// 
/// 0     U     1
/// 0 + --------- →
/// |           .
/// |           .
/// V |           .
/// |           .
/// 1 ↓ . . . . . .
/// 
/// This is the same convention as in Vulkan/Metal/DX12/WebGPU, but (!) unlike OpenGL,
/// which places the origin at the bottom-left.
/// </summary>
public readonly record struct Texcoord2D(Datatypes.Vec2D Uv) : ILoggable<Texcoord2D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Texcoord2D");

    public static IArrowArray ToArrow(ReadOnlySpan<Texcoord2D> data)
    {
        var inner = new Datatypes.Vec2D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Uv;
        return Datatypes.Vec2D.ToArrow(inner);
    }
}
