// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The severity level of a text log message.
/// 
/// Recommended to be one of:
/// * `"CRITICAL"`
/// * `"ERROR"`
/// * `"WARN"`
/// * `"INFO"`
/// * `"DEBUG"`
/// * `"TRACE"`
/// </summary>
public readonly record struct TextLogLevel(Datatypes.Utf8 Value) : ILoggable<TextLogLevel>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TextLogLevel");

    public static IArrowArray ToArrow(ReadOnlySpan<TextLogLevel> data)
    {
        var inner = new Datatypes.Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return Datatypes.Utf8.ToArrow(inner);
    }
}
