// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// When the recording started.
/// 
/// Should be an absolute time, i.e. relative to Unix Epoch.
/// </summary>
public readonly record struct Timestamp(TimeInt TimestampValue) : ILoggable<Timestamp>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Timestamp");

    public static IArrowArray ToArrow(ReadOnlySpan<Timestamp> data)
    {
        var inner = new TimeInt[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].TimestampValue;
        return TimeInt.ToArrow(inner);
    }
}
