// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A string identifier for a transform frame.
/// 
/// Transform frames may be derived from entity paths to refer to Rerun's implicit
/// entity path driven hierarchy which is defined via [archetypes.Transform3D], [archetypes.Pinhole] etc..
/// These implicit transform frames look like `tf#path/to/entity`.
/// 
/// Note that any [archetypes.Transform3D]s logged with both `parent_frame` and `child_frame` set
/// describes a relationship between these parent and child transform frames, **not** the transform frame
/// that the entity path may be using (defined by an [archetypes.CoordinateFrame]).
/// </summary>
public readonly record struct TransformFrameId(Utf8 Value) : ILoggable<TransformFrameId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TransformFrameId");

    public static IArrowArray ToArrow(ReadOnlySpan<TransformFrameId> data)
    {
        var inner = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return Utf8.ToArrow(inner);
    }
}
