// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// Specifies relation a spatial transform describes.
/// </summary>
public enum TransformRelationValue : byte
{
    Invalid = 0,
    ParentFromChild,
    ChildFromParent,
}

/// <summary>
/// Specifies relation a spatial transform describes.
/// </summary>
public readonly record struct TransformRelation(TransformRelationValue Value) : ILoggable<TransformRelation>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TransformRelation");

    public static IArrowArray ToArrow(ReadOnlySpan<TransformRelation> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
