// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A 3x3 transformation matrix Matrix.
/// 
/// 3x3 matrixes are able to represent any affine transformation in 3D space,
/// i.e. rotation, scaling, shearing, reflection etc.
/// 
/// Matrices in Rerun are stored as flat list of coefficients in column-major order:
/// ```text
/// column 0       column 1       column 2
/// -------------------------------------------------
/// row 0 | flat_columns[0] flat_columns[3] flat_columns[6]
/// row 1 | flat_columns[1] flat_columns[4] flat_columns[7]
/// row 2 | flat_columns[2] flat_columns[5] flat_columns[8]
/// ```
/// 
/// </summary>
public readonly record struct TransformMat3x3(Mat3x3 Matrix) : ILoggable<TransformMat3x3>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TransformMat3x3");

    public static IArrowArray ToArrow(ReadOnlySpan<TransformMat3x3> data)
    {
        var inner = new Mat3x3[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Matrix;
        return Mat3x3.ToArrow(inner);
    }
}
