// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// The three indices of a triangle in a triangle mesh.
/// </summary>
public readonly record struct TriangleIndices(Datatypes.UVec3D Indices) : ILoggable<TriangleIndices>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.TriangleIndices");

    public static IArrowArray ToArrow(ReadOnlySpan<TriangleIndices> data)
    {
        var inner = new Datatypes.UVec3D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Indices;
        return Datatypes.UVec3D.ToArrow(inner);
    }
}
