// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Range of expected or valid values, specifying a lower and upper bound.
/// </summary>
public readonly record struct ValueRange(Range1D Range) : ILoggable<ValueRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ValueRange");

    public static IArrowArray ToArrow(ReadOnlySpan<ValueRange> data)
    {
        var inner = new Range1D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Range;
        return Range1D.ToArrow(inner);
    }
}
