// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// A vector in 3D space.
/// </summary>
public readonly record struct Vector3D(Vec3D Vector) : ILoggable<Vector3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Vector3D");

    public static IArrowArray ToArrow(ReadOnlySpan<Vector3D> data)
    {
        var inner = new Vec3D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Vector;
        return Vec3D.ToArrow(inner);
    }
}
