// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Timestamp inside a [archetypes.AssetVideo].
/// </summary>
public readonly record struct VideoTimestamp(Datatypes.VideoTimestamp Timestamp) : ILoggable<VideoTimestamp>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.VideoTimestamp");

    public static IArrowArray ToArrow(ReadOnlySpan<VideoTimestamp> data)
    {
        var inner = new Datatypes.VideoTimestamp[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Timestamp;
        return Datatypes.VideoTimestamp.ToArrow(inner);
    }
}
