// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

/// <summary>
/// The codec used to encode video stored in [components.VideoSample].
/// 
/// Support of these codecs by the Rerun Viewer is platform dependent.
/// For more details see check the [video reference](https://rerun.io/docs/reference/video).
/// </summary>
public enum VideoCodecValue : uint
{
    Invalid = 0,
    H264,
    H265,
    AV1,
}

/// <summary>
/// The codec used to encode video stored in [components.VideoSample].
/// 
/// Support of these codecs by the Rerun Viewer is platform dependent.
/// For more details see check the [video reference](https://rerun.io/docs/reference/video).
/// </summary>
public readonly record struct VideoCodec(VideoCodecValue Value) : ILoggable<VideoCodec>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.VideoCodec");

    public static IArrowArray ToArrow(ReadOnlySpan<VideoCodec> data)
    {
        var builder = new UInt32Array.Builder();
        foreach (var v in data)
            builder.Append((uint)v.Value);
        return builder.Build();
    }
}
