// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Video sample data (also known as "video chunk").
/// 
/// Each video sample must contain enough data for exactly one video frame
/// (this restriction may be relaxed in the future for some codecs).
/// 
/// Keyframes may require additional data, for details see [components.VideoCodec].
/// </summary>
public readonly record struct VideoSample(Blob Buffer) : ILoggable<VideoSample>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.VideoSample");

    public static IArrowArray ToArrow(ReadOnlySpan<VideoSample> data)
    {
        var inner = new Blob[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Buffer;
        return Blob.ToArrow(inner);
    }
}
