// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

namespace Rerun.Net.Components;

public enum ViewDirValue : byte
{
    Up = 1,
    Down = 2,
    Right = 3,
    Left = 4,
    Forward = 5,
    Back = 6,
}

public readonly record struct ViewDir(ViewDirValue Value) : ILoggable<ViewDir>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ViewDir");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewDir> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
