// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// How we interpret the coordinate system of an entity/space.
/// 
/// For instance: What is "up"? What does the Z axis mean?
/// 
/// The three coordinates are always ordered as [x, y, z].
/// 
/// For example [Right, Down, Forward] means that the X axis points to the right, the Y axis points
/// down, and the Z axis points forward.
/// 
/// ⚠ [Rerun does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
/// 
/// The following constants are used to represent the different directions:
/// * Up = 1
/// * Down = 2
/// * Right = 3
/// * Left = 4
/// * Forward = 5
/// * Back = 6
/// </summary>
public readonly record struct ViewCoordinates(Datatypes.ViewCoordinates Coordinates) : ILoggable<ViewCoordinates>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.ViewCoordinates");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewCoordinates> data)
    {
        var inner = new Datatypes.ViewCoordinates[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Coordinates;
        return Datatypes.ViewCoordinates.ToArrow(inner);
    }
}
