// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

namespace Rerun.Net.Components;

/// <summary>
/// Whether the container, view, entity or instance is currently visible.
/// </summary>
public readonly record struct Visible(bool VisibleValue) : ILoggable<Visible>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.components.Visible");

    public static IArrowArray ToArrow(ReadOnlySpan<Visible> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.VisibleValue);
        return builder.Build();
    }
}
