// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// What kind of source to use for a visualizer component mapping.
/// </summary>
public enum ComponentSourceKind : byte
{
    Invalid = 0,
    SourceComponent,
    Override,
    Default,
}
