// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

public readonly partial record struct ComponentColumnSelector(EntityPath EntityPath, Utf8 Component) : ILoggable<ComponentColumnSelector>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.ComponentColumnSelector");

    public static IArrowArray ToArrow(ReadOnlySpan<ComponentColumnSelector> data)
    {
        var entity_pathTmp = new EntityPath[data.Length];
        for (var i = 0; i < data.Length; i++) entity_pathTmp[i] = data[i].EntityPath;
        var entity_pathArray = EntityPath.ToArrow(entity_pathTmp);
        var componentTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) componentTmp[i] = data[i].Component;
        var componentArray = Utf8.ToArrow(componentTmp);
        var fields = new Apache.Arrow.Field[] {
            new("entity_path", entity_pathArray.Data.DataType, false),
            new("component", componentArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { entity_pathArray, componentArray }, ArrowBuffer.Empty);
    }
}
