// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

public readonly partial record struct FilterIsNotNull(bool Active, ComponentColumnSelector Column) : ILoggable<FilterIsNotNull>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.FilterIsNotNull");

    public static IArrowArray ToArrow(ReadOnlySpan<FilterIsNotNull> data)
    {
        var activeBuilder = new BooleanArray.Builder();
        foreach (var v in data) activeBuilder.Append(v.Active);
        var activeArray = (IArrowArray)activeBuilder.Build();
        var columnTmp = new ComponentColumnSelector[data.Length];
        for (var i = 0; i < data.Length; i++) columnTmp[i] = data[i].Column;
        var columnArray = ComponentColumnSelector.ToArrow(columnTmp);
        var fields = new Apache.Arrow.Field[] {
            new("active", activeArray.Data.DataType, false),
            new("column", columnArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { activeArray, columnArray }, ArrowBuffer.Empty);
    }
}
