// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// Configuration for the filter-by-range feature of the dataframe view.
/// </summary>
public readonly partial record struct FilterByRange(TimeInt Start, TimeInt End) : ILoggable<FilterByRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.FilterByRange");

    public static IArrowArray ToArrow(ReadOnlySpan<FilterByRange> data)
    {
        var startTmp = new TimeInt[data.Length];
        for (var i = 0; i < data.Length; i++) startTmp[i] = data[i].Start;
        var startArray = TimeInt.ToArrow(startTmp);
        var endTmp = new TimeInt[data.Length];
        for (var i = 0; i < data.Length; i++) endTmp[i] = data[i].End;
        var endArray = TimeInt.ToArrow(endTmp);
        var fields = new Apache.Arrow.Field[] {
            new("start", startArray.Data.DataType, false),
            new("end", endArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { startArray, endArray }, ArrowBuffer.Empty);
    }
}
