// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

public readonly partial record struct SelectedColumns(Utf8[] TimeColumns, ComponentColumnSelector[] ComponentColumns) : ILoggable<SelectedColumns>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.SelectedColumns");

    public static IArrowArray ToArrow(ReadOnlySpan<SelectedColumns> data)
    {
        IArrowArray time_columnsArray = null!; // unsupported field type
        IArrowArray component_columnsArray = null!; // unsupported field type
        var fields = new Apache.Arrow.Field[] {
            new("time_columns", time_columnsArray.Data.DataType, false),
            new("component_columns", component_columnsArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { time_columnsArray, component_columnsArray }, ArrowBuffer.Empty);
    }
}
