// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// Defines a slider for the index of some dimension.
/// </summary>
public readonly record struct TensorDimensionIndexSlider(uint Dimension) : ILoggable<TensorDimensionIndexSlider>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.TensorDimensionIndexSlider");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorDimensionIndexSlider> data)
    {
        var dimensionBuilder = new UInt32Array.Builder();
        foreach (var v in data) dimensionBuilder.Append(v.Dimension);
        var fields = new Apache.Arrow.Field[] {
            new Apache.Arrow.Field("dimension", new UInt32Type(), false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { dimensionBuilder.Build() }, ArrowBuffer.Empty);
    }
}
