// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// A text log column.
/// </summary>
public readonly partial record struct TextLogColumn(bool Visible, TextLogColumnKind Kind) : ILoggable<TextLogColumn>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.TextLogColumn");

    public static IArrowArray ToArrow(ReadOnlySpan<TextLogColumn> data)
    {
        var visibleBuilder = new BooleanArray.Builder();
        foreach (var v in data) visibleBuilder.Append(v.Visible);
        var visibleArray = (IArrowArray)visibleBuilder.Build();
        var kindBuilder = new UInt8Array.Builder();
        foreach (var v in data) kindBuilder.Append((byte)v.Kind);
        var kindArray = (IArrowArray)kindBuilder.Build();
        var fields = new Apache.Arrow.Field[] {
            new("visible", visibleArray.Data.DataType, false),
            new("kind", kindArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { visibleArray, kindArray }, ArrowBuffer.Empty);
    }
}
