// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// A text log column kind.
/// </summary>
public enum TextLogColumnKind : byte
{
    Invalid = 0,
    EntityPath,
    LogLevel,
    Body,
}
