// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// A timeline column in a table.
/// </summary>
public readonly partial record struct TimelineColumn(bool Visible, Utf8 Timeline) : ILoggable<TimelineColumn>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.TimelineColumn");

    public static IArrowArray ToArrow(ReadOnlySpan<TimelineColumn> data)
    {
        var visibleBuilder = new BooleanArray.Builder();
        foreach (var v in data) visibleBuilder.Append(v.Visible);
        var visibleArray = (IArrowArray)visibleBuilder.Build();
        var timelineTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) timelineTmp[i] = data[i].Timeline;
        var timelineArray = Utf8.ToArrow(timelineTmp);
        var fields = new Apache.Arrow.Field[] {
            new("visible", visibleArray.Data.DataType, false),
            new("timeline", timelineArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { visibleArray, timelineArray }, ArrowBuffer.Empty);
    }
}
