// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

using Rerun.Net.Datatypes;

namespace Rerun.Net.Blueprint.Datatypes;

/// <summary>
/// Associate components of an entity to components of a visualizer.
/// </summary>
public readonly partial record struct VisualizerComponentMapping(Utf8 Target, ComponentSourceKind SourceKind, string SourceComponent, string Selector) : ILoggable<VisualizerComponentMapping>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.datatypes.VisualizerComponentMapping");

    public static IArrowArray ToArrow(ReadOnlySpan<VisualizerComponentMapping> data)
    {
        var targetTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) targetTmp[i] = data[i].Target;
        var targetArray = Utf8.ToArrow(targetTmp);
        var source_kindBuilder = new UInt8Array.Builder();
        foreach (var v in data) source_kindBuilder.Append((byte)v.SourceKind);
        var source_kindArray = (IArrowArray)source_kindBuilder.Build();
        var source_componentBuilder = new StringArray.Builder();
        foreach (var v in data) source_componentBuilder.Append(v.SourceComponent);
        var source_componentArray = (IArrowArray)source_componentBuilder.Build();
        var selectorBuilder = new StringArray.Builder();
        foreach (var v in data) selectorBuilder.Append(v.Selector);
        var selectorArray = (IArrowArray)selectorBuilder.Build();
        var fields = new Apache.Arrow.Field[] {
            new("target", targetArray.Data.DataType, false),
            new("source_kind", source_kindArray.Data.DataType, false),
            new("source_component", source_componentArray.Data.DataType, false),
            new("selector", selectorArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { targetArray, source_kindArray, source_componentArray, selectorArray }, ArrowBuffer.Empty);
    }
}
