// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Override the visualizers for an entity.
/// 
/// This archetype is a stop-gap mechanism based on the current implementation details
/// of the visualizer system. It is not intended to be a long-term solution, but provides
/// enough utility to be useful in the short term.
/// 
/// This can only be used as part of blueprints. It will have no effect if used
/// in a regular entity.
/// </summary>
public sealed partial class ActiveVisualizers : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ActiveVisualizers";

    public ComponentBatch InstructionIds { get; private set; }

    public ActiveVisualizers(ReadOnlySpan<Components.VisualizerInstructionId> instruction_ids)
    {
        InstructionIds = ComponentBatch.FromLoggable(instruction_ids,
            new ComponentDescriptor(ArchetypeName, "ActiveVisualizers:instruction_ids", "rerun.blueprint.components.VisualizerInstructionId"));
    }

    public ActiveVisualizers(params Components.VisualizerInstructionId[] instruction_ids) : this(instruction_ids.AsSpan()) { }

    /// <summary>Create an empty ActiveVisualizers for partial updates. Use With*() to set fields.</summary>
    public static ActiveVisualizers UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ActiveVisualizers ClearFields() => new();

    private ActiveVisualizers() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(InstructionIds);
        return batches;
    }
}
