// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the background of a spatial view.
/// </summary>
public sealed partial class Background : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.Background";

    public ComponentBatch Kind { get; private set; }
    public ComponentBatch? Color { get; private set; }

    public Background(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.BackgroundKind> kind)
    {
        Kind = ComponentBatch.FromLoggable(kind,
            new ComponentDescriptor(ArchetypeName, "Background:kind", "rerun.blueprint.components.BackgroundKind"));
    }

    public Background(params global::Rerun.Net.Blueprint.Components.BackgroundKind[] kind) : this(kind.AsSpan()) { }

    public Background WithColor(ReadOnlySpan<global::Rerun.Net.Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "Background:color", "rerun.components.Color"));
        return this;
    }

    public Background WithColor(params global::Rerun.Net.Components.Color[] color) => WithColor(color.AsSpan());

    /// <summary>Create an empty Background for partial updates. Use With*() to set fields.</summary>
    public static Background UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Background ClearFields() => new();

    private Background() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(Kind);
        if (Color != null) batches.Add(Color);
        return batches;
    }
}
