// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// The description of a container.
/// </summary>
public sealed partial class ContainerBlueprint : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ContainerBlueprint";

    public ComponentBatch ContainerKind { get; private set; }
    public ComponentBatch? DisplayName { get; private set; }
    public ComponentBatch? Contents { get; private set; }
    public ComponentBatch? ColShares { get; private set; }
    public ComponentBatch? RowShares { get; private set; }
    public ComponentBatch? ActiveTab { get; private set; }
    public ComponentBatch? Visible { get; private set; }
    public ComponentBatch? GridColumns { get; private set; }

    public ContainerBlueprint(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ContainerKind> container_kind)
    {
        ContainerKind = ComponentBatch.FromLoggable(container_kind,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:container_kind", "rerun.blueprint.components.ContainerKind"));
    }

    public ContainerBlueprint(params global::Rerun.Net.Blueprint.Components.ContainerKind[] container_kind) : this(container_kind.AsSpan()) { }

    public ContainerBlueprint WithDisplayName(ReadOnlySpan<global::Rerun.Net.Components.Name> display_name)
    {
        DisplayName = ComponentBatch.FromLoggable(display_name,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:display_name", "rerun.components.Name"));
        return this;
    }

    public ContainerBlueprint WithDisplayName(params global::Rerun.Net.Components.Name[] display_name) => WithDisplayName(display_name.AsSpan());

    public ContainerBlueprint WithContents(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.IncludedContent> contents)
    {
        Contents = ComponentBatch.FromLoggable(contents,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:contents", "rerun.blueprint.components.IncludedContent"));
        return this;
    }

    public ContainerBlueprint WithContents(params global::Rerun.Net.Blueprint.Components.IncludedContent[] contents) => WithContents(contents.AsSpan());

    public ContainerBlueprint WithColShares(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ColumnShare> col_shares)
    {
        ColShares = ComponentBatch.FromLoggable(col_shares,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:col_shares", "rerun.blueprint.components.ColumnShare"));
        return this;
    }

    public ContainerBlueprint WithColShares(params global::Rerun.Net.Blueprint.Components.ColumnShare[] col_shares) => WithColShares(col_shares.AsSpan());

    public ContainerBlueprint WithRowShares(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.RowShare> row_shares)
    {
        RowShares = ComponentBatch.FromLoggable(row_shares,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:row_shares", "rerun.blueprint.components.RowShare"));
        return this;
    }

    public ContainerBlueprint WithRowShares(params global::Rerun.Net.Blueprint.Components.RowShare[] row_shares) => WithRowShares(row_shares.AsSpan());

    public ContainerBlueprint WithActiveTab(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ActiveTab> active_tab)
    {
        ActiveTab = ComponentBatch.FromLoggable(active_tab,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:active_tab", "rerun.blueprint.components.ActiveTab"));
        return this;
    }

    public ContainerBlueprint WithActiveTab(params global::Rerun.Net.Blueprint.Components.ActiveTab[] active_tab) => WithActiveTab(active_tab.AsSpan());

    public ContainerBlueprint WithVisible(ReadOnlySpan<global::Rerun.Net.Components.Visible> visible)
    {
        Visible = ComponentBatch.FromLoggable(visible,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:visible", "rerun.components.Visible"));
        return this;
    }

    public ContainerBlueprint WithVisible(params global::Rerun.Net.Components.Visible[] visible) => WithVisible(visible.AsSpan());

    public ContainerBlueprint WithGridColumns(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.GridColumns> grid_columns)
    {
        GridColumns = ComponentBatch.FromLoggable(grid_columns,
            new ComponentDescriptor(ArchetypeName, "ContainerBlueprint:grid_columns", "rerun.blueprint.components.GridColumns"));
        return this;
    }

    public ContainerBlueprint WithGridColumns(params global::Rerun.Net.Blueprint.Components.GridColumns[] grid_columns) => WithGridColumns(grid_columns.AsSpan());

    /// <summary>Create an empty ContainerBlueprint for partial updates. Use With*() to set fields.</summary>
    public static ContainerBlueprint UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ContainerBlueprint ClearFields() => new();

    private ContainerBlueprint() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(ContainerKind);
        if (DisplayName != null) batches.Add(DisplayName);
        if (Contents != null) batches.Add(Contents);
        if (ColShares != null) batches.Add(ColShares);
        if (RowShares != null) batches.Add(RowShares);
        if (ActiveTab != null) batches.Add(ActiveTab);
        if (Visible != null) batches.Add(Visible);
        if (GridColumns != null) batches.Add(GridColumns);
        return batches;
    }
}
