// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// The query for the dataframe view.
/// </summary>
public sealed partial class DataframeQuery : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.DataframeQuery";

    public ComponentBatch? Timeline { get; private set; }
    public ComponentBatch? FilterByRange { get; private set; }
    public ComponentBatch? FilterIsNotNull { get; private set; }
    public ComponentBatch? ApplyLatestAt { get; private set; }
    public ComponentBatch? Select { get; private set; }
    public ComponentBatch? EntityOrder { get; private set; }
    public ComponentBatch? AutoScroll { get; private set; }

    public DataframeQuery() { }

    public DataframeQuery WithTimeline(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TimelineName> timeline)
    {
        Timeline = ComponentBatch.FromLoggable(timeline,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:timeline", "rerun.blueprint.components.TimelineName"));
        return this;
    }

    public DataframeQuery WithTimeline(params global::Rerun.Net.Blueprint.Components.TimelineName[] timeline) => WithTimeline(timeline.AsSpan());

    public DataframeQuery WithFilterByRange(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.FilterByRange> filter_by_range)
    {
        FilterByRange = ComponentBatch.FromLoggable(filter_by_range,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:filter_by_range", "rerun.blueprint.components.FilterByRange"));
        return this;
    }

    public DataframeQuery WithFilterByRange(params global::Rerun.Net.Blueprint.Components.FilterByRange[] filter_by_range) => WithFilterByRange(filter_by_range.AsSpan());

    public DataframeQuery WithFilterIsNotNull(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.FilterIsNotNull> filter_is_not_null)
    {
        FilterIsNotNull = ComponentBatch.FromLoggable(filter_is_not_null,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:filter_is_not_null", "rerun.blueprint.components.FilterIsNotNull"));
        return this;
    }

    public DataframeQuery WithFilterIsNotNull(params global::Rerun.Net.Blueprint.Components.FilterIsNotNull[] filter_is_not_null) => WithFilterIsNotNull(filter_is_not_null.AsSpan());

    public DataframeQuery WithApplyLatestAt(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ApplyLatestAt> apply_latest_at)
    {
        ApplyLatestAt = ComponentBatch.FromLoggable(apply_latest_at,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:apply_latest_at", "rerun.blueprint.components.ApplyLatestAt"));
        return this;
    }

    public DataframeQuery WithApplyLatestAt(params global::Rerun.Net.Blueprint.Components.ApplyLatestAt[] apply_latest_at) => WithApplyLatestAt(apply_latest_at.AsSpan());

    public DataframeQuery WithSelect(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.SelectedColumns> select)
    {
        Select = ComponentBatch.FromLoggable(select,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:select", "rerun.blueprint.components.SelectedColumns"));
        return this;
    }

    public DataframeQuery WithSelect(params global::Rerun.Net.Blueprint.Components.SelectedColumns[] select) => WithSelect(select.AsSpan());

    public DataframeQuery WithEntityOrder(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ColumnOrder> entity_order)
    {
        EntityOrder = ComponentBatch.FromLoggable(entity_order,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:entity_order", "rerun.blueprint.components.ColumnOrder"));
        return this;
    }

    public DataframeQuery WithEntityOrder(params global::Rerun.Net.Blueprint.Components.ColumnOrder[] entity_order) => WithEntityOrder(entity_order.AsSpan());

    public DataframeQuery WithAutoScroll(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.AutoScroll> auto_scroll)
    {
        AutoScroll = ComponentBatch.FromLoggable(auto_scroll,
            new ComponentDescriptor(ArchetypeName, "DataframeQuery:auto_scroll", "rerun.blueprint.components.AutoScroll"));
        return this;
    }

    public DataframeQuery WithAutoScroll(params global::Rerun.Net.Blueprint.Components.AutoScroll[] auto_scroll) => WithAutoScroll(auto_scroll.AsSpan());

    /// <summary>Create an empty DataframeQuery for partial updates. Use With*() to set fields.</summary>
    public static DataframeQuery UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static DataframeQuery ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(7);
        if (Timeline != null) batches.Add(Timeline);
        if (FilterByRange != null) batches.Add(FilterByRange);
        if (FilterIsNotNull != null) batches.Add(FilterIsNotNull);
        if (ApplyLatestAt != null) batches.Add(ApplyLatestAt);
        if (Select != null) batches.Add(Select);
        if (EntityOrder != null) batches.Add(EntityOrder);
        if (AutoScroll != null) batches.Add(AutoScroll);
        return batches;
    }
}
