// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// General visualization behavior of an entity.
/// 
/// TODO(#6541): Fields of this archetype currently only have an effect when logged in the blueprint store.
/// 
/// </summary>
public sealed partial class EntityBehavior : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.EntityBehavior";

    public ComponentBatch? Interactive { get; private set; }
    public ComponentBatch? Visible { get; private set; }

    public EntityBehavior() { }

    public EntityBehavior WithInteractive(ReadOnlySpan<global::Rerun.Net.Components.Interactive> interactive)
    {
        Interactive = ComponentBatch.FromLoggable(interactive,
            new ComponentDescriptor(ArchetypeName, "EntityBehavior:interactive", "rerun.components.Interactive"));
        return this;
    }

    public EntityBehavior WithInteractive(params global::Rerun.Net.Components.Interactive[] interactive) => WithInteractive(interactive.AsSpan());

    public EntityBehavior WithVisible(ReadOnlySpan<global::Rerun.Net.Components.Visible> visible)
    {
        Visible = ComponentBatch.FromLoggable(visible,
            new ComponentDescriptor(ArchetypeName, "EntityBehavior:visible", "rerun.components.Visible"));
        return this;
    }

    public EntityBehavior WithVisible(params global::Rerun.Net.Components.Visible[] visible) => WithVisible(visible.AsSpan());

    /// <summary>Create an empty EntityBehavior for partial updates. Use With*() to set fields.</summary>
    public static EntityBehavior UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static EntityBehavior ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (Interactive != null) batches.Add(Interactive);
        if (Visible != null) batches.Add(Visible);
        return batches;
    }
}
