// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration of a background in a graph view.
/// </summary>
public sealed partial class GraphBackground : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.GraphBackground";

    public ComponentBatch? Color { get; private set; }

    public GraphBackground() { }

    public GraphBackground WithColor(ReadOnlySpan<global::Rerun.Net.Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "GraphBackground:color", "rerun.components.Color"));
        return this;
    }

    public GraphBackground WithColor(params global::Rerun.Net.Components.Color[] color) => WithColor(color.AsSpan());

    /// <summary>Create an empty GraphBackground for partial updates. Use With*() to set fields.</summary>
    public static GraphBackground UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static GraphBackground ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (Color != null) batches.Add(Color);
        return batches;
    }
}
