// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the 3D line grid.
/// </summary>
public sealed partial class LineGrid3D : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.LineGrid3D";

    public ComponentBatch? Visible { get; private set; }
    public ComponentBatch? Spacing { get; private set; }
    public ComponentBatch? Plane { get; private set; }
    public ComponentBatch? StrokeWidth { get; private set; }
    public ComponentBatch? Color { get; private set; }

    public LineGrid3D() { }

    public LineGrid3D WithVisible(ReadOnlySpan<global::Rerun.Net.Components.Visible> visible)
    {
        Visible = ComponentBatch.FromLoggable(visible,
            new ComponentDescriptor(ArchetypeName, "LineGrid3D:visible", "rerun.components.Visible"));
        return this;
    }

    public LineGrid3D WithVisible(params global::Rerun.Net.Components.Visible[] visible) => WithVisible(visible.AsSpan());

    public LineGrid3D WithSpacing(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.GridSpacing> spacing)
    {
        Spacing = ComponentBatch.FromLoggable(spacing,
            new ComponentDescriptor(ArchetypeName, "LineGrid3D:spacing", "rerun.blueprint.components.GridSpacing"));
        return this;
    }

    public LineGrid3D WithSpacing(params global::Rerun.Net.Blueprint.Components.GridSpacing[] spacing) => WithSpacing(spacing.AsSpan());

    public LineGrid3D WithPlane(ReadOnlySpan<global::Rerun.Net.Components.Plane3D> plane)
    {
        Plane = ComponentBatch.FromLoggable(plane,
            new ComponentDescriptor(ArchetypeName, "LineGrid3D:plane", "rerun.components.Plane3D"));
        return this;
    }

    public LineGrid3D WithPlane(params global::Rerun.Net.Components.Plane3D[] plane) => WithPlane(plane.AsSpan());

    public LineGrid3D WithStrokeWidth(ReadOnlySpan<global::Rerun.Net.Components.StrokeWidth> stroke_width)
    {
        StrokeWidth = ComponentBatch.FromLoggable(stroke_width,
            new ComponentDescriptor(ArchetypeName, "LineGrid3D:stroke_width", "rerun.components.StrokeWidth"));
        return this;
    }

    public LineGrid3D WithStrokeWidth(params global::Rerun.Net.Components.StrokeWidth[] stroke_width) => WithStrokeWidth(stroke_width.AsSpan());

    public LineGrid3D WithColor(ReadOnlySpan<global::Rerun.Net.Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "LineGrid3D:color", "rerun.components.Color"));
        return this;
    }

    public LineGrid3D WithColor(params global::Rerun.Net.Components.Color[] color) => WithColor(color.AsSpan());

    /// <summary>Create an empty LineGrid3D for partial updates. Use With*() to set fields.</summary>
    public static LineGrid3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static LineGrid3D ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        if (Visible != null) batches.Add(Visible);
        if (Spacing != null) batches.Add(Spacing);
        if (Plane != null) batches.Add(Plane);
        if (StrokeWidth != null) batches.Add(StrokeWidth);
        if (Color != null) batches.Add(Color);
        return batches;
    }
}
