// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the background map of the map view.
/// </summary>
public sealed partial class MapBackground : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.MapBackground";

    public ComponentBatch? Provider { get; private set; }

    public MapBackground() { }

    public MapBackground WithProvider(ReadOnlySpan<Components.MapProvider> provider)
    {
        Provider = ComponentBatch.FromLoggable(provider,
            new ComponentDescriptor(ArchetypeName, "MapBackground:provider", "rerun.blueprint.components.MapProvider"));
        return this;
    }

    public MapBackground WithProvider(params Components.MapProvider[] provider) => WithProvider(provider.AsSpan());

    /// <summary>Create an empty MapBackground for partial updates. Use With*() to set fields.</summary>
    public static MapBackground UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static MapBackground ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (Provider != null) batches.Add(Provider);
        return batches;
    }
}
