// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

public sealed partial class MapZoom : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.MapZoom";

    public ComponentBatch? Zoom { get; private set; }

    public MapZoom() { }

    public MapZoom WithZoom(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ZoomLevel> zoom)
    {
        Zoom = ComponentBatch.FromLoggable(zoom,
            new ComponentDescriptor(ArchetypeName, "MapZoom:zoom", "rerun.blueprint.components.ZoomLevel"));
        return this;
    }

    public MapZoom WithZoom(params global::Rerun.Net.Blueprint.Components.ZoomLevel[] zoom) => WithZoom(zoom.AsSpan());

    /// <summary>Create an empty MapZoom for partial updates. Use With*() to set fields.</summary>
    public static MapZoom UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static MapZoom ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (Zoom != null) batches.Add(Zoom);
        return batches;
    }
}
