// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Controls the distance to the near clip plane in 3D scene units.
/// </summary>
public sealed partial class NearClipPlane : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.NearClipPlane";

    public ComponentBatch? NearClipPlaneValue { get; private set; }

    public NearClipPlane() { }

    public NearClipPlane WithNearClipPlaneValue(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.NearClipPlane> near_clip_plane)
    {
        NearClipPlaneValue = ComponentBatch.FromLoggable(near_clip_plane,
            new ComponentDescriptor(ArchetypeName, "NearClipPlane:near_clip_plane", "rerun.blueprint.components.NearClipPlane"));
        return this;
    }

    public NearClipPlane WithNearClipPlaneValue(params global::Rerun.Net.Blueprint.Components.NearClipPlane[] near_clip_plane) => WithNearClipPlaneValue(near_clip_plane.AsSpan());

    /// <summary>Create an empty NearClipPlane for partial updates. Use With*() to set fields.</summary>
    public static NearClipPlane UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static NearClipPlane ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (NearClipPlaneValue != null) batches.Add(NearClipPlaneValue);
        return batches;
    }
}
