// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Shared state for the 3 collapsible panels.
/// </summary>
public sealed partial class PanelBlueprint : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.PanelBlueprint";

    public ComponentBatch? State { get; private set; }

    public PanelBlueprint() { }

    public PanelBlueprint WithState(ReadOnlySpan<Components.PanelState> state)
    {
        State = ComponentBatch.FromLoggable(state,
            new ComponentDescriptor(ArchetypeName, "PanelBlueprint:state", "rerun.blueprint.components.PanelState"));
        return this;
    }

    public PanelBlueprint WithState(params Components.PanelState[] state) => WithState(state.AsSpan());

    /// <summary>Create an empty PanelBlueprint for partial updates. Use With*() to set fields.</summary>
    public static PanelBlueprint UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static PanelBlueprint ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (State != null) batches.Add(State);
        return batches;
    }
}
