// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the legend of a plot.
/// </summary>
public sealed partial class PlotLegend : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.PlotLegend";

    public ComponentBatch? Corner { get; private set; }
    public ComponentBatch? Visible { get; private set; }

    public PlotLegend() { }

    public PlotLegend WithCorner(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.Corner2D> corner)
    {
        Corner = ComponentBatch.FromLoggable(corner,
            new ComponentDescriptor(ArchetypeName, "PlotLegend:corner", "rerun.blueprint.components.Corner2D"));
        return this;
    }

    public PlotLegend WithCorner(params global::Rerun.Net.Blueprint.Components.Corner2D[] corner) => WithCorner(corner.AsSpan());

    public PlotLegend WithVisible(ReadOnlySpan<global::Rerun.Net.Components.Visible> visible)
    {
        Visible = ComponentBatch.FromLoggable(visible,
            new ComponentDescriptor(ArchetypeName, "PlotLegend:visible", "rerun.components.Visible"));
        return this;
    }

    public PlotLegend WithVisible(params global::Rerun.Net.Components.Visible[] visible) => WithVisible(visible.AsSpan());

    /// <summary>Create an empty PlotLegend for partial updates. Use With*() to set fields.</summary>
    public static PlotLegend UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static PlotLegend ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (Corner != null) batches.Add(Corner);
        if (Visible != null) batches.Add(Visible);
        return batches;
    }
}
