// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration of a background in a plot view.
/// </summary>
public sealed partial class PlotBackground : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.PlotBackground";

    public ComponentBatch? Color { get; private set; }
    public ComponentBatch? ShowGrid { get; private set; }

    public PlotBackground() { }

    public PlotBackground WithColor(ReadOnlySpan<global::Rerun.Net.Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "PlotBackground:color", "rerun.components.Color"));
        return this;
    }

    public PlotBackground WithColor(params global::Rerun.Net.Components.Color[] color) => WithColor(color.AsSpan());

    public PlotBackground WithShowGrid(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.Enabled> show_grid)
    {
        ShowGrid = ComponentBatch.FromLoggable(show_grid,
            new ComponentDescriptor(ArchetypeName, "PlotBackground:show_grid", "rerun.blueprint.components.Enabled"));
        return this;
    }

    public PlotBackground WithShowGrid(params global::Rerun.Net.Blueprint.Components.Enabled[] show_grid) => WithShowGrid(show_grid.AsSpan());

    /// <summary>Create an empty PlotBackground for partial updates. Use With*() to set fields.</summary>
    public static PlotBackground UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static PlotBackground ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (Color != null) batches.Add(Color);
        if (ShowGrid != null) batches.Add(ShowGrid);
        return batches;
    }
}
