// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the scalar (Y) axis of a plot.
/// </summary>
public sealed partial class ScalarAxis : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ScalarAxis";

    public ComponentBatch? Range { get; private set; }
    public ComponentBatch? ZoomLock { get; private set; }

    public ScalarAxis() { }

    public ScalarAxis WithRange(ReadOnlySpan<global::Rerun.Net.Components.Range1D> range)
    {
        Range = ComponentBatch.FromLoggable(range,
            new ComponentDescriptor(ArchetypeName, "ScalarAxis:range", "rerun.components.Range1D"));
        return this;
    }

    public ScalarAxis WithRange(params global::Rerun.Net.Components.Range1D[] range) => WithRange(range.AsSpan());

    public ScalarAxis WithZoomLock(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.LockRangeDuringZoom> zoom_lock)
    {
        ZoomLock = ComponentBatch.FromLoggable(zoom_lock,
            new ComponentDescriptor(ArchetypeName, "ScalarAxis:zoom_lock", "rerun.blueprint.components.LockRangeDuringZoom"));
        return this;
    }

    public ScalarAxis WithZoomLock(params global::Rerun.Net.Blueprint.Components.LockRangeDuringZoom[] zoom_lock) => WithZoomLock(zoom_lock.AsSpan());

    /// <summary>Create an empty ScalarAxis for partial updates. Use With*() to set fields.</summary>
    public static ScalarAxis UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ScalarAxis ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (Range != null) batches.Add(Range);
        if (ZoomLock != null) batches.Add(ZoomLock);
        return batches;
    }
}
