// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// This configures extra drawing config for the 3D view.
/// </summary>
public sealed partial class SpatialInformation : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.SpatialInformation";

    public ComponentBatch? TargetFrame { get; private set; }
    public ComponentBatch? ShowAxes { get; private set; }
    public ComponentBatch? ShowBoundingBox { get; private set; }

    public SpatialInformation() { }

    public SpatialInformation WithTargetFrame(ReadOnlySpan<global::Rerun.Net.Components.TransformFrameId> target_frame)
    {
        TargetFrame = ComponentBatch.FromLoggable(target_frame,
            new ComponentDescriptor(ArchetypeName, "SpatialInformation:target_frame", "rerun.components.TransformFrameId"));
        return this;
    }

    public SpatialInformation WithTargetFrame(params global::Rerun.Net.Components.TransformFrameId[] target_frame) => WithTargetFrame(target_frame.AsSpan());

    public SpatialInformation WithShowAxes(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.Enabled> show_axes)
    {
        ShowAxes = ComponentBatch.FromLoggable(show_axes,
            new ComponentDescriptor(ArchetypeName, "SpatialInformation:show_axes", "rerun.blueprint.components.Enabled"));
        return this;
    }

    public SpatialInformation WithShowAxes(params global::Rerun.Net.Blueprint.Components.Enabled[] show_axes) => WithShowAxes(show_axes.AsSpan());

    public SpatialInformation WithShowBoundingBox(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.Enabled> show_bounding_box)
    {
        ShowBoundingBox = ComponentBatch.FromLoggable(show_bounding_box,
            new ComponentDescriptor(ArchetypeName, "SpatialInformation:show_bounding_box", "rerun.blueprint.components.Enabled"));
        return this;
    }

    public SpatialInformation WithShowBoundingBox(params global::Rerun.Net.Blueprint.Components.Enabled[] show_bounding_box) => WithShowBoundingBox(show_bounding_box.AsSpan());

    /// <summary>Create an empty SpatialInformation for partial updates. Use With*() to set fields.</summary>
    public static SpatialInformation UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static SpatialInformation ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        if (TargetFrame != null) batches.Add(TargetFrame);
        if (ShowAxes != null) batches.Add(ShowAxes);
        if (ShowBoundingBox != null) batches.Add(ShowBoundingBox);
        return batches;
    }
}
