// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configures how a selected tensor slice is shown on screen.
/// </summary>
public sealed partial class TensorViewFit : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TensorViewFit";

    public ComponentBatch? Scaling { get; private set; }

    public TensorViewFit() { }

    public TensorViewFit WithScaling(ReadOnlySpan<Components.ViewFit> scaling)
    {
        Scaling = ComponentBatch.FromLoggable(scaling,
            new ComponentDescriptor(ArchetypeName, "TensorViewFit:scaling", "rerun.blueprint.components.ViewFit"));
        return this;
    }

    public TensorViewFit WithScaling(params Components.ViewFit[] scaling) => WithScaling(scaling.AsSpan());

    /// <summary>Create an empty TensorViewFit for partial updates. Use With*() to set fields.</summary>
    public static TensorViewFit UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TensorViewFit ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (Scaling != null) batches.Add(Scaling);
        return batches;
    }
}
