// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Specifies a 2D slice of a tensor.
/// </summary>
public sealed partial class TensorSliceSelection : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TensorSliceSelection";

    public ComponentBatch? Width { get; private set; }
    public ComponentBatch? Height { get; private set; }
    public ComponentBatch? Indices { get; private set; }
    public ComponentBatch? Slider { get; private set; }

    public TensorSliceSelection() { }

    public TensorSliceSelection WithWidth(ReadOnlySpan<global::Rerun.Net.Components.TensorWidthDimension> width)
    {
        Width = ComponentBatch.FromLoggable(width,
            new ComponentDescriptor(ArchetypeName, "TensorSliceSelection:width", "rerun.components.TensorWidthDimension"));
        return this;
    }

    public TensorSliceSelection WithWidth(params global::Rerun.Net.Components.TensorWidthDimension[] width) => WithWidth(width.AsSpan());

    public TensorSliceSelection WithHeight(ReadOnlySpan<global::Rerun.Net.Components.TensorHeightDimension> height)
    {
        Height = ComponentBatch.FromLoggable(height,
            new ComponentDescriptor(ArchetypeName, "TensorSliceSelection:height", "rerun.components.TensorHeightDimension"));
        return this;
    }

    public TensorSliceSelection WithHeight(params global::Rerun.Net.Components.TensorHeightDimension[] height) => WithHeight(height.AsSpan());

    public TensorSliceSelection WithIndices(ReadOnlySpan<global::Rerun.Net.Components.TensorDimensionIndexSelection> indices)
    {
        Indices = ComponentBatch.FromLoggable(indices,
            new ComponentDescriptor(ArchetypeName, "TensorSliceSelection:indices", "rerun.components.TensorDimensionIndexSelection"));
        return this;
    }

    public TensorSliceSelection WithIndices(params global::Rerun.Net.Components.TensorDimensionIndexSelection[] indices) => WithIndices(indices.AsSpan());

    public TensorSliceSelection WithSlider(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TensorDimensionIndexSlider> slider)
    {
        Slider = ComponentBatch.FromLoggable(slider,
            new ComponentDescriptor(ArchetypeName, "TensorSliceSelection:slider", "rerun.blueprint.components.TensorDimensionIndexSlider"));
        return this;
    }

    public TensorSliceSelection WithSlider(params global::Rerun.Net.Blueprint.Components.TensorDimensionIndexSlider[] slider) => WithSlider(slider.AsSpan());

    /// <summary>Create an empty TensorSliceSelection for partial updates. Use With*() to set fields.</summary>
    public static TensorSliceSelection UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TensorSliceSelection ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        if (Width != null) batches.Add(Width);
        if (Height != null) batches.Add(Height);
        if (Indices != null) batches.Add(Indices);
        if (Slider != null) batches.Add(Slider);
        return batches;
    }
}
