// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configures how tensor scalars are mapped to color.
/// </summary>
public sealed partial class TensorScalarMapping : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TensorScalarMapping";

    public ComponentBatch? MagFilter { get; private set; }
    public ComponentBatch? Colormap { get; private set; }
    public ComponentBatch? Gamma { get; private set; }

    public TensorScalarMapping() { }

    public TensorScalarMapping WithMagFilter(ReadOnlySpan<global::Rerun.Net.Components.MagnificationFilter> mag_filter)
    {
        MagFilter = ComponentBatch.FromLoggable(mag_filter,
            new ComponentDescriptor(ArchetypeName, "TensorScalarMapping:mag_filter", "rerun.components.MagnificationFilter"));
        return this;
    }

    public TensorScalarMapping WithMagFilter(params global::Rerun.Net.Components.MagnificationFilter[] mag_filter) => WithMagFilter(mag_filter.AsSpan());

    public TensorScalarMapping WithColormap(ReadOnlySpan<global::Rerun.Net.Components.Colormap> colormap)
    {
        Colormap = ComponentBatch.FromLoggable(colormap,
            new ComponentDescriptor(ArchetypeName, "TensorScalarMapping:colormap", "rerun.components.Colormap"));
        return this;
    }

    public TensorScalarMapping WithColormap(params global::Rerun.Net.Components.Colormap[] colormap) => WithColormap(colormap.AsSpan());

    public TensorScalarMapping WithGamma(ReadOnlySpan<global::Rerun.Net.Components.GammaCorrection> gamma)
    {
        Gamma = ComponentBatch.FromLoggable(gamma,
            new ComponentDescriptor(ArchetypeName, "TensorScalarMapping:gamma", "rerun.components.GammaCorrection"));
        return this;
    }

    public TensorScalarMapping WithGamma(params global::Rerun.Net.Components.GammaCorrection[] gamma) => WithGamma(gamma.AsSpan());

    /// <summary>Create an empty TensorScalarMapping for partial updates. Use With*() to set fields.</summary>
    public static TensorScalarMapping UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TensorScalarMapping ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        if (MagFilter != null) batches.Add(MagFilter);
        if (Colormap != null) batches.Add(Colormap);
        if (Gamma != null) batches.Add(Gamma);
        return batches;
    }
}
