// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration of the text log rows.
/// </summary>
public sealed partial class TextLogRows : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TextLogRows";

    public ComponentBatch? FilterByLogLevel { get; private set; }

    public TextLogRows() { }

    public TextLogRows WithFilterByLogLevel(ReadOnlySpan<global::Rerun.Net.Components.TextLogLevel> filter_by_log_level)
    {
        FilterByLogLevel = ComponentBatch.FromLoggable(filter_by_log_level,
            new ComponentDescriptor(ArchetypeName, "TextLogRows:filter_by_log_level", "rerun.components.TextLogLevel"));
        return this;
    }

    public TextLogRows WithFilterByLogLevel(params global::Rerun.Net.Components.TextLogLevel[] filter_by_log_level) => WithFilterByLogLevel(filter_by_log_level.AsSpan());

    /// <summary>Create an empty TextLogRows for partial updates. Use With*() to set fields.</summary>
    public static TextLogRows UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TextLogRows ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (FilterByLogLevel != null) batches.Add(FilterByLogLevel);
        return batches;
    }
}
