// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration of the text log rows.
/// </summary>
public sealed partial class TextLogFormat : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TextLogFormat";

    public ComponentBatch? MonospaceBody { get; private set; }

    public TextLogFormat() { }

    public TextLogFormat WithMonospaceBody(ReadOnlySpan<Components.Enabled> monospace_body)
    {
        MonospaceBody = ComponentBatch.FromLoggable(monospace_body,
            new ComponentDescriptor(ArchetypeName, "TextLogFormat:monospace_body", "rerun.blueprint.components.Enabled"));
        return this;
    }

    public TextLogFormat WithMonospaceBody(params Components.Enabled[] monospace_body) => WithMonospaceBody(monospace_body.AsSpan());

    /// <summary>Create an empty TextLogFormat for partial updates. Use With*() to set fields.</summary>
    public static TextLogFormat UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TextLogFormat ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (MonospaceBody != null) batches.Add(MonospaceBody);
        return batches;
    }
}
