// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration of the text log columns.
/// </summary>
public sealed partial class TextLogColumns : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TextLogColumns";

    public ComponentBatch? TimelineColumns { get; private set; }
    public ComponentBatch? TextLogColumnsValue { get; private set; }

    public TextLogColumns() { }

    public TextLogColumns WithTimelineColumns(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TimelineColumn> timeline_columns)
    {
        TimelineColumns = ComponentBatch.FromLoggable(timeline_columns,
            new ComponentDescriptor(ArchetypeName, "TextLogColumns:timeline_columns", "rerun.blueprint.components.TimelineColumn"));
        return this;
    }

    public TextLogColumns WithTimelineColumns(params global::Rerun.Net.Blueprint.Components.TimelineColumn[] timeline_columns) => WithTimelineColumns(timeline_columns.AsSpan());

    public TextLogColumns WithTextLogColumnsValue(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TextLogColumn> text_log_columns)
    {
        TextLogColumnsValue = ComponentBatch.FromLoggable(text_log_columns,
            new ComponentDescriptor(ArchetypeName, "TextLogColumns:text_log_columns", "rerun.blueprint.components.TextLogColumn"));
        return this;
    }

    public TextLogColumns WithTextLogColumnsValue(params global::Rerun.Net.Blueprint.Components.TextLogColumn[] text_log_columns) => WithTextLogColumnsValue(text_log_columns.AsSpan());

    /// <summary>Create an empty TextLogColumns for partial updates. Use With*() to set fields.</summary>
    public static TextLogColumns UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TextLogColumns ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (TimelineColumns != null) batches.Add(TimelineColumns);
        if (TextLogColumnsValue != null) batches.Add(TextLogColumnsValue);
        return batches;
    }
}
