// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Time panel specific state.
/// </summary>
public sealed partial class TimePanelBlueprint : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TimePanelBlueprint";

    public ComponentBatch? State { get; private set; }
    public ComponentBatch? Timeline { get; private set; }
    public ComponentBatch? PlaybackSpeed { get; private set; }
    public ComponentBatch? Fps { get; private set; }
    public ComponentBatch? PlayState { get; private set; }
    public ComponentBatch? LoopMode { get; private set; }
    public ComponentBatch? TimeSelection { get; private set; }

    public TimePanelBlueprint() { }

    public TimePanelBlueprint WithState(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.PanelState> state)
    {
        State = ComponentBatch.FromLoggable(state,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:state", "rerun.blueprint.components.PanelState"));
        return this;
    }

    public TimePanelBlueprint WithState(params global::Rerun.Net.Blueprint.Components.PanelState[] state) => WithState(state.AsSpan());

    public TimePanelBlueprint WithTimeline(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TimelineName> timeline)
    {
        Timeline = ComponentBatch.FromLoggable(timeline,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:timeline", "rerun.blueprint.components.TimelineName"));
        return this;
    }

    public TimePanelBlueprint WithTimeline(params global::Rerun.Net.Blueprint.Components.TimelineName[] timeline) => WithTimeline(timeline.AsSpan());

    public TimePanelBlueprint WithPlaybackSpeed(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.PlaybackSpeed> playback_speed)
    {
        PlaybackSpeed = ComponentBatch.FromLoggable(playback_speed,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:playback_speed", "rerun.blueprint.components.PlaybackSpeed"));
        return this;
    }

    public TimePanelBlueprint WithPlaybackSpeed(params global::Rerun.Net.Blueprint.Components.PlaybackSpeed[] playback_speed) => WithPlaybackSpeed(playback_speed.AsSpan());

    public TimePanelBlueprint WithFps(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.Fps> fps)
    {
        Fps = ComponentBatch.FromLoggable(fps,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:fps", "rerun.blueprint.components.Fps"));
        return this;
    }

    public TimePanelBlueprint WithFps(params global::Rerun.Net.Blueprint.Components.Fps[] fps) => WithFps(fps.AsSpan());

    public TimePanelBlueprint WithPlayState(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.PlayState> play_state)
    {
        PlayState = ComponentBatch.FromLoggable(play_state,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:play_state", "rerun.blueprint.components.PlayState"));
        return this;
    }

    public TimePanelBlueprint WithPlayState(params global::Rerun.Net.Blueprint.Components.PlayState[] play_state) => WithPlayState(play_state.AsSpan());

    public TimePanelBlueprint WithLoopMode(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.LoopMode> loop_mode)
    {
        LoopMode = ComponentBatch.FromLoggable(loop_mode,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:loop_mode", "rerun.blueprint.components.LoopMode"));
        return this;
    }

    public TimePanelBlueprint WithLoopMode(params global::Rerun.Net.Blueprint.Components.LoopMode[] loop_mode) => WithLoopMode(loop_mode.AsSpan());

    public TimePanelBlueprint WithTimeSelection(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.AbsoluteTimeRange> time_selection)
    {
        TimeSelection = ComponentBatch.FromLoggable(time_selection,
            new ComponentDescriptor(ArchetypeName, "TimePanelBlueprint:time_selection", "rerun.blueprint.components.AbsoluteTimeRange"));
        return this;
    }

    public TimePanelBlueprint WithTimeSelection(params global::Rerun.Net.Blueprint.Components.AbsoluteTimeRange[] time_selection) => WithTimeSelection(time_selection.AsSpan());

    /// <summary>Create an empty TimePanelBlueprint for partial updates. Use With*() to set fields.</summary>
    public static TimePanelBlueprint UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TimePanelBlueprint ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(7);
        if (State != null) batches.Add(State);
        if (Timeline != null) batches.Add(Timeline);
        if (PlaybackSpeed != null) batches.Add(PlaybackSpeed);
        if (Fps != null) batches.Add(Fps);
        if (PlayState != null) batches.Add(PlayState);
        if (LoopMode != null) batches.Add(LoopMode);
        if (TimeSelection != null) batches.Add(TimeSelection);
        return batches;
    }
}
