// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configuration for the time (X) axis of a plot.
/// </summary>
public sealed partial class TimeAxis : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.TimeAxis";

    public ComponentBatch? Link { get; private set; }
    public ComponentBatch? ViewRange { get; private set; }
    public ComponentBatch? ZoomLock { get; private set; }

    public TimeAxis() { }

    public TimeAxis WithLink(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.LinkAxis> link)
    {
        Link = ComponentBatch.FromLoggable(link,
            new ComponentDescriptor(ArchetypeName, "TimeAxis:link", "rerun.blueprint.components.LinkAxis"));
        return this;
    }

    public TimeAxis WithLink(params global::Rerun.Net.Blueprint.Components.LinkAxis[] link) => WithLink(link.AsSpan());

    public TimeAxis WithViewRange(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.TimeRange> view_range)
    {
        ViewRange = ComponentBatch.FromLoggable(view_range,
            new ComponentDescriptor(ArchetypeName, "TimeAxis:view_range", "rerun.blueprint.components.TimeRange"));
        return this;
    }

    public TimeAxis WithViewRange(params global::Rerun.Net.Blueprint.Components.TimeRange[] view_range) => WithViewRange(view_range.AsSpan());

    public TimeAxis WithZoomLock(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.LockRangeDuringZoom> zoom_lock)
    {
        ZoomLock = ComponentBatch.FromLoggable(zoom_lock,
            new ComponentDescriptor(ArchetypeName, "TimeAxis:zoom_lock", "rerun.blueprint.components.LockRangeDuringZoom"));
        return this;
    }

    public TimeAxis WithZoomLock(params global::Rerun.Net.Blueprint.Components.LockRangeDuringZoom[] zoom_lock) => WithZoomLock(zoom_lock.AsSpan());

    /// <summary>Create an empty TimeAxis for partial updates. Use With*() to set fields.</summary>
    public static TimeAxis UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TimeAxis ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        if (Link != null) batches.Add(Link);
        if (ViewRange != null) batches.Add(ViewRange);
        if (ZoomLock != null) batches.Add(ZoomLock);
        return batches;
    }
}
