// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// The description of a single view.
/// </summary>
public sealed partial class ViewBlueprint : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ViewBlueprint";

    public ComponentBatch ClassIdentifier { get; private set; }
    public ComponentBatch? DisplayName { get; private set; }
    public ComponentBatch? SpaceOrigin { get; private set; }
    public ComponentBatch? Visible { get; private set; }

    public ViewBlueprint(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ViewClass> class_identifier)
    {
        ClassIdentifier = ComponentBatch.FromLoggable(class_identifier,
            new ComponentDescriptor(ArchetypeName, "ViewBlueprint:class_identifier", "rerun.blueprint.components.ViewClass"));
    }

    public ViewBlueprint(params global::Rerun.Net.Blueprint.Components.ViewClass[] class_identifier) : this(class_identifier.AsSpan()) { }

    public ViewBlueprint WithDisplayName(ReadOnlySpan<global::Rerun.Net.Components.Name> display_name)
    {
        DisplayName = ComponentBatch.FromLoggable(display_name,
            new ComponentDescriptor(ArchetypeName, "ViewBlueprint:display_name", "rerun.components.Name"));
        return this;
    }

    public ViewBlueprint WithDisplayName(params global::Rerun.Net.Components.Name[] display_name) => WithDisplayName(display_name.AsSpan());

    public ViewBlueprint WithSpaceOrigin(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.ViewOrigin> space_origin)
    {
        SpaceOrigin = ComponentBatch.FromLoggable(space_origin,
            new ComponentDescriptor(ArchetypeName, "ViewBlueprint:space_origin", "rerun.blueprint.components.ViewOrigin"));
        return this;
    }

    public ViewBlueprint WithSpaceOrigin(params global::Rerun.Net.Blueprint.Components.ViewOrigin[] space_origin) => WithSpaceOrigin(space_origin.AsSpan());

    public ViewBlueprint WithVisible(ReadOnlySpan<global::Rerun.Net.Components.Visible> visible)
    {
        Visible = ComponentBatch.FromLoggable(visible,
            new ComponentDescriptor(ArchetypeName, "ViewBlueprint:visible", "rerun.components.Visible"));
        return this;
    }

    public ViewBlueprint WithVisible(params global::Rerun.Net.Components.Visible[] visible) => WithVisible(visible.AsSpan());

    /// <summary>Create an empty ViewBlueprint for partial updates. Use With*() to set fields.</summary>
    public static ViewBlueprint UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ViewBlueprint ClearFields() => new();

    private ViewBlueprint() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(ClassIdentifier);
        if (DisplayName != null) batches.Add(DisplayName);
        if (SpaceOrigin != null) batches.Add(SpaceOrigin);
        if (Visible != null) batches.Add(Visible);
        return batches;
    }
}
