// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// The contents of a `View`.
/// 
/// The contents are found by combining a collection of `QueryExpression`s.
/// 
/// ```diff
/// + /world/**           # add everything…
/// - /world/roads/**     # …but remove all roads…
/// + /world/roads/main   # …but show main road
/// ```
/// 
/// If there is multiple matching rules, the most specific rule wins.
/// If there are multiple rules of the same specificity, the last one wins.
/// If no rules match, the path is excluded.
/// 
/// Specifying a path without a `+` or `-` prefix is equivalent to `+`:
/// ```diff
/// /world/**           # add everything…
/// - /world/roads/**   # …but remove all roads…
/// /world/roads/main   # …but show main road
/// ```
/// 
/// The `/**` suffix matches the whole subtree, i.e. self and any child, recursively
/// (`/world/**` matches both `/world` and `/world/car/driver`).
/// Other uses of `*` are not (yet) supported.
/// 
/// Internally, `EntityPathFilter` sorts the rule by entity path, with recursive coming before non-recursive.
/// This means the last matching rule is also the most specific one. For instance:
/// ```diff
/// + /world/**
/// - /world
/// - /world/car/**
/// + /world/car/driver
/// ```
/// 
/// The last rule matching `/world/car/driver` is `+ /world/car/driver`, so it is included.
/// The last rule matching `/world/car/hood` is `- /world/car/**`, so it is excluded.
/// The last rule matching `/world` is `- /world`, so it is excluded.
/// The last rule matching `/world/house` is `+ /world/**`, so it is included.
/// </summary>
public sealed partial class ViewContents : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ViewContents";

    public ComponentBatch? Query { get; private set; }

    public ViewContents() { }

    public ViewContents WithQuery(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.QueryExpression> query)
    {
        Query = ComponentBatch.FromLoggable(query,
            new ComponentDescriptor(ArchetypeName, "ViewContents:query", "rerun.blueprint.components.QueryExpression"));
        return this;
    }

    public ViewContents WithQuery(params global::Rerun.Net.Blueprint.Components.QueryExpression[] query) => WithQuery(query.AsSpan());

    /// <summary>Create an empty ViewContents for partial updates. Use With*() to set fields.</summary>
    public static ViewContents UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ViewContents ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        if (Query != null) batches.Add(Query);
        return batches;
    }
}
