// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// The top-level description of the viewport.
/// </summary>
public sealed partial class ViewportBlueprint : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.ViewportBlueprint";

    public ComponentBatch? RootContainer { get; private set; }
    public ComponentBatch? Maximized { get; private set; }
    public ComponentBatch? AutoLayout { get; private set; }
    public ComponentBatch? AutoViews { get; private set; }
    public ComponentBatch? PastViewerRecommendations { get; private set; }

    public ViewportBlueprint() { }

    public ViewportBlueprint WithRootContainer(ReadOnlySpan<Components.RootContainer> root_container)
    {
        RootContainer = ComponentBatch.FromLoggable(root_container,
            new ComponentDescriptor(ArchetypeName, "ViewportBlueprint:root_container", "rerun.blueprint.components.RootContainer"));
        return this;
    }

    public ViewportBlueprint WithRootContainer(params Components.RootContainer[] root_container) => WithRootContainer(root_container.AsSpan());

    public ViewportBlueprint WithMaximized(ReadOnlySpan<Components.ViewMaximized> maximized)
    {
        Maximized = ComponentBatch.FromLoggable(maximized,
            new ComponentDescriptor(ArchetypeName, "ViewportBlueprint:maximized", "rerun.blueprint.components.ViewMaximized"));
        return this;
    }

    public ViewportBlueprint WithMaximized(params Components.ViewMaximized[] maximized) => WithMaximized(maximized.AsSpan());

    public ViewportBlueprint WithAutoLayout(ReadOnlySpan<Components.AutoLayout> auto_layout)
    {
        AutoLayout = ComponentBatch.FromLoggable(auto_layout,
            new ComponentDescriptor(ArchetypeName, "ViewportBlueprint:auto_layout", "rerun.blueprint.components.AutoLayout"));
        return this;
    }

    public ViewportBlueprint WithAutoLayout(params Components.AutoLayout[] auto_layout) => WithAutoLayout(auto_layout.AsSpan());

    public ViewportBlueprint WithAutoViews(ReadOnlySpan<Components.AutoViews> auto_views)
    {
        AutoViews = ComponentBatch.FromLoggable(auto_views,
            new ComponentDescriptor(ArchetypeName, "ViewportBlueprint:auto_views", "rerun.blueprint.components.AutoViews"));
        return this;
    }

    public ViewportBlueprint WithAutoViews(params Components.AutoViews[] auto_views) => WithAutoViews(auto_views.AsSpan());

    public ViewportBlueprint WithPastViewerRecommendations(ReadOnlySpan<Components.ViewerRecommendationHash> past_viewer_recommendations)
    {
        PastViewerRecommendations = ComponentBatch.FromLoggable(past_viewer_recommendations,
            new ComponentDescriptor(ArchetypeName, "ViewportBlueprint:past_viewer_recommendations", "rerun.blueprint.components.ViewerRecommendationHash"));
        return this;
    }

    public ViewportBlueprint WithPastViewerRecommendations(params Components.ViewerRecommendationHash[] past_viewer_recommendations) => WithPastViewerRecommendations(past_viewer_recommendations.AsSpan());

    /// <summary>Create an empty ViewportBlueprint for partial updates. Use With*() to set fields.</summary>
    public static ViewportBlueprint UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ViewportBlueprint ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        if (RootContainer != null) batches.Add(RootContainer);
        if (Maximized != null) batches.Add(Maximized);
        if (AutoLayout != null) batches.Add(AutoLayout);
        if (AutoViews != null) batches.Add(AutoViews);
        if (PastViewerRecommendations != null) batches.Add(PastViewerRecommendations);
        return batches;
    }
}
