// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Configures what range of each timeline is shown on a view.
/// 
/// Whenever no visual time range applies, queries are done with "latest-at" semantics.
/// This means that the view will, starting from the time cursor position,
/// query the latest data available for each component type.
/// 
/// The default visual time range depends on the type of view this property applies to:
/// - For time series views, the default is to show the entire timeline.
/// - For any other view, the default is to apply latest-at semantics.
/// </summary>
public sealed partial class VisibleTimeRanges : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.VisibleTimeRanges";

    public ComponentBatch Ranges { get; private set; }

    public VisibleTimeRanges(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.VisibleTimeRange> ranges)
    {
        Ranges = ComponentBatch.FromLoggable(ranges,
            new ComponentDescriptor(ArchetypeName, "VisibleTimeRanges:ranges", "rerun.blueprint.components.VisibleTimeRange"));
    }

    public VisibleTimeRanges(params global::Rerun.Net.Blueprint.Components.VisibleTimeRange[] ranges) : this(ranges.AsSpan()) { }

    /// <summary>Create an empty VisibleTimeRanges for partial updates. Use With*() to set fields.</summary>
    public static VisibleTimeRanges UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static VisibleTimeRanges ClearFields() => new();

    private VisibleTimeRanges() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Ranges);
        return batches;
    }
}
