// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// A visualizer instruction for an entity.
/// </summary>
public sealed partial class VisualizerInstruction : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.VisualizerInstruction";

    public ComponentBatch VisualizerType { get; private set; }
    public ComponentBatch? ComponentMap { get; private set; }

    public VisualizerInstruction(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.VisualizerType> visualizer_type)
    {
        VisualizerType = ComponentBatch.FromLoggable(visualizer_type,
            new ComponentDescriptor(ArchetypeName, "VisualizerInstruction:visualizer_type", "rerun.blueprint.components.VisualizerType"));
    }

    public VisualizerInstruction(params global::Rerun.Net.Blueprint.Components.VisualizerType[] visualizer_type) : this(visualizer_type.AsSpan()) { }

    public VisualizerInstruction WithComponentMap(ReadOnlySpan<global::Rerun.Net.Blueprint.Components.VisualizerComponentMapping> component_map)
    {
        ComponentMap = ComponentBatch.FromLoggable(component_map,
            new ComponentDescriptor(ArchetypeName, "VisualizerInstruction:component_map", "rerun.blueprint.components.VisualizerComponentMapping"));
        return this;
    }

    public VisualizerInstruction WithComponentMap(params global::Rerun.Net.Blueprint.Components.VisualizerComponentMapping[] component_map) => WithComponentMap(component_map.AsSpan());

    /// <summary>Create an empty VisualizerInstruction for partial updates. Use With*() to set fields.</summary>
    public static VisualizerInstruction UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static VisualizerInstruction ClearFields() => new();

    private VisualizerInstruction() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(VisualizerType);
        if (ComponentMap != null) batches.Add(ComponentMap);
        return batches;
    }
}
