// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

using Rerun.Net.Components;
using Rerun.Net.Blueprint.Components;

namespace Rerun.Net.Blueprint.Archetypes;

/// <summary>
/// Controls the visual bounds of a 2D view.
/// 
/// Everything within these bounds are guaranteed to be visible.
/// Somethings outside of these bounds may also be visible due to letterboxing.
/// 
/// If no visual bounds are set, it will be determined automatically,
/// based on the bounding-box of the data or other camera information present in the view.
/// </summary>
public sealed partial class VisualBounds2D : IAsComponents
{
    private const string ArchetypeName = "rerun.blueprint.archetypes.VisualBounds2D";

    public ComponentBatch Range { get; private set; }

    public VisualBounds2D(ReadOnlySpan<Components.VisualBounds2D> range)
    {
        Range = ComponentBatch.FromLoggable(range,
            new ComponentDescriptor(ArchetypeName, "VisualBounds2D:range", "rerun.blueprint.components.VisualBounds2D"));
    }

    public VisualBounds2D(params Components.VisualBounds2D[] range) : this(range.AsSpan()) { }

    /// <summary>Create an empty VisualBounds2D for partial updates. Use With*() to set fields.</summary>
    public static VisualBounds2D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static VisualBounds2D ClearFields() => new();

    private VisualBounds2D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Range);
        return batches;
    }
}
