using System.Text;

namespace Rerun.Net.CodeGen.Emitters;

internal abstract class EmitterBase
{
    protected static string ToPascalCase(string snakeCase)
    {
        var sb = new StringBuilder();
        var capitalize = true;
        foreach (var ch in snakeCase)
        {
            if (ch == '_') { capitalize = true; continue; }
            sb.Append(capitalize ? char.ToUpper(ch) : ch);
            capitalize = false;
        }
        return sb.ToString();
    }

    protected static string MapPrimitiveToCSharp(string fbsPrimitive) => fbsPrimitive switch
    {
        "bool" => "bool",
        "byte" or "int8" => "sbyte",
        "ubyte" or "uint8" => "byte",
        "short" or "int16" => "short",
        "ushort" or "uint16" => "ushort",
        "int" or "int32" => "int",
        "uint" or "uint32" => "uint",
        "long" or "int64" => "long",
        "ulong" or "uint64" => "ulong",
        "float" or "float32" => "float",
        "double" or "float64" => "double",
        "string" => "string",
        _ => throw new ArgumentException($"Unknown primitive: {fbsPrimitive}"),
    };

    protected static string MapPrimitiveToArrowBuilder(string fbsPrimitive) => fbsPrimitive switch
    {
        "bool" => "BooleanArray.Builder",
        "byte" or "int8" => "Int8Array.Builder",
        "ubyte" or "uint8" => "UInt8Array.Builder",
        "short" or "int16" => "Int16Array.Builder",
        "ushort" or "uint16" => "UInt16Array.Builder",
        "int" or "int32" => "Int32Array.Builder",
        "uint" or "uint32" => "UInt32Array.Builder",
        "long" or "int64" => "Int64Array.Builder",
        "ulong" or "uint64" => "UInt64Array.Builder",
        "float" or "float32" => "FloatArray.Builder",
        "double" or "float64" => "DoubleArray.Builder",
        _ => throw new ArgumentException($"No Arrow builder for: {fbsPrimitive}"),
    };

    protected static string MapPrimitiveToArrowType(string fbsPrimitive) => fbsPrimitive switch
    {
        "bool" => "BooleanType",
        "byte" or "int8" => "Int8Type",
        "ubyte" or "uint8" => "UInt8Type",
        "short" or "int16" => "Int16Type",
        "ushort" or "uint16" => "UInt16Type",
        "int" or "int32" => "Int32Type",
        "uint" or "uint32" => "UInt32Type",
        "long" or "int64" => "Int64Type",
        "ulong" or "uint64" => "UInt64Type",
        "float" or "float32" => "FloatType",
        "double" or "float64" => "DoubleType",
        _ => throw new ArgumentException($"No Arrow type for: {fbsPrimitive}"),
    };

    protected static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// DO NOT EDIT — generated by Rerun.Net.CodeGen");
        sb.AppendLine("#pragma warning disable CS0542 // member names shall not match enclosing type");
        sb.AppendLine();
    }

    protected static void WriteDocComment(StringBuilder sb, string? doc, string indent = "")
    {
        if (doc == null) return;
        sb.AppendLine($"{indent}/// <summary>");
        foreach (var line in doc.Split('\n'))
            sb.AppendLine($"{indent}/// {line}");
        sb.AppendLine($"{indent}/// </summary>");
    }

    protected static string GetShortName(string fullyQualifiedName)
        => fullyQualifiedName.Split('.').Last();

    /// <summary>Avoid C# error when property name matches enclosing type name.</summary>
    protected static string SafePropName(string propName, string typeName)
        => propName == typeName ? $"{propName}Value" : propName;
}
