// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// The annotation context provides additional information on how to display entities.
/// 
/// Entities can use [components.ClassId]s and [components.KeypointId]s to provide annotations, and
/// the labels and colors will be looked up in the appropriate
/// annotation context. We use the *first* annotation context we find in the
/// path-hierarchy when searching up through the ancestors of a given entity
/// path.
/// 
/// See also [datatypes.ClassDescription].
/// 
/// </summary>
public sealed partial class AnnotationContext : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.AnnotationContext";

    public ComponentBatch Context { get; private set; }

    public AnnotationContext(ReadOnlySpan<Components.AnnotationContext> context)
    {
        Context = ComponentBatch.FromLoggable(context,
            new ComponentDescriptor(ArchetypeName, "AnnotationContext:context", "rerun.components.AnnotationContext"));
    }

    public AnnotationContext(params Components.AnnotationContext[] context) : this(context.AsSpan()) { }

    /// <summary>Create an empty AnnotationContext for partial updates. Use With*() to set fields.</summary>
    public static AnnotationContext UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static AnnotationContext ClearFields() => new();

    private AnnotationContext() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Context);
        return batches;
    }
}
