// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 3D arrows with optional colors, radii, labels, etc.
/// 
/// </summary>
public sealed partial class Arrows3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Arrows3D";

    public ComponentBatch Vectors { get; private set; }
    public ComponentBatch? Origins { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Arrows3D(ReadOnlySpan<Components.Vector3D> vectors)
    {
        Vectors = ComponentBatch.FromLoggable(vectors,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:vectors", "rerun.components.Vector3D"));
    }

    public Arrows3D(params Components.Vector3D[] vectors) : this(vectors.AsSpan()) { }

    public Arrows3D WithOrigins(ReadOnlySpan<Components.Position3D> origins)
    {
        Origins = ComponentBatch.FromLoggable(origins,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:origins", "rerun.components.Position3D"));
        return this;
    }

    public Arrows3D WithOrigins(params Components.Position3D[] origins) => WithOrigins(origins.AsSpan());

    public Arrows3D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:radii", "rerun.components.Radius"));
        return this;
    }

    public Arrows3D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Arrows3D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:colors", "rerun.components.Color"));
        return this;
    }

    public Arrows3D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Arrows3D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:labels", "rerun.components.Text"));
        return this;
    }

    public Arrows3D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Arrows3D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Arrows3D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Arrows3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Arrows3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Arrows3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Arrows3D for partial updates. Use With*() to set fields.</summary>
    public static Arrows3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Arrows3D ClearFields() => new();

    private Arrows3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(7);
        batches.Add(Vectors);
        if (Origins != null) batches.Add(Origins);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
