// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 2D arrows with optional colors, radii, labels, etc.
/// 
/// </summary>
public sealed partial class Arrows2D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Arrows2D";

    public ComponentBatch Vectors { get; private set; }
    public ComponentBatch? Origins { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Arrows2D(ReadOnlySpan<Components.Vector2D> vectors)
    {
        Vectors = ComponentBatch.FromLoggable(vectors,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:vectors", "rerun.components.Vector2D"));
    }

    public Arrows2D(params Components.Vector2D[] vectors) : this(vectors.AsSpan()) { }

    public Arrows2D WithOrigins(ReadOnlySpan<Components.Position2D> origins)
    {
        Origins = ComponentBatch.FromLoggable(origins,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:origins", "rerun.components.Position2D"));
        return this;
    }

    public Arrows2D WithOrigins(params Components.Position2D[] origins) => WithOrigins(origins.AsSpan());

    public Arrows2D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:radii", "rerun.components.Radius"));
        return this;
    }

    public Arrows2D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Arrows2D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:colors", "rerun.components.Color"));
        return this;
    }

    public Arrows2D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Arrows2D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:labels", "rerun.components.Text"));
        return this;
    }

    public Arrows2D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Arrows2D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Arrows2D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Arrows2D WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public Arrows2D WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public Arrows2D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Arrows2D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Arrows2D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Arrows2D for partial updates. Use With*() to set fields.</summary>
    public static Arrows2D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Arrows2D ClearFields() => new();

    private Arrows2D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(Vectors);
        if (Origins != null) batches.Add(Origins);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
