// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 
/// See <https://rerun.io/docs/reference/video> for codec support and more general information.
/// 
/// In order to display a video, you also need to log a [archetypes.VideoFrameReference] for each frame.
/// 
/// </summary>
public sealed partial class AssetVideo : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.AssetVideo";

    public ComponentBatch Blob { get; private set; }
    public ComponentBatch? MediaType { get; private set; }

    public AssetVideo(ReadOnlySpan<Components.Blob> blob)
    {
        Blob = ComponentBatch.FromLoggable(blob,
            new ComponentDescriptor(ArchetypeName, "AssetVideo:blob", "rerun.components.Blob"));
    }

    public AssetVideo(params Components.Blob[] blob) : this(blob.AsSpan()) { }

    public AssetVideo WithMediaType(ReadOnlySpan<Components.MediaType> media_type)
    {
        MediaType = ComponentBatch.FromLoggable(media_type,
            new ComponentDescriptor(ArchetypeName, "AssetVideo:media_type", "rerun.components.MediaType"));
        return this;
    }

    public AssetVideo WithMediaType(params Components.MediaType[] media_type) => WithMediaType(media_type.AsSpan());

    /// <summary>Create an empty AssetVideo for partial updates. Use With*() to set fields.</summary>
    public static AssetVideo UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static AssetVideo ClearFields() => new();

    private AssetVideo() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(Blob);
        if (MediaType != null) batches.Add(MediaType);
        return batches;
    }
}
