// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A prepacked 3D asset (`.gltf`, `.glb`, `.obj`, `.stl`, etc.).
/// 
/// See also [archetypes.Mesh3D].
/// 
/// If there are multiple [archetypes.InstancePoses3D] instances logged to the same entity as a mesh,
/// an instance of the mesh will be drawn for each transform.
/// 
/// </summary>
public sealed partial class Asset3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Asset3D";

    public ComponentBatch Blob { get; private set; }
    public ComponentBatch? MediaType { get; private set; }
    public ComponentBatch? AlbedoFactor { get; private set; }

    public Asset3D(ReadOnlySpan<Components.Blob> blob)
    {
        Blob = ComponentBatch.FromLoggable(blob,
            new ComponentDescriptor(ArchetypeName, "Asset3D:blob", "rerun.components.Blob"));
    }

    public Asset3D(params Components.Blob[] blob) : this(blob.AsSpan()) { }

    public Asset3D WithMediaType(ReadOnlySpan<Components.MediaType> media_type)
    {
        MediaType = ComponentBatch.FromLoggable(media_type,
            new ComponentDescriptor(ArchetypeName, "Asset3D:media_type", "rerun.components.MediaType"));
        return this;
    }

    public Asset3D WithMediaType(params Components.MediaType[] media_type) => WithMediaType(media_type.AsSpan());

    public Asset3D WithAlbedoFactor(ReadOnlySpan<Components.AlbedoFactor> albedo_factor)
    {
        AlbedoFactor = ComponentBatch.FromLoggable(albedo_factor,
            new ComponentDescriptor(ArchetypeName, "Asset3D:albedo_factor", "rerun.components.AlbedoFactor"));
        return this;
    }

    public Asset3D WithAlbedoFactor(params Components.AlbedoFactor[] albedo_factor) => WithAlbedoFactor(albedo_factor.AsSpan());

    /// <summary>Create an empty Asset3D for partial updates. Use With*() to set fields.</summary>
    public static Asset3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Asset3D ClearFields() => new();

    private Asset3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        batches.Add(Blob);
        if (MediaType != null) batches.Add(MediaType);
        if (AlbedoFactor != null) batches.Add(AlbedoFactor);
        return batches;
    }
}
