// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A bar chart.
/// 
/// The bar heights will be the provided values, and the x coordinates of the bars will be the provided abscissa or default to the index of the provided values.
/// 
/// </summary>
public sealed partial class BarChart : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.BarChart";

    public ComponentBatch Values { get; private set; }
    public ComponentBatch? Color { get; private set; }
    public ComponentBatch? Abscissa { get; private set; }
    public ComponentBatch? Widths { get; private set; }

    public BarChart(ReadOnlySpan<Components.TensorData> values)
    {
        Values = ComponentBatch.FromLoggable(values,
            new ComponentDescriptor(ArchetypeName, "BarChart:values", "rerun.components.TensorData"));
    }

    public BarChart(params Components.TensorData[] values) : this(values.AsSpan()) { }

    public BarChart WithColor(ReadOnlySpan<Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "BarChart:color", "rerun.components.Color"));
        return this;
    }

    public BarChart WithColor(params Components.Color[] color) => WithColor(color.AsSpan());

    public BarChart WithAbscissa(ReadOnlySpan<Components.TensorData> abscissa)
    {
        Abscissa = ComponentBatch.FromLoggable(abscissa,
            new ComponentDescriptor(ArchetypeName, "BarChart:abscissa", "rerun.components.TensorData"));
        return this;
    }

    public BarChart WithAbscissa(params Components.TensorData[] abscissa) => WithAbscissa(abscissa.AsSpan());

    public BarChart WithWidths(ReadOnlySpan<Components.Length> widths)
    {
        Widths = ComponentBatch.FromLoggable(widths,
            new ComponentDescriptor(ArchetypeName, "BarChart:widths", "rerun.components.Length"));
        return this;
    }

    public BarChart WithWidths(params Components.Length[] widths) => WithWidths(widths.AsSpan());

    /// <summary>Create an empty BarChart for partial updates. Use With*() to set fields.</summary>
    public static BarChart UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static BarChart ClearFields() => new();

    private BarChart() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Values);
        if (Color != null) batches.Add(Color);
        if (Abscissa != null) batches.Add(Abscissa);
        if (Widths != null) batches.Add(Widths);
        return batches;
    }
}
