// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 2D boxes with half-extents and optional center, colors etc.
/// 
/// </summary>
public sealed partial class Boxes2D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Boxes2D";

    public ComponentBatch HalfSizes { get; private set; }
    public ComponentBatch? Centers { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Boxes2D(ReadOnlySpan<Components.HalfSize2D> half_sizes)
    {
        HalfSizes = ComponentBatch.FromLoggable(half_sizes,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:half_sizes", "rerun.components.HalfSize2D"));
    }

    public Boxes2D(params Components.HalfSize2D[] half_sizes) : this(half_sizes.AsSpan()) { }

    public Boxes2D WithCenters(ReadOnlySpan<Components.Position2D> centers)
    {
        Centers = ComponentBatch.FromLoggable(centers,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:centers", "rerun.components.Position2D"));
        return this;
    }

    public Boxes2D WithCenters(params Components.Position2D[] centers) => WithCenters(centers.AsSpan());

    public Boxes2D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:colors", "rerun.components.Color"));
        return this;
    }

    public Boxes2D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Boxes2D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:radii", "rerun.components.Radius"));
        return this;
    }

    public Boxes2D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Boxes2D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:labels", "rerun.components.Text"));
        return this;
    }

    public Boxes2D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Boxes2D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Boxes2D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Boxes2D WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public Boxes2D WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public Boxes2D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Boxes2D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Boxes2D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Boxes2D for partial updates. Use With*() to set fields.</summary>
    public static Boxes2D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Boxes2D ClearFields() => new();

    private Boxes2D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(HalfSizes);
        if (Centers != null) batches.Add(Centers);
        if (Colors != null) batches.Add(Colors);
        if (Radii != null) batches.Add(Radii);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
