// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 3D boxes with half-extents and optional center, rotations, colors etc.
/// 
/// If there's more instance poses than half sizes, the last box's orientation will be repeated for the remaining poses.
/// Orienting and placing boxes forms a separate transform that is applied prior to [archetypes.InstancePoses3D] and [archetypes.Transform3D].
/// 
/// </summary>
public sealed partial class Boxes3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Boxes3D";

    public ComponentBatch HalfSizes { get; private set; }
    public ComponentBatch? Centers { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? RotationAxisAngles { get; private set; }
    public ComponentBatch? Quaternions { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? FillMode { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Boxes3D(ReadOnlySpan<Components.HalfSize3D> half_sizes)
    {
        HalfSizes = ComponentBatch.FromLoggable(half_sizes,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:half_sizes", "rerun.components.HalfSize3D"));
    }

    public Boxes3D(params Components.HalfSize3D[] half_sizes) : this(half_sizes.AsSpan()) { }

    public Boxes3D WithCenters(ReadOnlySpan<Components.Translation3D> centers)
    {
        Centers = ComponentBatch.FromLoggable(centers,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:centers", "rerun.components.Translation3D"));
        return this;
    }

    public Boxes3D WithCenters(params Components.Translation3D[] centers) => WithCenters(centers.AsSpan());

    public Boxes3D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:colors", "rerun.components.Color"));
        return this;
    }

    public Boxes3D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Boxes3D WithRotationAxisAngles(ReadOnlySpan<Components.RotationAxisAngle> rotation_axis_angles)
    {
        RotationAxisAngles = ComponentBatch.FromLoggable(rotation_axis_angles,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:rotation_axis_angles", "rerun.components.RotationAxisAngle"));
        return this;
    }

    public Boxes3D WithRotationAxisAngles(params Components.RotationAxisAngle[] rotation_axis_angles) => WithRotationAxisAngles(rotation_axis_angles.AsSpan());

    public Boxes3D WithQuaternions(ReadOnlySpan<Components.RotationQuat> quaternions)
    {
        Quaternions = ComponentBatch.FromLoggable(quaternions,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:quaternions", "rerun.components.RotationQuat"));
        return this;
    }

    public Boxes3D WithQuaternions(params Components.RotationQuat[] quaternions) => WithQuaternions(quaternions.AsSpan());

    public Boxes3D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:radii", "rerun.components.Radius"));
        return this;
    }

    public Boxes3D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Boxes3D WithFillMode(ReadOnlySpan<Components.FillMode> fill_mode)
    {
        FillMode = ComponentBatch.FromLoggable(fill_mode,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:fill_mode", "rerun.components.FillMode"));
        return this;
    }

    public Boxes3D WithFillMode(params Components.FillMode[] fill_mode) => WithFillMode(fill_mode.AsSpan());

    public Boxes3D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:labels", "rerun.components.Text"));
        return this;
    }

    public Boxes3D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Boxes3D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Boxes3D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Boxes3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Boxes3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Boxes3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Boxes3D for partial updates. Use With*() to set fields.</summary>
    public static Boxes3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Boxes3D ClearFields() => new();

    private Boxes3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(10);
        batches.Add(HalfSizes);
        if (Centers != null) batches.Add(Centers);
        if (Colors != null) batches.Add(Colors);
        if (RotationAxisAngles != null) batches.Add(RotationAxisAngles);
        if (Quaternions != null) batches.Add(Quaternions);
        if (Radii != null) batches.Add(Radii);
        if (FillMode != null) batches.Add(FillMode);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
