// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 3D capsules; cylinders with hemispherical caps.
/// 
/// Capsules are defined by two endpoints (the centers of their end cap spheres), which are located
/// at (0, 0, 0) and (0, 0, length), that is, extending along the positive direction of the Z axis.
/// Capsules in other orientations may be produced by applying a rotation to the entity or
/// instances.
/// 
/// If there's more instance poses than lengths & radii, the last capsule's orientation will be repeated for the remaining poses.
/// Orienting and placing capsules forms a separate transform that is applied prior to [archetypes.InstancePoses3D] and [archetypes.Transform3D].
/// 
/// </summary>
public sealed partial class Capsules3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Capsules3D";

    public ComponentBatch Lengths { get; private set; }
    public ComponentBatch Radii { get; private set; }
    public ComponentBatch? Translations { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? RotationAxisAngles { get; private set; }
    public ComponentBatch? Quaternions { get; private set; }
    public ComponentBatch? LineRadii { get; private set; }
    public ComponentBatch? FillMode { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Capsules3D(ReadOnlySpan<Components.Length> lengths, ReadOnlySpan<Components.Radius> radii)
    {
        Lengths = ComponentBatch.FromLoggable(lengths,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:lengths", "rerun.components.Length"));
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:radii", "rerun.components.Radius"));
    }

    public Capsules3D(Components.Length[] lengths, Components.Radius[] radii) : this(lengths.AsSpan(), radii.AsSpan()) { }

    public Capsules3D WithTranslations(ReadOnlySpan<Components.Translation3D> translations)
    {
        Translations = ComponentBatch.FromLoggable(translations,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:translations", "rerun.components.Translation3D"));
        return this;
    }

    public Capsules3D WithTranslations(params Components.Translation3D[] translations) => WithTranslations(translations.AsSpan());

    public Capsules3D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:colors", "rerun.components.Color"));
        return this;
    }

    public Capsules3D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Capsules3D WithRotationAxisAngles(ReadOnlySpan<Components.RotationAxisAngle> rotation_axis_angles)
    {
        RotationAxisAngles = ComponentBatch.FromLoggable(rotation_axis_angles,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:rotation_axis_angles", "rerun.components.RotationAxisAngle"));
        return this;
    }

    public Capsules3D WithRotationAxisAngles(params Components.RotationAxisAngle[] rotation_axis_angles) => WithRotationAxisAngles(rotation_axis_angles.AsSpan());

    public Capsules3D WithQuaternions(ReadOnlySpan<Components.RotationQuat> quaternions)
    {
        Quaternions = ComponentBatch.FromLoggable(quaternions,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:quaternions", "rerun.components.RotationQuat"));
        return this;
    }

    public Capsules3D WithQuaternions(params Components.RotationQuat[] quaternions) => WithQuaternions(quaternions.AsSpan());

    public Capsules3D WithLineRadii(ReadOnlySpan<Components.Radius> line_radii)
    {
        LineRadii = ComponentBatch.FromLoggable(line_radii,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:line_radii", "rerun.components.Radius"));
        return this;
    }

    public Capsules3D WithLineRadii(params Components.Radius[] line_radii) => WithLineRadii(line_radii.AsSpan());

    public Capsules3D WithFillMode(ReadOnlySpan<Components.FillMode> fill_mode)
    {
        FillMode = ComponentBatch.FromLoggable(fill_mode,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:fill_mode", "rerun.components.FillMode"));
        return this;
    }

    public Capsules3D WithFillMode(params Components.FillMode[] fill_mode) => WithFillMode(fill_mode.AsSpan());

    public Capsules3D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:labels", "rerun.components.Text"));
        return this;
    }

    public Capsules3D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Capsules3D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Capsules3D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Capsules3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Capsules3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Capsules3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Capsules3D for partial updates. Use With*() to set fields.</summary>
    public static Capsules3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Capsules3D ClearFields() => new();

    private Capsules3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(11);
        batches.Add(Lengths);
        batches.Add(Radii);
        if (Translations != null) batches.Add(Translations);
        if (Colors != null) batches.Add(Colors);
        if (RotationAxisAngles != null) batches.Add(RotationAxisAngles);
        if (Quaternions != null) batches.Add(Quaternions);
        if (LineRadii != null) batches.Add(LineRadii);
        if (FillMode != null) batches.Add(FillMode);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
