// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Empties all the components of an entity.
/// 
/// The presence of a clear means that a latest-at query of components at a given path(s)
/// will not return any components that were logged at those paths before the clear.
/// Any logged components after the clear are unaffected by the clear.
/// 
/// This implies that a range query that includes time points that are before the clear,
/// still returns all components at the given path(s).
/// Meaning that in practice clears are ineffective when making use of visible time ranges.
/// Scalar plots are an exception: they track clears and use them to represent holes in the
/// data (i.e. discontinuous lines).
/// 
/// </summary>
public sealed partial class Clear : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Clear";

    public ComponentBatch IsRecursive { get; private set; }

    public Clear(ReadOnlySpan<Components.ClearIsRecursive> is_recursive)
    {
        IsRecursive = ComponentBatch.FromLoggable(is_recursive,
            new ComponentDescriptor(ArchetypeName, "Clear:is_recursive", "rerun.components.ClearIsRecursive"));
    }

    public Clear(params Components.ClearIsRecursive[] is_recursive) : this(is_recursive.AsSpan()) { }

    /// <summary>Create an empty Clear for partial updates. Use With*() to set fields.</summary>
    public static Clear UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Clear ClearFields() => new();

    private Clear() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(IsRecursive);
        return batches;
    }
}
