// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Specifies the coordinate frame for an entity.
/// 
/// If not specified, the coordinate frame uses an implicit frame derived from the entity path.
/// The implicit frame's name is `tf#/your/entity/path` and has an identity transform connection to its parent path.
/// 
/// To learn more about transforms see [Spaces & Transforms](https://rerun.io/docs/concepts/spaces-and-transforms) in the reference.
/// 
/// </summary>
public sealed partial class CoordinateFrame : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.CoordinateFrame";

    public ComponentBatch Frame { get; private set; }

    public CoordinateFrame(ReadOnlySpan<Components.TransformFrameId> frame)
    {
        Frame = ComponentBatch.FromLoggable(frame,
            new ComponentDescriptor(ArchetypeName, "CoordinateFrame:frame", "rerun.components.TransformFrameId"));
    }

    public CoordinateFrame(params Components.TransformFrameId[] frame) : this(frame.AsSpan()) { }

    /// <summary>Create an empty CoordinateFrame for partial updates. Use With*() to set fields.</summary>
    public static CoordinateFrame UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static CoordinateFrame ClearFields() => new();

    private CoordinateFrame() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Frame);
        return batches;
    }
}
