// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A depth image, i.e. as captured by a depth camera.
/// 
/// Each pixel corresponds to a depth value in units specified by [components.DepthMeter].
/// 
/// 
/// </summary>
public sealed partial class DepthImage : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.DepthImage";

    public ComponentBatch Buffer { get; private set; }
    public ComponentBatch Format { get; private set; }
    public ComponentBatch? Meter { get; private set; }
    public ComponentBatch? Colormap { get; private set; }
    public ComponentBatch? DepthRange { get; private set; }
    public ComponentBatch? PointFillRatio { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? MagnificationFilter { get; private set; }

    public DepthImage(ReadOnlySpan<Components.ImageBuffer> buffer, ReadOnlySpan<Components.ImageFormat> format)
    {
        Buffer = ComponentBatch.FromLoggable(buffer,
            new ComponentDescriptor(ArchetypeName, "DepthImage:buffer", "rerun.components.ImageBuffer"));
        Format = ComponentBatch.FromLoggable(format,
            new ComponentDescriptor(ArchetypeName, "DepthImage:format", "rerun.components.ImageFormat"));
    }

    public DepthImage(Components.ImageBuffer[] buffer, Components.ImageFormat[] format) : this(buffer.AsSpan(), format.AsSpan()) { }

    public DepthImage WithMeter(ReadOnlySpan<Components.DepthMeter> meter)
    {
        Meter = ComponentBatch.FromLoggable(meter,
            new ComponentDescriptor(ArchetypeName, "DepthImage:meter", "rerun.components.DepthMeter"));
        return this;
    }

    public DepthImage WithMeter(params Components.DepthMeter[] meter) => WithMeter(meter.AsSpan());

    public DepthImage WithColormap(ReadOnlySpan<Components.Colormap> colormap)
    {
        Colormap = ComponentBatch.FromLoggable(colormap,
            new ComponentDescriptor(ArchetypeName, "DepthImage:colormap", "rerun.components.Colormap"));
        return this;
    }

    public DepthImage WithColormap(params Components.Colormap[] colormap) => WithColormap(colormap.AsSpan());

    public DepthImage WithDepthRange(ReadOnlySpan<Components.ValueRange> depth_range)
    {
        DepthRange = ComponentBatch.FromLoggable(depth_range,
            new ComponentDescriptor(ArchetypeName, "DepthImage:depth_range", "rerun.components.ValueRange"));
        return this;
    }

    public DepthImage WithDepthRange(params Components.ValueRange[] depth_range) => WithDepthRange(depth_range.AsSpan());

    public DepthImage WithPointFillRatio(ReadOnlySpan<Components.FillRatio> point_fill_ratio)
    {
        PointFillRatio = ComponentBatch.FromLoggable(point_fill_ratio,
            new ComponentDescriptor(ArchetypeName, "DepthImage:point_fill_ratio", "rerun.components.FillRatio"));
        return this;
    }

    public DepthImage WithPointFillRatio(params Components.FillRatio[] point_fill_ratio) => WithPointFillRatio(point_fill_ratio.AsSpan());

    public DepthImage WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "DepthImage:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public DepthImage WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public DepthImage WithMagnificationFilter(ReadOnlySpan<Components.MagnificationFilter> magnification_filter)
    {
        MagnificationFilter = ComponentBatch.FromLoggable(magnification_filter,
            new ComponentDescriptor(ArchetypeName, "DepthImage:magnification_filter", "rerun.components.MagnificationFilter"));
        return this;
    }

    public DepthImage WithMagnificationFilter(params Components.MagnificationFilter[] magnification_filter) => WithMagnificationFilter(magnification_filter.AsSpan());

    /// <summary>Create an empty DepthImage for partial updates. Use With*() to set fields.</summary>
    public static DepthImage UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static DepthImage ClearFields() => new();

    private DepthImage() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(Buffer);
        batches.Add(Format);
        if (Meter != null) batches.Add(Meter);
        if (Colormap != null) batches.Add(Colormap);
        if (DepthRange != null) batches.Add(DepthRange);
        if (PointFillRatio != null) batches.Add(PointFillRatio);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (MagnificationFilter != null) batches.Add(MagnificationFilter);
        return batches;
    }
}
