// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A depth image encoded with a codec (e.g. RVL or PNG).
/// 
/// Rerun also supports uncompressed depth images with the [`archetypes.DepthImage`](https://rerun.io/docs/reference/types/archetypes/depth_image).
/// 
/// </summary>
public sealed partial class EncodedDepthImage : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.EncodedDepthImage";

    public ComponentBatch Blob { get; private set; }
    public ComponentBatch? MediaType { get; private set; }
    public ComponentBatch? Meter { get; private set; }
    public ComponentBatch? Colormap { get; private set; }
    public ComponentBatch? DepthRange { get; private set; }
    public ComponentBatch? PointFillRatio { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? MagnificationFilter { get; private set; }

    public EncodedDepthImage(ReadOnlySpan<Components.Blob> blob)
    {
        Blob = ComponentBatch.FromLoggable(blob,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:blob", "rerun.components.Blob"));
    }

    public EncodedDepthImage(params Components.Blob[] blob) : this(blob.AsSpan()) { }

    public EncodedDepthImage WithMediaType(ReadOnlySpan<Components.MediaType> media_type)
    {
        MediaType = ComponentBatch.FromLoggable(media_type,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:media_type", "rerun.components.MediaType"));
        return this;
    }

    public EncodedDepthImage WithMediaType(params Components.MediaType[] media_type) => WithMediaType(media_type.AsSpan());

    public EncodedDepthImage WithMeter(ReadOnlySpan<Components.DepthMeter> meter)
    {
        Meter = ComponentBatch.FromLoggable(meter,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:meter", "rerun.components.DepthMeter"));
        return this;
    }

    public EncodedDepthImage WithMeter(params Components.DepthMeter[] meter) => WithMeter(meter.AsSpan());

    public EncodedDepthImage WithColormap(ReadOnlySpan<Components.Colormap> colormap)
    {
        Colormap = ComponentBatch.FromLoggable(colormap,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:colormap", "rerun.components.Colormap"));
        return this;
    }

    public EncodedDepthImage WithColormap(params Components.Colormap[] colormap) => WithColormap(colormap.AsSpan());

    public EncodedDepthImage WithDepthRange(ReadOnlySpan<Components.ValueRange> depth_range)
    {
        DepthRange = ComponentBatch.FromLoggable(depth_range,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:depth_range", "rerun.components.ValueRange"));
        return this;
    }

    public EncodedDepthImage WithDepthRange(params Components.ValueRange[] depth_range) => WithDepthRange(depth_range.AsSpan());

    public EncodedDepthImage WithPointFillRatio(ReadOnlySpan<Components.FillRatio> point_fill_ratio)
    {
        PointFillRatio = ComponentBatch.FromLoggable(point_fill_ratio,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:point_fill_ratio", "rerun.components.FillRatio"));
        return this;
    }

    public EncodedDepthImage WithPointFillRatio(params Components.FillRatio[] point_fill_ratio) => WithPointFillRatio(point_fill_ratio.AsSpan());

    public EncodedDepthImage WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public EncodedDepthImage WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public EncodedDepthImage WithMagnificationFilter(ReadOnlySpan<Components.MagnificationFilter> magnification_filter)
    {
        MagnificationFilter = ComponentBatch.FromLoggable(magnification_filter,
            new ComponentDescriptor(ArchetypeName, "EncodedDepthImage:magnification_filter", "rerun.components.MagnificationFilter"));
        return this;
    }

    public EncodedDepthImage WithMagnificationFilter(params Components.MagnificationFilter[] magnification_filter) => WithMagnificationFilter(magnification_filter.AsSpan());

    /// <summary>Create an empty EncodedDepthImage for partial updates. Use With*() to set fields.</summary>
    public static EncodedDepthImage UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static EncodedDepthImage ClearFields() => new();

    private EncodedDepthImage() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(Blob);
        if (MediaType != null) batches.Add(MediaType);
        if (Meter != null) batches.Add(Meter);
        if (Colormap != null) batches.Add(Colormap);
        if (DepthRange != null) batches.Add(DepthRange);
        if (PointFillRatio != null) batches.Add(PointFillRatio);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (MagnificationFilter != null) batches.Add(MagnificationFilter);
        return batches;
    }
}
