// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// An image encoded as e.g. a JPEG or PNG.
/// 
/// Rerun also supports uncompressed images with the [archetypes.Image].
/// For images that refer to video frames see [archetypes.VideoFrameReference].
/// 
/// 
/// </summary>
public sealed partial class EncodedImage : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.EncodedImage";

    public ComponentBatch Blob { get; private set; }
    public ComponentBatch? MediaType { get; private set; }
    public ComponentBatch? Opacity { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? MagnificationFilter { get; private set; }

    public EncodedImage(ReadOnlySpan<Components.Blob> blob)
    {
        Blob = ComponentBatch.FromLoggable(blob,
            new ComponentDescriptor(ArchetypeName, "EncodedImage:blob", "rerun.components.Blob"));
    }

    public EncodedImage(params Components.Blob[] blob) : this(blob.AsSpan()) { }

    public EncodedImage WithMediaType(ReadOnlySpan<Components.MediaType> media_type)
    {
        MediaType = ComponentBatch.FromLoggable(media_type,
            new ComponentDescriptor(ArchetypeName, "EncodedImage:media_type", "rerun.components.MediaType"));
        return this;
    }

    public EncodedImage WithMediaType(params Components.MediaType[] media_type) => WithMediaType(media_type.AsSpan());

    public EncodedImage WithOpacity(ReadOnlySpan<Components.Opacity> opacity)
    {
        Opacity = ComponentBatch.FromLoggable(opacity,
            new ComponentDescriptor(ArchetypeName, "EncodedImage:opacity", "rerun.components.Opacity"));
        return this;
    }

    public EncodedImage WithOpacity(params Components.Opacity[] opacity) => WithOpacity(opacity.AsSpan());

    public EncodedImage WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "EncodedImage:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public EncodedImage WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public EncodedImage WithMagnificationFilter(ReadOnlySpan<Components.MagnificationFilter> magnification_filter)
    {
        MagnificationFilter = ComponentBatch.FromLoggable(magnification_filter,
            new ComponentDescriptor(ArchetypeName, "EncodedImage:magnification_filter", "rerun.components.MagnificationFilter"));
        return this;
    }

    public EncodedImage WithMagnificationFilter(params Components.MagnificationFilter[] magnification_filter) => WithMagnificationFilter(magnification_filter.AsSpan());

    /// <summary>Create an empty EncodedImage for partial updates. Use With*() to set fields.</summary>
    public static EncodedImage UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static EncodedImage ClearFields() => new();

    private EncodedImage() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        batches.Add(Blob);
        if (MediaType != null) batches.Add(MediaType);
        if (Opacity != null) batches.Add(Opacity);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (MagnificationFilter != null) batches.Add(MagnificationFilter);
        return batches;
    }
}
