// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Geospatial line strings with positions expressed in [EPSG:4326](https://epsg.io/4326) latitude and longitude (North/East-positive degrees), and optional colors and radii.
/// 
/// Also known as "line strips" or "polylines".
/// 
/// </summary>
public sealed partial class GeoLineStrings : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.GeoLineStrings";

    public ComponentBatch LineStrings { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }

    public GeoLineStrings(ReadOnlySpan<Components.GeoLineString> line_strings)
    {
        LineStrings = ComponentBatch.FromLoggable(line_strings,
            new ComponentDescriptor(ArchetypeName, "GeoLineStrings:line_strings", "rerun.components.GeoLineString"));
    }

    public GeoLineStrings(params Components.GeoLineString[] line_strings) : this(line_strings.AsSpan()) { }

    public GeoLineStrings WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "GeoLineStrings:radii", "rerun.components.Radius"));
        return this;
    }

    public GeoLineStrings WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public GeoLineStrings WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "GeoLineStrings:colors", "rerun.components.Color"));
        return this;
    }

    public GeoLineStrings WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    /// <summary>Create an empty GeoLineStrings for partial updates. Use With*() to set fields.</summary>
    public static GeoLineStrings UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static GeoLineStrings ClearFields() => new();

    private GeoLineStrings() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        batches.Add(LineStrings);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        return batches;
    }
}
