// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Geospatial points with positions expressed in [EPSG:4326](https://epsg.io/4326) latitude and longitude (North/East-positive degrees), and optional colors and radii.
/// 
/// </summary>
public sealed partial class GeoPoints : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.GeoPoints";

    public ComponentBatch Positions { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public GeoPoints(ReadOnlySpan<Components.LatLon> positions)
    {
        Positions = ComponentBatch.FromLoggable(positions,
            new ComponentDescriptor(ArchetypeName, "GeoPoints:positions", "rerun.components.LatLon"));
    }

    public GeoPoints(params Components.LatLon[] positions) : this(positions.AsSpan()) { }

    public GeoPoints WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "GeoPoints:radii", "rerun.components.Radius"));
        return this;
    }

    public GeoPoints WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public GeoPoints WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "GeoPoints:colors", "rerun.components.Color"));
        return this;
    }

    public GeoPoints WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public GeoPoints WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "GeoPoints:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public GeoPoints WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty GeoPoints for partial updates. Use With*() to set fields.</summary>
    public static GeoPoints UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static GeoPoints ClearFields() => new();

    private GeoPoints() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Positions);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
