// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A list of nodes in a graph with optional labels, colors, etc.
/// 
/// </summary>
public sealed partial class GraphNodes : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.GraphNodes";

    public ComponentBatch NodeIds { get; private set; }
    public ComponentBatch? Positions { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? Radii { get; private set; }

    public GraphNodes(ReadOnlySpan<Components.GraphNode> node_ids)
    {
        NodeIds = ComponentBatch.FromLoggable(node_ids,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:node_ids", "rerun.components.GraphNode"));
    }

    public GraphNodes(params Components.GraphNode[] node_ids) : this(node_ids.AsSpan()) { }

    public GraphNodes WithPositions(ReadOnlySpan<Components.Position2D> positions)
    {
        Positions = ComponentBatch.FromLoggable(positions,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:positions", "rerun.components.Position2D"));
        return this;
    }

    public GraphNodes WithPositions(params Components.Position2D[] positions) => WithPositions(positions.AsSpan());

    public GraphNodes WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:colors", "rerun.components.Color"));
        return this;
    }

    public GraphNodes WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public GraphNodes WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:labels", "rerun.components.Text"));
        return this;
    }

    public GraphNodes WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public GraphNodes WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public GraphNodes WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public GraphNodes WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "GraphNodes:radii", "rerun.components.Radius"));
        return this;
    }

    public GraphNodes WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    /// <summary>Create an empty GraphNodes for partial updates. Use With*() to set fields.</summary>
    public static GraphNodes UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static GraphNodes ClearFields() => new();

    private GraphNodes() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(6);
        batches.Add(NodeIds);
        if (Positions != null) batches.Add(Positions);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (Radii != null) batches.Add(Radii);
        return batches;
    }
}
