// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A list of edges in a graph.
/// 
/// By default, edges are undirected.
/// 
/// </summary>
public sealed partial class GraphEdges : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.GraphEdges";

    public ComponentBatch Edges { get; private set; }
    public ComponentBatch? GraphType { get; private set; }

    public GraphEdges(ReadOnlySpan<Components.GraphEdge> edges)
    {
        Edges = ComponentBatch.FromLoggable(edges,
            new ComponentDescriptor(ArchetypeName, "GraphEdges:edges", "rerun.components.GraphEdge"));
    }

    public GraphEdges(params Components.GraphEdge[] edges) : this(edges.AsSpan()) { }

    public GraphEdges WithGraphType(ReadOnlySpan<Components.GraphType> graph_type)
    {
        GraphType = ComponentBatch.FromLoggable(graph_type,
            new ComponentDescriptor(ArchetypeName, "GraphEdges:graph_type", "rerun.components.GraphType"));
        return this;
    }

    public GraphEdges WithGraphType(params Components.GraphType[] graph_type) => WithGraphType(graph_type.AsSpan());

    /// <summary>Create an empty GraphEdges for partial updates. Use With*() to set fields.</summary>
    public static GraphEdges UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static GraphEdges ClearFields() => new();

    private GraphEdges() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(Edges);
        if (GraphType != null) batches.Add(GraphType);
        return batches;
    }
}
