// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A monochrome or color image.
/// 
/// See also [archetypes.DepthImage] and [archetypes.SegmentationImage].
/// 
/// Rerun also supports compressed images (JPEG, PNG, …), using [archetypes.EncodedImage].
/// For images that refer to video frames see [archetypes.VideoFrameReference].
/// Compressing images or using video data instead can save a lot of bandwidth and memory.
/// 
/// The raw image data is stored as a single buffer of bytes in a [components.Blob].
/// The meaning of these bytes is determined by the [components.ImageFormat] which specifies the resolution
/// and the pixel format (e.g. RGB, RGBA, …).
/// 
/// The order of dimensions in the underlying [components.Blob] follows the typical
/// row-major, interleaved-pixel image format.
/// 
/// 
/// </summary>
public sealed partial class Image : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Image";

    public ComponentBatch Buffer { get; private set; }
    public ComponentBatch Format { get; private set; }
    public ComponentBatch? Opacity { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? MagnificationFilter { get; private set; }

    public Image(ReadOnlySpan<Components.ImageBuffer> buffer, ReadOnlySpan<Components.ImageFormat> format)
    {
        Buffer = ComponentBatch.FromLoggable(buffer,
            new ComponentDescriptor(ArchetypeName, "Image:buffer", "rerun.components.ImageBuffer"));
        Format = ComponentBatch.FromLoggable(format,
            new ComponentDescriptor(ArchetypeName, "Image:format", "rerun.components.ImageFormat"));
    }

    public Image(Components.ImageBuffer[] buffer, Components.ImageFormat[] format) : this(buffer.AsSpan(), format.AsSpan()) { }

    public Image WithOpacity(ReadOnlySpan<Components.Opacity> opacity)
    {
        Opacity = ComponentBatch.FromLoggable(opacity,
            new ComponentDescriptor(ArchetypeName, "Image:opacity", "rerun.components.Opacity"));
        return this;
    }

    public Image WithOpacity(params Components.Opacity[] opacity) => WithOpacity(opacity.AsSpan());

    public Image WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "Image:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public Image WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public Image WithMagnificationFilter(ReadOnlySpan<Components.MagnificationFilter> magnification_filter)
    {
        MagnificationFilter = ComponentBatch.FromLoggable(magnification_filter,
            new ComponentDescriptor(ArchetypeName, "Image:magnification_filter", "rerun.components.MagnificationFilter"));
        return this;
    }

    public Image WithMagnificationFilter(params Components.MagnificationFilter[] magnification_filter) => WithMagnificationFilter(magnification_filter.AsSpan());

    /// <summary>Create an empty Image for partial updates. Use With*() to set fields.</summary>
    public static Image UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Image ClearFields() => new();

    private Image() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        batches.Add(Buffer);
        batches.Add(Format);
        if (Opacity != null) batches.Add(Opacity);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (MagnificationFilter != null) batches.Add(MagnificationFilter);
        return batches;
    }
}
