// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// One or more transforms applied on the current entity's transform frame.
/// 
/// Unlike [archetypes.Transform3D], it is *not* propagated in the transform hierarchy.
/// If [archetypes.CoordinateFrame] is specified, it acts relative to that coordinate frame,
/// otherwise it is relative to the entity's implicit coordinate frame.
/// 
/// Whenever you log this archetype, the state of the resulting overall pose is fully reset to the new archetype.
/// This means that if you first log a pose with only a translation, and then log one with only a rotation,
/// it will be resolved to a pose with only a rotation.
/// (This is unlike how we usually apply latest-at semantics on an archetype where we take the latest state of any component independently)
/// 
/// From the point of view of the entity's coordinate system,
/// all components are applied in the inverse order they are listed here.
/// E.g. if both a translation and a mat3x3 transform are present,
/// the 3x3 matrix is applied first, followed by the translation.
/// 
/// Currently, many visualizers support only a single instance transform per entity.
/// Check archetype documentations for details - if not otherwise specified, only the first instance transform is applied.
/// Some visualizers like the mesh visualizer used for [archetypes.Mesh3D],
/// will draw an object for every pose, a behavior also known as "instancing".
/// 
/// </summary>
public sealed partial class InstancePoses3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.InstancePoses3D";

    public ComponentBatch? Translations { get; private set; }
    public ComponentBatch? RotationAxisAngles { get; private set; }
    public ComponentBatch? Quaternions { get; private set; }
    public ComponentBatch? Scales { get; private set; }
    public ComponentBatch? Mat3x3 { get; private set; }

    public InstancePoses3D() { }

    public InstancePoses3D WithTranslations(ReadOnlySpan<Components.Translation3D> translations)
    {
        Translations = ComponentBatch.FromLoggable(translations,
            new ComponentDescriptor(ArchetypeName, "InstancePoses3D:translations", "rerun.components.Translation3D"));
        return this;
    }

    public InstancePoses3D WithTranslations(params Components.Translation3D[] translations) => WithTranslations(translations.AsSpan());

    public InstancePoses3D WithRotationAxisAngles(ReadOnlySpan<Components.RotationAxisAngle> rotation_axis_angles)
    {
        RotationAxisAngles = ComponentBatch.FromLoggable(rotation_axis_angles,
            new ComponentDescriptor(ArchetypeName, "InstancePoses3D:rotation_axis_angles", "rerun.components.RotationAxisAngle"));
        return this;
    }

    public InstancePoses3D WithRotationAxisAngles(params Components.RotationAxisAngle[] rotation_axis_angles) => WithRotationAxisAngles(rotation_axis_angles.AsSpan());

    public InstancePoses3D WithQuaternions(ReadOnlySpan<Components.RotationQuat> quaternions)
    {
        Quaternions = ComponentBatch.FromLoggable(quaternions,
            new ComponentDescriptor(ArchetypeName, "InstancePoses3D:quaternions", "rerun.components.RotationQuat"));
        return this;
    }

    public InstancePoses3D WithQuaternions(params Components.RotationQuat[] quaternions) => WithQuaternions(quaternions.AsSpan());

    public InstancePoses3D WithScales(ReadOnlySpan<Components.Scale3D> scales)
    {
        Scales = ComponentBatch.FromLoggable(scales,
            new ComponentDescriptor(ArchetypeName, "InstancePoses3D:scales", "rerun.components.Scale3D"));
        return this;
    }

    public InstancePoses3D WithScales(params Components.Scale3D[] scales) => WithScales(scales.AsSpan());

    public InstancePoses3D WithMat3x3(ReadOnlySpan<Components.TransformMat3x3> mat3x3)
    {
        Mat3x3 = ComponentBatch.FromLoggable(mat3x3,
            new ComponentDescriptor(ArchetypeName, "InstancePoses3D:mat3x3", "rerun.components.TransformMat3x3"));
        return this;
    }

    public InstancePoses3D WithMat3x3(params Components.TransformMat3x3[] mat3x3) => WithMat3x3(mat3x3.AsSpan());

    /// <summary>Create an empty InstancePoses3D for partial updates. Use With*() to set fields.</summary>
    public static InstancePoses3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static InstancePoses3D ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        if (Translations != null) batches.Add(Translations);
        if (RotationAxisAngles != null) batches.Add(RotationAxisAngles);
        if (Quaternions != null) batches.Add(Quaternions);
        if (Scales != null) batches.Add(Scales);
        if (Mat3x3 != null) batches.Add(Mat3x3);
        return batches;
    }
}
