// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 2D line strips with positions and optional colors, radii, labels, etc.
/// 
/// </summary>
public sealed partial class LineStrips2D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.LineStrips2D";

    public ComponentBatch Strips { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public LineStrips2D(ReadOnlySpan<Components.LineStrip2D> strips)
    {
        Strips = ComponentBatch.FromLoggable(strips,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:strips", "rerun.components.LineStrip2D"));
    }

    public LineStrips2D(params Components.LineStrip2D[] strips) : this(strips.AsSpan()) { }

    public LineStrips2D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:radii", "rerun.components.Radius"));
        return this;
    }

    public LineStrips2D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public LineStrips2D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:colors", "rerun.components.Color"));
        return this;
    }

    public LineStrips2D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public LineStrips2D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:labels", "rerun.components.Text"));
        return this;
    }

    public LineStrips2D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public LineStrips2D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public LineStrips2D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public LineStrips2D WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public LineStrips2D WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public LineStrips2D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "LineStrips2D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public LineStrips2D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty LineStrips2D for partial updates. Use With*() to set fields.</summary>
    public static LineStrips2D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static LineStrips2D ClearFields() => new();

    private LineStrips2D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(7);
        batches.Add(Strips);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
