// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// 3D line strips with positions and optional colors, radii, labels, etc.
/// 
/// </summary>
public sealed partial class LineStrips3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.LineStrips3D";

    public ComponentBatch Strips { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public LineStrips3D(ReadOnlySpan<Components.LineStrip3D> strips)
    {
        Strips = ComponentBatch.FromLoggable(strips,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:strips", "rerun.components.LineStrip3D"));
    }

    public LineStrips3D(params Components.LineStrip3D[] strips) : this(strips.AsSpan()) { }

    public LineStrips3D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:radii", "rerun.components.Radius"));
        return this;
    }

    public LineStrips3D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public LineStrips3D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:colors", "rerun.components.Color"));
        return this;
    }

    public LineStrips3D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public LineStrips3D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:labels", "rerun.components.Text"));
        return this;
    }

    public LineStrips3D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public LineStrips3D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public LineStrips3D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public LineStrips3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "LineStrips3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public LineStrips3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty LineStrips3D for partial updates. Use With*() to set fields.</summary>
    public static LineStrips3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static LineStrips3D ClearFields() => new();

    private LineStrips3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(6);
        batches.Add(Strips);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
