// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A schema definition that describes the structure of messages in an MCAP file.
/// 
/// Schemas define the data types and field structures used by messages in MCAP channels.
/// They provide the blueprint for interpreting message payloads, specifying field names,
/// types, and organization. Each schema is referenced by channels to indicate how their
/// messages should be decoded and understood.
/// 
/// See also [archetypes.McapChannel] for channels that reference these schemas,
/// [archetypes.McapMessage] for the messages that conform to these schemas, and the
/// [MCAP specification](https://mcap.dev/) for complete format details.
/// 
/// </summary>
public sealed partial class McapSchema : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.McapSchema";

    public ComponentBatch Id { get; private set; }
    public ComponentBatch Name { get; private set; }
    public ComponentBatch Encoding { get; private set; }
    public ComponentBatch Data { get; private set; }

    public McapSchema(ReadOnlySpan<Components.SchemaId> id, ReadOnlySpan<Components.Text> name, ReadOnlySpan<Components.Text> encoding, ReadOnlySpan<Components.Blob> data)
    {
        Id = ComponentBatch.FromLoggable(id,
            new ComponentDescriptor(ArchetypeName, "McapSchema:id", "rerun.components.SchemaId"));
        Name = ComponentBatch.FromLoggable(name,
            new ComponentDescriptor(ArchetypeName, "McapSchema:name", "rerun.components.Text"));
        Encoding = ComponentBatch.FromLoggable(encoding,
            new ComponentDescriptor(ArchetypeName, "McapSchema:encoding", "rerun.components.Text"));
        Data = ComponentBatch.FromLoggable(data,
            new ComponentDescriptor(ArchetypeName, "McapSchema:data", "rerun.components.Blob"));
    }

    public McapSchema(Components.SchemaId[] id, Components.Text[] name, Components.Text[] encoding, Components.Blob[] data) : this(id.AsSpan(), name.AsSpan(), encoding.AsSpan(), data.AsSpan()) { }

    /// <summary>Create an empty McapSchema for partial updates. Use With*() to set fields.</summary>
    public static McapSchema UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static McapSchema ClearFields() => new();

    private McapSchema() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Id);
        batches.Add(Name);
        batches.Add(Encoding);
        batches.Add(Data);
        return batches;
    }
}
