// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// The binary payload of a single MCAP message, without metadata.
/// 
/// This archetype represents only the raw message data from an MCAP file. It does not include
/// MCAP message metadata such as timestamps, channel IDs, sequence numbers, or publication times.
/// The binary payload represents sensor data, commands, or other information encoded according
/// to the format specified by the associated channel.
/// 
/// See [archetypes.McapChannel] for channel definitions that specify message encoding,
/// [archetypes.McapSchema] for data structure definitions, and the
/// [MCAP specification](https://mcap.dev/) for complete format details.
/// 
/// </summary>
public sealed partial class McapMessage : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.McapMessage";

    public ComponentBatch Data { get; private set; }

    public McapMessage(ReadOnlySpan<Components.Blob> data)
    {
        Data = ComponentBatch.FromLoggable(data,
            new ComponentDescriptor(ArchetypeName, "McapMessage:data", "rerun.components.Blob"));
    }

    public McapMessage(params Components.Blob[] data) : this(data.AsSpan()) { }

    /// <summary>Create an empty McapMessage for partial updates. Use With*() to set fields.</summary>
    public static McapMessage UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static McapMessage ClearFields() => new();

    private McapMessage() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Data);
        return batches;
    }
}
