// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A channel within an MCAP file that defines how messages are structured and encoded.
/// 
/// Channels in MCAP files group messages by topic and define their encoding format.
/// Each channel has a unique identifier and specifies the message schema and encoding used
/// for all messages published to that topic.
/// 
/// See also [archetypes.McapMessage] for individual messages within a channel,
/// [archetypes.McapSchema] for the data structure definitions, and the
/// [MCAP specification](https://mcap.dev/) for complete format details.
/// 
/// </summary>
public sealed partial class McapChannel : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.McapChannel";

    public ComponentBatch Id { get; private set; }
    public ComponentBatch Topic { get; private set; }
    public ComponentBatch MessageEncoding { get; private set; }
    public ComponentBatch? Metadata { get; private set; }

    public McapChannel(ReadOnlySpan<Components.ChannelId> id, ReadOnlySpan<Components.Text> topic, ReadOnlySpan<Components.Text> message_encoding)
    {
        Id = ComponentBatch.FromLoggable(id,
            new ComponentDescriptor(ArchetypeName, "McapChannel:id", "rerun.components.ChannelId"));
        Topic = ComponentBatch.FromLoggable(topic,
            new ComponentDescriptor(ArchetypeName, "McapChannel:topic", "rerun.components.Text"));
        MessageEncoding = ComponentBatch.FromLoggable(message_encoding,
            new ComponentDescriptor(ArchetypeName, "McapChannel:message_encoding", "rerun.components.Text"));
    }

    public McapChannel(Components.ChannelId[] id, Components.Text[] topic, Components.Text[] message_encoding) : this(id.AsSpan(), topic.AsSpan(), message_encoding.AsSpan()) { }

    public McapChannel WithMetadata(ReadOnlySpan<Components.KeyValuePairs> metadata)
    {
        Metadata = ComponentBatch.FromLoggable(metadata,
            new ComponentDescriptor(ArchetypeName, "McapChannel:metadata", "rerun.components.KeyValuePairs"));
        return this;
    }

    public McapChannel WithMetadata(params Components.KeyValuePairs[] metadata) => WithMetadata(metadata.AsSpan());

    /// <summary>Create an empty McapChannel for partial updates. Use With*() to set fields.</summary>
    public static McapChannel UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static McapChannel ClearFields() => new();

    private McapChannel() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Id);
        batches.Add(Topic);
        batches.Add(MessageEncoding);
        if (Metadata != null) batches.Add(Metadata);
        return batches;
    }
}
