// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Recording-level statistics about an MCAP file, logged as a part of [archetypes.RecordingInfo].
/// 
/// This archetype contains summary information about an entire MCAP recording, including
/// counts of messages, schemas, channels, and other records, as well as timing information
/// spanning the full recording duration. It is typically logged once per recording to provide
/// an overview of the dataset's structure and content.
/// 
/// See also [archetypes.McapChannel] for individual channel definitions,
/// [archetypes.McapMessage] for message content, [archetypes.McapSchema] for schema definitions,
/// and the [MCAP specification](https://mcap.dev/) for complete format details.
/// 
/// </summary>
public sealed partial class McapStatistics : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.McapStatistics";

    public ComponentBatch MessageCount { get; private set; }
    public ComponentBatch SchemaCount { get; private set; }
    public ComponentBatch ChannelCount { get; private set; }
    public ComponentBatch AttachmentCount { get; private set; }
    public ComponentBatch MetadataCount { get; private set; }
    public ComponentBatch ChunkCount { get; private set; }
    public ComponentBatch MessageStartTime { get; private set; }
    public ComponentBatch MessageEndTime { get; private set; }
    public ComponentBatch? ChannelMessageCounts { get; private set; }

    public McapStatistics(ReadOnlySpan<Components.Count> message_count, ReadOnlySpan<Components.Count> schema_count, ReadOnlySpan<Components.Count> channel_count, ReadOnlySpan<Components.Count> attachment_count, ReadOnlySpan<Components.Count> metadata_count, ReadOnlySpan<Components.Count> chunk_count, ReadOnlySpan<Components.Timestamp> message_start_time, ReadOnlySpan<Components.Timestamp> message_end_time)
    {
        MessageCount = ComponentBatch.FromLoggable(message_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:message_count", "rerun.components.Count"));
        SchemaCount = ComponentBatch.FromLoggable(schema_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:schema_count", "rerun.components.Count"));
        ChannelCount = ComponentBatch.FromLoggable(channel_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:channel_count", "rerun.components.Count"));
        AttachmentCount = ComponentBatch.FromLoggable(attachment_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:attachment_count", "rerun.components.Count"));
        MetadataCount = ComponentBatch.FromLoggable(metadata_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:metadata_count", "rerun.components.Count"));
        ChunkCount = ComponentBatch.FromLoggable(chunk_count,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:chunk_count", "rerun.components.Count"));
        MessageStartTime = ComponentBatch.FromLoggable(message_start_time,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:message_start_time", "rerun.components.Timestamp"));
        MessageEndTime = ComponentBatch.FromLoggable(message_end_time,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:message_end_time", "rerun.components.Timestamp"));
    }

    public McapStatistics(Components.Count[] message_count, Components.Count[] schema_count, Components.Count[] channel_count, Components.Count[] attachment_count, Components.Count[] metadata_count, Components.Count[] chunk_count, Components.Timestamp[] message_start_time, Components.Timestamp[] message_end_time) : this(message_count.AsSpan(), schema_count.AsSpan(), channel_count.AsSpan(), attachment_count.AsSpan(), metadata_count.AsSpan(), chunk_count.AsSpan(), message_start_time.AsSpan(), message_end_time.AsSpan()) { }

    public McapStatistics WithChannelMessageCounts(ReadOnlySpan<Components.ChannelMessageCounts> channel_message_counts)
    {
        ChannelMessageCounts = ComponentBatch.FromLoggable(channel_message_counts,
            new ComponentDescriptor(ArchetypeName, "McapStatistics:channel_message_counts", "rerun.components.ChannelMessageCounts"));
        return this;
    }

    public McapStatistics WithChannelMessageCounts(params Components.ChannelMessageCounts[] channel_message_counts) => WithChannelMessageCounts(channel_message_counts.AsSpan());

    /// <summary>Create an empty McapStatistics for partial updates. Use With*() to set fields.</summary>
    public static McapStatistics UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static McapStatistics ClearFields() => new();

    private McapStatistics() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(9);
        batches.Add(MessageCount);
        batches.Add(SchemaCount);
        batches.Add(ChannelCount);
        batches.Add(AttachmentCount);
        batches.Add(MetadataCount);
        batches.Add(ChunkCount);
        batches.Add(MessageStartTime);
        batches.Add(MessageEndTime);
        if (ChannelMessageCounts != null) batches.Add(ChannelMessageCounts);
        return batches;
    }
}
