// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A 3D triangle mesh as specified by its per-mesh and per-vertex properties.
/// 
/// See also [archetypes.Asset3D].
/// 
/// If there are multiple [archetypes.InstancePoses3D] instances logged to the same entity as a mesh,
/// an instance of the mesh will be drawn for each transform.
/// 
/// For transparency ordering, as well as back face culling (disabled by default),
/// front faces are assumed to be those with counter clockwise triangle winding order
/// (this is the same as in the GLTF specification).
/// 
/// </summary>
public sealed partial class Mesh3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Mesh3D";

    public ComponentBatch VertexPositions { get; private set; }
    public ComponentBatch? TriangleIndices { get; private set; }
    public ComponentBatch? VertexNormals { get; private set; }
    public ComponentBatch? VertexColors { get; private set; }
    public ComponentBatch? VertexTexcoords { get; private set; }
    public ComponentBatch? AlbedoFactor { get; private set; }
    public ComponentBatch? FaceRendering { get; private set; }
    public ComponentBatch? AlbedoTextureBuffer { get; private set; }
    public ComponentBatch? AlbedoTextureFormat { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }

    public Mesh3D(ReadOnlySpan<Components.Position3D> vertex_positions)
    {
        VertexPositions = ComponentBatch.FromLoggable(vertex_positions,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:vertex_positions", "rerun.components.Position3D"));
    }

    public Mesh3D(params Components.Position3D[] vertex_positions) : this(vertex_positions.AsSpan()) { }

    public Mesh3D WithTriangleIndices(ReadOnlySpan<Components.TriangleIndices> triangle_indices)
    {
        TriangleIndices = ComponentBatch.FromLoggable(triangle_indices,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:triangle_indices", "rerun.components.TriangleIndices"));
        return this;
    }

    public Mesh3D WithTriangleIndices(params Components.TriangleIndices[] triangle_indices) => WithTriangleIndices(triangle_indices.AsSpan());

    public Mesh3D WithVertexNormals(ReadOnlySpan<Components.Vector3D> vertex_normals)
    {
        VertexNormals = ComponentBatch.FromLoggable(vertex_normals,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:vertex_normals", "rerun.components.Vector3D"));
        return this;
    }

    public Mesh3D WithVertexNormals(params Components.Vector3D[] vertex_normals) => WithVertexNormals(vertex_normals.AsSpan());

    public Mesh3D WithVertexColors(ReadOnlySpan<Components.Color> vertex_colors)
    {
        VertexColors = ComponentBatch.FromLoggable(vertex_colors,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:vertex_colors", "rerun.components.Color"));
        return this;
    }

    public Mesh3D WithVertexColors(params Components.Color[] vertex_colors) => WithVertexColors(vertex_colors.AsSpan());

    public Mesh3D WithVertexTexcoords(ReadOnlySpan<Components.Texcoord2D> vertex_texcoords)
    {
        VertexTexcoords = ComponentBatch.FromLoggable(vertex_texcoords,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:vertex_texcoords", "rerun.components.Texcoord2D"));
        return this;
    }

    public Mesh3D WithVertexTexcoords(params Components.Texcoord2D[] vertex_texcoords) => WithVertexTexcoords(vertex_texcoords.AsSpan());

    public Mesh3D WithAlbedoFactor(ReadOnlySpan<Components.AlbedoFactor> albedo_factor)
    {
        AlbedoFactor = ComponentBatch.FromLoggable(albedo_factor,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:albedo_factor", "rerun.components.AlbedoFactor"));
        return this;
    }

    public Mesh3D WithAlbedoFactor(params Components.AlbedoFactor[] albedo_factor) => WithAlbedoFactor(albedo_factor.AsSpan());

    public Mesh3D WithFaceRendering(ReadOnlySpan<Components.MeshFaceRendering> face_rendering)
    {
        FaceRendering = ComponentBatch.FromLoggable(face_rendering,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:face_rendering", "rerun.components.MeshFaceRendering"));
        return this;
    }

    public Mesh3D WithFaceRendering(params Components.MeshFaceRendering[] face_rendering) => WithFaceRendering(face_rendering.AsSpan());

    public Mesh3D WithAlbedoTextureBuffer(ReadOnlySpan<Components.ImageBuffer> albedo_texture_buffer)
    {
        AlbedoTextureBuffer = ComponentBatch.FromLoggable(albedo_texture_buffer,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:albedo_texture_buffer", "rerun.components.ImageBuffer"));
        return this;
    }

    public Mesh3D WithAlbedoTextureBuffer(params Components.ImageBuffer[] albedo_texture_buffer) => WithAlbedoTextureBuffer(albedo_texture_buffer.AsSpan());

    public Mesh3D WithAlbedoTextureFormat(ReadOnlySpan<Components.ImageFormat> albedo_texture_format)
    {
        AlbedoTextureFormat = ComponentBatch.FromLoggable(albedo_texture_format,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:albedo_texture_format", "rerun.components.ImageFormat"));
        return this;
    }

    public Mesh3D WithAlbedoTextureFormat(params Components.ImageFormat[] albedo_texture_format) => WithAlbedoTextureFormat(albedo_texture_format.AsSpan());

    public Mesh3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Mesh3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Mesh3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    /// <summary>Create an empty Mesh3D for partial updates. Use With*() to set fields.</summary>
    public static Mesh3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Mesh3D ClearFields() => new();

    private Mesh3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(10);
        batches.Add(VertexPositions);
        if (TriangleIndices != null) batches.Add(TriangleIndices);
        if (VertexNormals != null) batches.Add(VertexNormals);
        if (VertexColors != null) batches.Add(VertexColors);
        if (VertexTexcoords != null) batches.Add(VertexTexcoords);
        if (AlbedoFactor != null) batches.Add(AlbedoFactor);
        if (FaceRendering != null) batches.Add(FaceRendering);
        if (AlbedoTextureBuffer != null) batches.Add(AlbedoTextureBuffer);
        if (AlbedoTextureFormat != null) batches.Add(AlbedoTextureFormat);
        if (ClassIds != null) batches.Add(ClassIds);
        return batches;
    }
}
