// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Camera perspective projection (a.k.a. intrinsics).
/// 
/// If [archetypes.Transform3D] is logged for the same child/parent relationship (e.g. for the camera extrinsics), it takes precedence over [archetypes.Pinhole].
/// 
/// If you use named transform frames via the `child_frame` and `parent_frame` fields, you don't have to use [archetypes.CoordinateFrame]
/// as it is the case with other visualizations: for any entity with an [archetypes.Pinhole] the viewer will always visualize it
/// directly without needing a [archetypes.CoordinateFrame] to refer to the pinhole's child/parent frame.
/// 
/// </summary>
public sealed partial class Pinhole : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Pinhole";

    public ComponentBatch ImageFromCamera { get; private set; }
    public ComponentBatch? Resolution { get; private set; }
    public ComponentBatch? CameraXyz { get; private set; }
    public ComponentBatch? ChildFrame { get; private set; }
    public ComponentBatch? ParentFrame { get; private set; }
    public ComponentBatch? ImagePlaneDistance { get; private set; }
    public ComponentBatch? Color { get; private set; }
    public ComponentBatch? LineWidth { get; private set; }

    public Pinhole(ReadOnlySpan<Components.PinholeProjection> image_from_camera)
    {
        ImageFromCamera = ComponentBatch.FromLoggable(image_from_camera,
            new ComponentDescriptor(ArchetypeName, "Pinhole:image_from_camera", "rerun.components.PinholeProjection"));
    }

    public Pinhole(params Components.PinholeProjection[] image_from_camera) : this(image_from_camera.AsSpan()) { }

    public Pinhole WithResolution(ReadOnlySpan<Components.Resolution> resolution)
    {
        Resolution = ComponentBatch.FromLoggable(resolution,
            new ComponentDescriptor(ArchetypeName, "Pinhole:resolution", "rerun.components.Resolution"));
        return this;
    }

    public Pinhole WithResolution(params Components.Resolution[] resolution) => WithResolution(resolution.AsSpan());

    public Pinhole WithCameraXyz(ReadOnlySpan<Components.ViewCoordinates> camera_xyz)
    {
        CameraXyz = ComponentBatch.FromLoggable(camera_xyz,
            new ComponentDescriptor(ArchetypeName, "Pinhole:camera_xyz", "rerun.components.ViewCoordinates"));
        return this;
    }

    public Pinhole WithCameraXyz(params Components.ViewCoordinates[] camera_xyz) => WithCameraXyz(camera_xyz.AsSpan());

    public Pinhole WithChildFrame(ReadOnlySpan<Components.TransformFrameId> child_frame)
    {
        ChildFrame = ComponentBatch.FromLoggable(child_frame,
            new ComponentDescriptor(ArchetypeName, "Pinhole:child_frame", "rerun.components.TransformFrameId"));
        return this;
    }

    public Pinhole WithChildFrame(params Components.TransformFrameId[] child_frame) => WithChildFrame(child_frame.AsSpan());

    public Pinhole WithParentFrame(ReadOnlySpan<Components.TransformFrameId> parent_frame)
    {
        ParentFrame = ComponentBatch.FromLoggable(parent_frame,
            new ComponentDescriptor(ArchetypeName, "Pinhole:parent_frame", "rerun.components.TransformFrameId"));
        return this;
    }

    public Pinhole WithParentFrame(params Components.TransformFrameId[] parent_frame) => WithParentFrame(parent_frame.AsSpan());

    public Pinhole WithImagePlaneDistance(ReadOnlySpan<Components.ImagePlaneDistance> image_plane_distance)
    {
        ImagePlaneDistance = ComponentBatch.FromLoggable(image_plane_distance,
            new ComponentDescriptor(ArchetypeName, "Pinhole:image_plane_distance", "rerun.components.ImagePlaneDistance"));
        return this;
    }

    public Pinhole WithImagePlaneDistance(params Components.ImagePlaneDistance[] image_plane_distance) => WithImagePlaneDistance(image_plane_distance.AsSpan());

    public Pinhole WithColor(ReadOnlySpan<Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "Pinhole:color", "rerun.components.Color"));
        return this;
    }

    public Pinhole WithColor(params Components.Color[] color) => WithColor(color.AsSpan());

    public Pinhole WithLineWidth(ReadOnlySpan<Components.Radius> line_width)
    {
        LineWidth = ComponentBatch.FromLoggable(line_width,
            new ComponentDescriptor(ArchetypeName, "Pinhole:line_width", "rerun.components.Radius"));
        return this;
    }

    public Pinhole WithLineWidth(params Components.Radius[] line_width) => WithLineWidth(line_width.AsSpan());

    /// <summary>Create an empty Pinhole for partial updates. Use With*() to set fields.</summary>
    public static Pinhole UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Pinhole ClearFields() => new();

    private Pinhole() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(ImageFromCamera);
        if (Resolution != null) batches.Add(Resolution);
        if (CameraXyz != null) batches.Add(CameraXyz);
        if (ChildFrame != null) batches.Add(ChildFrame);
        if (ParentFrame != null) batches.Add(ParentFrame);
        if (ImagePlaneDistance != null) batches.Add(ImagePlaneDistance);
        if (Color != null) batches.Add(Color);
        if (LineWidth != null) batches.Add(LineWidth);
        return batches;
    }
}
