// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A 2D point cloud with positions and optional colors, radii, labels, etc.
/// 
/// </summary>
public sealed partial class Points2D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Points2D";

    public ComponentBatch Positions { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }
    public ComponentBatch? KeypointIds { get; private set; }

    public Points2D(ReadOnlySpan<Components.Position2D> positions)
    {
        Positions = ComponentBatch.FromLoggable(positions,
            new ComponentDescriptor(ArchetypeName, "Points2D:positions", "rerun.components.Position2D"));
    }

    public Points2D(params Components.Position2D[] positions) : this(positions.AsSpan()) { }

    public Points2D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Points2D:radii", "rerun.components.Radius"));
        return this;
    }

    public Points2D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Points2D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Points2D:colors", "rerun.components.Color"));
        return this;
    }

    public Points2D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Points2D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Points2D:labels", "rerun.components.Text"));
        return this;
    }

    public Points2D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Points2D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Points2D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Points2D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Points2D WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "Points2D:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public Points2D WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    public Points2D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Points2D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Points2D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    public Points2D WithKeypointIds(ReadOnlySpan<Components.KeypointId> keypoint_ids)
    {
        KeypointIds = ComponentBatch.FromLoggable(keypoint_ids,
            new ComponentDescriptor(ArchetypeName, "Points2D:keypoint_ids", "rerun.components.KeypointId"));
        return this;
    }

    public Points2D WithKeypointIds(params Components.KeypointId[] keypoint_ids) => WithKeypointIds(keypoint_ids.AsSpan());

    /// <summary>Create an empty Points2D for partial updates. Use With*() to set fields.</summary>
    public static Points2D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Points2D ClearFields() => new();

    private Points2D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        batches.Add(Positions);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (DrawOrder != null) batches.Add(DrawOrder);
        if (ClassIds != null) batches.Add(ClassIds);
        if (KeypointIds != null) batches.Add(KeypointIds);
        return batches;
    }
}
