// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A 3D point cloud with positions and optional colors, radii, labels, etc.
/// 
/// If there are multiple instance poses, the entire point cloud will be repeated for each of the poses.
/// 
/// </summary>
public sealed partial class Points3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Points3D";

    public ComponentBatch Positions { get; private set; }
    public ComponentBatch? Radii { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Labels { get; private set; }
    public ComponentBatch? ShowLabels { get; private set; }
    public ComponentBatch? ClassIds { get; private set; }
    public ComponentBatch? KeypointIds { get; private set; }

    public Points3D(ReadOnlySpan<Components.Position3D> positions)
    {
        Positions = ComponentBatch.FromLoggable(positions,
            new ComponentDescriptor(ArchetypeName, "Points3D:positions", "rerun.components.Position3D"));
    }

    public Points3D(params Components.Position3D[] positions) : this(positions.AsSpan()) { }

    public Points3D WithRadii(ReadOnlySpan<Components.Radius> radii)
    {
        Radii = ComponentBatch.FromLoggable(radii,
            new ComponentDescriptor(ArchetypeName, "Points3D:radii", "rerun.components.Radius"));
        return this;
    }

    public Points3D WithRadii(params Components.Radius[] radii) => WithRadii(radii.AsSpan());

    public Points3D WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "Points3D:colors", "rerun.components.Color"));
        return this;
    }

    public Points3D WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public Points3D WithLabels(ReadOnlySpan<Components.Text> labels)
    {
        Labels = ComponentBatch.FromLoggable(labels,
            new ComponentDescriptor(ArchetypeName, "Points3D:labels", "rerun.components.Text"));
        return this;
    }

    public Points3D WithLabels(params Components.Text[] labels) => WithLabels(labels.AsSpan());

    public Points3D WithShowLabels(ReadOnlySpan<Components.ShowLabels> show_labels)
    {
        ShowLabels = ComponentBatch.FromLoggable(show_labels,
            new ComponentDescriptor(ArchetypeName, "Points3D:show_labels", "rerun.components.ShowLabels"));
        return this;
    }

    public Points3D WithShowLabels(params Components.ShowLabels[] show_labels) => WithShowLabels(show_labels.AsSpan());

    public Points3D WithClassIds(ReadOnlySpan<Components.ClassId> class_ids)
    {
        ClassIds = ComponentBatch.FromLoggable(class_ids,
            new ComponentDescriptor(ArchetypeName, "Points3D:class_ids", "rerun.components.ClassId"));
        return this;
    }

    public Points3D WithClassIds(params Components.ClassId[] class_ids) => WithClassIds(class_ids.AsSpan());

    public Points3D WithKeypointIds(ReadOnlySpan<Components.KeypointId> keypoint_ids)
    {
        KeypointIds = ComponentBatch.FromLoggable(keypoint_ids,
            new ComponentDescriptor(ArchetypeName, "Points3D:keypoint_ids", "rerun.components.KeypointId"));
        return this;
    }

    public Points3D WithKeypointIds(params Components.KeypointId[] keypoint_ids) => WithKeypointIds(keypoint_ids.AsSpan());

    /// <summary>Create an empty Points3D for partial updates. Use With*() to set fields.</summary>
    public static Points3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Points3D ClearFields() => new();

    private Points3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(7);
        batches.Add(Positions);
        if (Radii != null) batches.Add(Radii);
        if (Colors != null) batches.Add(Colors);
        if (Labels != null) batches.Add(Labels);
        if (ShowLabels != null) batches.Add(ShowLabels);
        if (ClassIds != null) batches.Add(ClassIds);
        if (KeypointIds != null) batches.Add(KeypointIds);
        return batches;
    }
}
