// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A list of properties associated with a recording.
/// 
/// </summary>
public sealed partial class RecordingInfo : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.RecordingInfo";

    public ComponentBatch? StartTime { get; private set; }
    public ComponentBatch? Name { get; private set; }

    public RecordingInfo() { }

    public RecordingInfo WithStartTime(ReadOnlySpan<Components.Timestamp> start_time)
    {
        StartTime = ComponentBatch.FromLoggable(start_time,
            new ComponentDescriptor(ArchetypeName, "RecordingInfo:start_time", "rerun.components.Timestamp"));
        return this;
    }

    public RecordingInfo WithStartTime(params Components.Timestamp[] start_time) => WithStartTime(start_time.AsSpan());

    public RecordingInfo WithName(ReadOnlySpan<Components.Name> name)
    {
        Name = ComponentBatch.FromLoggable(name,
            new ComponentDescriptor(ArchetypeName, "RecordingInfo:name", "rerun.components.Name"));
        return this;
    }

    public RecordingInfo WithName(params Components.Name[] name) => WithName(name.AsSpan());

    /// <summary>Create an empty RecordingInfo for partial updates. Use With*() to set fields.</summary>
    public static RecordingInfo UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static RecordingInfo ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        if (StartTime != null) batches.Add(StartTime);
        if (Name != null) batches.Add(Name);
        return batches;
    }
}
