// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// One or more double-precision scalar values, e.g. for use for time-series plots.
/// 
/// The current timeline value will be used for the time/X-axis, hence scalars
/// should not be static.
/// Number of scalars per timestamp is expected to be the same over time.
/// 
/// When used to produce a plot, this archetype is used to provide the data that
/// is referenced by [archetypes.SeriesLines] or [archetypes.SeriesPoints]. You can do
/// this by logging both archetypes to the same path, or alternatively configuring
/// the plot-specific archetypes through the blueprint.
/// 
/// </summary>
public sealed partial class Scalars : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Scalars";

    public ComponentBatch ScalarsValue { get; private set; }

    public Scalars(ReadOnlySpan<Components.Scalar> scalars)
    {
        ScalarsValue = ComponentBatch.FromLoggable(scalars,
            new ComponentDescriptor(ArchetypeName, "Scalars:scalars", "rerun.components.Scalar"));
    }

    public Scalars(params Components.Scalar[] scalars) : this(scalars.AsSpan()) { }

    /// <summary>Create an empty Scalars for partial updates. Use With*() to set fields.</summary>
    public static Scalars UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Scalars ClearFields() => new();

    private Scalars() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(ScalarsValue);
        return batches;
    }
}
