// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// An image made up of integer [components.ClassId]s.
/// 
/// Each pixel corresponds to a [components.ClassId] that will be mapped to a color based on [archetypes.AnnotationContext].
/// 
/// In the case of floating point images, the label will be looked up based on rounding to the nearest
/// integer value.
/// 
/// Use [archetypes.AnnotationContext] to associate each class with a color and a label.
/// 
/// 
/// </summary>
public sealed partial class SegmentationImage : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.SegmentationImage";

    public ComponentBatch Buffer { get; private set; }
    public ComponentBatch Format { get; private set; }
    public ComponentBatch? Opacity { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }

    public SegmentationImage(ReadOnlySpan<Components.ImageBuffer> buffer, ReadOnlySpan<Components.ImageFormat> format)
    {
        Buffer = ComponentBatch.FromLoggable(buffer,
            new ComponentDescriptor(ArchetypeName, "SegmentationImage:buffer", "rerun.components.ImageBuffer"));
        Format = ComponentBatch.FromLoggable(format,
            new ComponentDescriptor(ArchetypeName, "SegmentationImage:format", "rerun.components.ImageFormat"));
    }

    public SegmentationImage(Components.ImageBuffer[] buffer, Components.ImageFormat[] format) : this(buffer.AsSpan(), format.AsSpan()) { }

    public SegmentationImage WithOpacity(ReadOnlySpan<Components.Opacity> opacity)
    {
        Opacity = ComponentBatch.FromLoggable(opacity,
            new ComponentDescriptor(ArchetypeName, "SegmentationImage:opacity", "rerun.components.Opacity"));
        return this;
    }

    public SegmentationImage WithOpacity(params Components.Opacity[] opacity) => WithOpacity(opacity.AsSpan());

    public SegmentationImage WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "SegmentationImage:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public SegmentationImage WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    /// <summary>Create an empty SegmentationImage for partial updates. Use With*() to set fields.</summary>
    public static SegmentationImage UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static SegmentationImage ClearFields() => new();

    private SegmentationImage() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Buffer);
        batches.Add(Format);
        if (Opacity != null) batches.Add(Opacity);
        if (DrawOrder != null) batches.Add(DrawOrder);
        return batches;
    }
}
