// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Define the style properties for one or more point series (scatter plot) in a chart.
/// 
/// This archetype only provides styling information.
/// Changes over time are supported for most but not all its fields (see respective fields for details),
/// it's generally recommended to log this type as static.
/// 
/// The underlying data needs to be logged to the same entity-path using [archetypes.Scalars].
/// Dimensionality of the scalar arrays logged at each time point is assumed to be the same over time.
/// 
/// </summary>
public sealed partial class SeriesPoints : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.SeriesPoints";

    public ComponentBatch Markers { get; private set; }
    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Names { get; private set; }
    public ComponentBatch? VisibleSeries { get; private set; }
    public ComponentBatch? MarkerSizes { get; private set; }

    public SeriesPoints(ReadOnlySpan<Components.MarkerShape> markers)
    {
        Markers = ComponentBatch.FromLoggable(markers,
            new ComponentDescriptor(ArchetypeName, "SeriesPoints:markers", "rerun.components.MarkerShape"));
    }

    public SeriesPoints(params Components.MarkerShape[] markers) : this(markers.AsSpan()) { }

    public SeriesPoints WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "SeriesPoints:colors", "rerun.components.Color"));
        return this;
    }

    public SeriesPoints WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public SeriesPoints WithNames(ReadOnlySpan<Components.Name> names)
    {
        Names = ComponentBatch.FromLoggable(names,
            new ComponentDescriptor(ArchetypeName, "SeriesPoints:names", "rerun.components.Name"));
        return this;
    }

    public SeriesPoints WithNames(params Components.Name[] names) => WithNames(names.AsSpan());

    public SeriesPoints WithVisibleSeries(ReadOnlySpan<Components.Visible> visible_series)
    {
        VisibleSeries = ComponentBatch.FromLoggable(visible_series,
            new ComponentDescriptor(ArchetypeName, "SeriesPoints:visible_series", "rerun.components.Visible"));
        return this;
    }

    public SeriesPoints WithVisibleSeries(params Components.Visible[] visible_series) => WithVisibleSeries(visible_series.AsSpan());

    public SeriesPoints WithMarkerSizes(ReadOnlySpan<Components.MarkerSize> marker_sizes)
    {
        MarkerSizes = ComponentBatch.FromLoggable(marker_sizes,
            new ComponentDescriptor(ArchetypeName, "SeriesPoints:marker_sizes", "rerun.components.MarkerSize"));
        return this;
    }

    public SeriesPoints WithMarkerSizes(params Components.MarkerSize[] marker_sizes) => WithMarkerSizes(marker_sizes.AsSpan());

    /// <summary>Create an empty SeriesPoints for partial updates. Use With*() to set fields.</summary>
    public static SeriesPoints UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static SeriesPoints ClearFields() => new();

    private SeriesPoints() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(5);
        batches.Add(Markers);
        if (Colors != null) batches.Add(Colors);
        if (Names != null) batches.Add(Names);
        if (VisibleSeries != null) batches.Add(VisibleSeries);
        if (MarkerSizes != null) batches.Add(MarkerSizes);
        return batches;
    }
}
