// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Define the style properties for one or more line series in a chart.
/// 
/// This archetype only provides styling information.
/// Changes over time are supported for most but not all its fields (see respective fields for details),
/// it's generally recommended to log this type as static.
/// 
/// The underlying data needs to be logged to the same entity-path using [archetypes.Scalars].
/// Dimensionality of the scalar arrays logged at each time point is assumed to be the same over time.
/// 
/// </summary>
public sealed partial class SeriesLines : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.SeriesLines";

    public ComponentBatch? Colors { get; private set; }
    public ComponentBatch? Widths { get; private set; }
    public ComponentBatch? Names { get; private set; }
    public ComponentBatch? VisibleSeries { get; private set; }
    public ComponentBatch? AggregationPolicy { get; private set; }
    public ComponentBatch? InterpolationMode { get; private set; }

    public SeriesLines() { }

    public SeriesLines WithColors(ReadOnlySpan<Components.Color> colors)
    {
        Colors = ComponentBatch.FromLoggable(colors,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:colors", "rerun.components.Color"));
        return this;
    }

    public SeriesLines WithColors(params Components.Color[] colors) => WithColors(colors.AsSpan());

    public SeriesLines WithWidths(ReadOnlySpan<Components.StrokeWidth> widths)
    {
        Widths = ComponentBatch.FromLoggable(widths,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:widths", "rerun.components.StrokeWidth"));
        return this;
    }

    public SeriesLines WithWidths(params Components.StrokeWidth[] widths) => WithWidths(widths.AsSpan());

    public SeriesLines WithNames(ReadOnlySpan<Components.Name> names)
    {
        Names = ComponentBatch.FromLoggable(names,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:names", "rerun.components.Name"));
        return this;
    }

    public SeriesLines WithNames(params Components.Name[] names) => WithNames(names.AsSpan());

    public SeriesLines WithVisibleSeries(ReadOnlySpan<Components.Visible> visible_series)
    {
        VisibleSeries = ComponentBatch.FromLoggable(visible_series,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:visible_series", "rerun.components.Visible"));
        return this;
    }

    public SeriesLines WithVisibleSeries(params Components.Visible[] visible_series) => WithVisibleSeries(visible_series.AsSpan());

    public SeriesLines WithAggregationPolicy(ReadOnlySpan<Components.AggregationPolicy> aggregation_policy)
    {
        AggregationPolicy = ComponentBatch.FromLoggable(aggregation_policy,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:aggregation_policy", "rerun.components.AggregationPolicy"));
        return this;
    }

    public SeriesLines WithAggregationPolicy(params Components.AggregationPolicy[] aggregation_policy) => WithAggregationPolicy(aggregation_policy.AsSpan());

    public SeriesLines WithInterpolationMode(ReadOnlySpan<Components.InterpolationMode> interpolation_mode)
    {
        InterpolationMode = ComponentBatch.FromLoggable(interpolation_mode,
            new ComponentDescriptor(ArchetypeName, "SeriesLines:interpolation_mode", "rerun.components.InterpolationMode"));
        return this;
    }

    public SeriesLines WithInterpolationMode(params Components.InterpolationMode[] interpolation_mode) => WithInterpolationMode(interpolation_mode.AsSpan());

    /// <summary>Create an empty SeriesLines for partial updates. Use With*() to set fields.</summary>
    public static SeriesLines UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static SeriesLines ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(6);
        if (Colors != null) batches.Add(Colors);
        if (Widths != null) batches.Add(Widths);
        if (Names != null) batches.Add(Names);
        if (VisibleSeries != null) batches.Add(VisibleSeries);
        if (AggregationPolicy != null) batches.Add(AggregationPolicy);
        if (InterpolationMode != null) batches.Add(InterpolationMode);
        return batches;
    }
}
