// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// An N-dimensional array of numbers.
/// 
/// 
/// 
/// </summary>
public sealed partial class Tensor : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Tensor";

    public ComponentBatch Data { get; private set; }
    public ComponentBatch? ValueRange { get; private set; }

    public Tensor(ReadOnlySpan<Components.TensorData> data)
    {
        Data = ComponentBatch.FromLoggable(data,
            new ComponentDescriptor(ArchetypeName, "Tensor:data", "rerun.components.TensorData"));
    }

    public Tensor(params Components.TensorData[] data) : this(data.AsSpan()) { }

    public Tensor WithValueRange(ReadOnlySpan<Components.ValueRange> value_range)
    {
        ValueRange = ComponentBatch.FromLoggable(value_range,
            new ComponentDescriptor(ArchetypeName, "Tensor:value_range", "rerun.components.ValueRange"));
        return this;
    }

    public Tensor WithValueRange(params Components.ValueRange[] value_range) => WithValueRange(value_range.AsSpan());

    /// <summary>Create an empty Tensor for partial updates. Use With*() to set fields.</summary>
    public static Tensor UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Tensor ClearFields() => new();

    private Tensor() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(Data);
        if (ValueRange != null) batches.Add(ValueRange);
        return batches;
    }
}
