// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A text element intended to be displayed in its own text box.
/// 
/// Supports raw text and markdown.
/// 
/// </summary>
public sealed partial class TextDocument : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.TextDocument";

    public ComponentBatch Text { get; private set; }
    public ComponentBatch? MediaType { get; private set; }

    public TextDocument(ReadOnlySpan<Components.Text> text)
    {
        Text = ComponentBatch.FromLoggable(text,
            new ComponentDescriptor(ArchetypeName, "TextDocument:text", "rerun.components.Text"));
    }

    public TextDocument(params Components.Text[] text) : this(text.AsSpan()) { }

    public TextDocument WithMediaType(ReadOnlySpan<Components.MediaType> media_type)
    {
        MediaType = ComponentBatch.FromLoggable(media_type,
            new ComponentDescriptor(ArchetypeName, "TextDocument:media_type", "rerun.components.MediaType"));
        return this;
    }

    public TextDocument WithMediaType(params Components.MediaType[] media_type) => WithMediaType(media_type.AsSpan());

    /// <summary>Create an empty TextDocument for partial updates. Use With*() to set fields.</summary>
    public static TextDocument UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TextDocument ClearFields() => new();

    private TextDocument() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(Text);
        if (MediaType != null) batches.Add(MediaType);
        return batches;
    }
}
