// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A log entry in a text log, comprised of a text body and its log level.
/// 
/// </summary>
public sealed partial class TextLog : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.TextLog";

    public ComponentBatch Text { get; private set; }
    public ComponentBatch? Level { get; private set; }
    public ComponentBatch? Color { get; private set; }

    public TextLog(ReadOnlySpan<Components.Text> text)
    {
        Text = ComponentBatch.FromLoggable(text,
            new ComponentDescriptor(ArchetypeName, "TextLog:text", "rerun.components.Text"));
    }

    public TextLog(params Components.Text[] text) : this(text.AsSpan()) { }

    public TextLog WithLevel(ReadOnlySpan<Components.TextLogLevel> level)
    {
        Level = ComponentBatch.FromLoggable(level,
            new ComponentDescriptor(ArchetypeName, "TextLog:level", "rerun.components.TextLogLevel"));
        return this;
    }

    public TextLog WithLevel(params Components.TextLogLevel[] level) => WithLevel(level.AsSpan());

    public TextLog WithColor(ReadOnlySpan<Components.Color> color)
    {
        Color = ComponentBatch.FromLoggable(color,
            new ComponentDescriptor(ArchetypeName, "TextLog:color", "rerun.components.Color"));
        return this;
    }

    public TextLog WithColor(params Components.Color[] color) => WithColor(color.AsSpan());

    /// <summary>Create an empty TextLog for partial updates. Use With*() to set fields.</summary>
    public static TextLog UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TextLog ClearFields() => new();

    private TextLog() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(3);
        batches.Add(Text);
        if (Level != null) batches.Add(Level);
        if (Color != null) batches.Add(Color);
        return batches;
    }
}
