// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A visual representation of a [archetypes.Transform3D].
/// 
/// </summary>
public sealed partial class TransformAxes3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.TransformAxes3D";

    public ComponentBatch AxisLength { get; private set; }
    public ComponentBatch? ShowFrame { get; private set; }

    public TransformAxes3D(ReadOnlySpan<Components.AxisLength> axis_length)
    {
        AxisLength = ComponentBatch.FromLoggable(axis_length,
            new ComponentDescriptor(ArchetypeName, "TransformAxes3D:axis_length", "rerun.components.AxisLength"));
    }

    public TransformAxes3D(params Components.AxisLength[] axis_length) : this(axis_length.AsSpan()) { }

    public TransformAxes3D WithShowFrame(ReadOnlySpan<Components.ShowLabels> show_frame)
    {
        ShowFrame = ComponentBatch.FromLoggable(show_frame,
            new ComponentDescriptor(ArchetypeName, "TransformAxes3D:show_frame", "rerun.components.ShowLabels"));
        return this;
    }

    public TransformAxes3D WithShowFrame(params Components.ShowLabels[] show_frame) => WithShowFrame(show_frame.AsSpan());

    /// <summary>Create an empty TransformAxes3D for partial updates. Use With*() to set fields.</summary>
    public static TransformAxes3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static TransformAxes3D ClearFields() => new();

    private TransformAxes3D() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(2);
        batches.Add(AxisLength);
        if (ShowFrame != null) batches.Add(ShowFrame);
        return batches;
    }
}
