// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// A transform between two 3D spaces, i.e. a pose.
/// 
/// From the point of view of the entity's coordinate system,
/// all components are applied in the inverse order they are listed here.
/// E.g. if both a translation and a mat3x3 transform are present,
/// the 3x3 matrix is applied first, followed by the translation.
/// 
/// Whenever you log this archetype, the state of the resulting transform relationship is fully reset to the new archetype.
/// This means that if you first log a transform with only a translation, and then log one with only a rotation,
/// it will be resolved to a transform with only a rotation.
/// (This is unlike how we usually apply latest-at semantics on an archetype where we take the latest state of any component independently)
/// 
/// For transforms that affect only a single entity and do not propagate along the entity tree refer to [archetypes.InstancePoses3D].
/// 
/// </summary>
public sealed partial class Transform3D : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.Transform3D";

    public ComponentBatch? Translation { get; private set; }
    public ComponentBatch? RotationAxisAngle { get; private set; }
    public ComponentBatch? Quaternion { get; private set; }
    public ComponentBatch? Scale { get; private set; }
    public ComponentBatch? Mat3x3 { get; private set; }
    public ComponentBatch? Relation { get; private set; }
    public ComponentBatch? ChildFrame { get; private set; }
    public ComponentBatch? ParentFrame { get; private set; }

    public Transform3D() { }

    public Transform3D WithTranslation(ReadOnlySpan<Components.Translation3D> translation)
    {
        Translation = ComponentBatch.FromLoggable(translation,
            new ComponentDescriptor(ArchetypeName, "Transform3D:translation", "rerun.components.Translation3D"));
        return this;
    }

    public Transform3D WithTranslation(params Components.Translation3D[] translation) => WithTranslation(translation.AsSpan());

    public Transform3D WithRotationAxisAngle(ReadOnlySpan<Components.RotationAxisAngle> rotation_axis_angle)
    {
        RotationAxisAngle = ComponentBatch.FromLoggable(rotation_axis_angle,
            new ComponentDescriptor(ArchetypeName, "Transform3D:rotation_axis_angle", "rerun.components.RotationAxisAngle"));
        return this;
    }

    public Transform3D WithRotationAxisAngle(params Components.RotationAxisAngle[] rotation_axis_angle) => WithRotationAxisAngle(rotation_axis_angle.AsSpan());

    public Transform3D WithQuaternion(ReadOnlySpan<Components.RotationQuat> quaternion)
    {
        Quaternion = ComponentBatch.FromLoggable(quaternion,
            new ComponentDescriptor(ArchetypeName, "Transform3D:quaternion", "rerun.components.RotationQuat"));
        return this;
    }

    public Transform3D WithQuaternion(params Components.RotationQuat[] quaternion) => WithQuaternion(quaternion.AsSpan());

    public Transform3D WithScale(ReadOnlySpan<Components.Scale3D> scale)
    {
        Scale = ComponentBatch.FromLoggable(scale,
            new ComponentDescriptor(ArchetypeName, "Transform3D:scale", "rerun.components.Scale3D"));
        return this;
    }

    public Transform3D WithScale(params Components.Scale3D[] scale) => WithScale(scale.AsSpan());

    public Transform3D WithMat3x3(ReadOnlySpan<Components.TransformMat3x3> mat3x3)
    {
        Mat3x3 = ComponentBatch.FromLoggable(mat3x3,
            new ComponentDescriptor(ArchetypeName, "Transform3D:mat3x3", "rerun.components.TransformMat3x3"));
        return this;
    }

    public Transform3D WithMat3x3(params Components.TransformMat3x3[] mat3x3) => WithMat3x3(mat3x3.AsSpan());

    public Transform3D WithRelation(ReadOnlySpan<Components.TransformRelation> relation)
    {
        Relation = ComponentBatch.FromLoggable(relation,
            new ComponentDescriptor(ArchetypeName, "Transform3D:relation", "rerun.components.TransformRelation"));
        return this;
    }

    public Transform3D WithRelation(params Components.TransformRelation[] relation) => WithRelation(relation.AsSpan());

    public Transform3D WithChildFrame(ReadOnlySpan<Components.TransformFrameId> child_frame)
    {
        ChildFrame = ComponentBatch.FromLoggable(child_frame,
            new ComponentDescriptor(ArchetypeName, "Transform3D:child_frame", "rerun.components.TransformFrameId"));
        return this;
    }

    public Transform3D WithChildFrame(params Components.TransformFrameId[] child_frame) => WithChildFrame(child_frame.AsSpan());

    public Transform3D WithParentFrame(ReadOnlySpan<Components.TransformFrameId> parent_frame)
    {
        ParentFrame = ComponentBatch.FromLoggable(parent_frame,
            new ComponentDescriptor(ArchetypeName, "Transform3D:parent_frame", "rerun.components.TransformFrameId"));
        return this;
    }

    public Transform3D WithParentFrame(params Components.TransformFrameId[] parent_frame) => WithParentFrame(parent_frame.AsSpan());

    /// <summary>Create an empty Transform3D for partial updates. Use With*() to set fields.</summary>
    public static Transform3D UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static Transform3D ClearFields() => new();

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(8);
        if (Translation != null) batches.Add(Translation);
        if (RotationAxisAngle != null) batches.Add(RotationAxisAngle);
        if (Quaternion != null) batches.Add(Quaternion);
        if (Scale != null) batches.Add(Scale);
        if (Mat3x3 != null) batches.Add(Mat3x3);
        if (Relation != null) batches.Add(Relation);
        if (ChildFrame != null) batches.Add(ChildFrame);
        if (ParentFrame != null) batches.Add(ParentFrame);
        return batches;
    }
}
