// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// Video stream consisting of raw video chunks.
/// 
/// For logging video containers like mp4, refer to [archetypes.AssetVideo] and [archetypes.VideoFrameReference].
/// To learn more about video support in Rerun, check the [video reference](https://rerun.io/docs/reference/video).
/// 
/// All components except `sample` are typically logged statically once per entity.
/// `sample` is then logged repeatedly for each frame on the timeline.
/// 
/// TODO(#10422): [archetypes.VideoFrameReference] does not yet work with [archetypes.VideoStream].
/// 
/// </summary>
public sealed partial class VideoStream : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.VideoStream";

    public ComponentBatch Codec { get; private set; }
    public ComponentBatch? Sample { get; private set; }
    public ComponentBatch? Opacity { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }

    public VideoStream(ReadOnlySpan<Components.VideoCodec> codec)
    {
        Codec = ComponentBatch.FromLoggable(codec,
            new ComponentDescriptor(ArchetypeName, "VideoStream:codec", "rerun.components.VideoCodec"));
    }

    public VideoStream(params Components.VideoCodec[] codec) : this(codec.AsSpan()) { }

    public VideoStream WithSample(ReadOnlySpan<Components.VideoSample> sample)
    {
        Sample = ComponentBatch.FromLoggable(sample,
            new ComponentDescriptor(ArchetypeName, "VideoStream:sample", "rerun.components.VideoSample"));
        return this;
    }

    public VideoStream WithSample(params Components.VideoSample[] sample) => WithSample(sample.AsSpan());

    public VideoStream WithOpacity(ReadOnlySpan<Components.Opacity> opacity)
    {
        Opacity = ComponentBatch.FromLoggable(opacity,
            new ComponentDescriptor(ArchetypeName, "VideoStream:opacity", "rerun.components.Opacity"));
        return this;
    }

    public VideoStream WithOpacity(params Components.Opacity[] opacity) => WithOpacity(opacity.AsSpan());

    public VideoStream WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "VideoStream:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public VideoStream WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    /// <summary>Create an empty VideoStream for partial updates. Use With*() to set fields.</summary>
    public static VideoStream UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static VideoStream ClearFields() => new();

    private VideoStream() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Codec);
        if (Sample != null) batches.Add(Sample);
        if (Opacity != null) batches.Add(Opacity);
        if (DrawOrder != null) batches.Add(DrawOrder);
        return batches;
    }
}
