// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// References a single video frame.
/// 
/// Used to display individual video frames from a [archetypes.AssetVideo].
/// To show an entire video, a video frame reference for each frame of the video should be logged.
/// 
/// See <https://rerun.io/docs/reference/video> for details of what is and isn't supported.
/// 
/// TODO(#10422): [archetypes.VideoFrameReference] does not yet work with [archetypes.VideoStream].
/// 
/// </summary>
public sealed partial class VideoFrameReference : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.VideoFrameReference";

    public ComponentBatch Timestamp { get; private set; }
    public ComponentBatch? VideoReference { get; private set; }
    public ComponentBatch? Opacity { get; private set; }
    public ComponentBatch? DrawOrder { get; private set; }

    public VideoFrameReference(ReadOnlySpan<Components.VideoTimestamp> timestamp)
    {
        Timestamp = ComponentBatch.FromLoggable(timestamp,
            new ComponentDescriptor(ArchetypeName, "VideoFrameReference:timestamp", "rerun.components.VideoTimestamp"));
    }

    public VideoFrameReference(params Components.VideoTimestamp[] timestamp) : this(timestamp.AsSpan()) { }

    public VideoFrameReference WithVideoReference(ReadOnlySpan<Components.EntityPath> video_reference)
    {
        VideoReference = ComponentBatch.FromLoggable(video_reference,
            new ComponentDescriptor(ArchetypeName, "VideoFrameReference:video_reference", "rerun.components.EntityPath"));
        return this;
    }

    public VideoFrameReference WithVideoReference(params Components.EntityPath[] video_reference) => WithVideoReference(video_reference.AsSpan());

    public VideoFrameReference WithOpacity(ReadOnlySpan<Components.Opacity> opacity)
    {
        Opacity = ComponentBatch.FromLoggable(opacity,
            new ComponentDescriptor(ArchetypeName, "VideoFrameReference:opacity", "rerun.components.Opacity"));
        return this;
    }

    public VideoFrameReference WithOpacity(params Components.Opacity[] opacity) => WithOpacity(opacity.AsSpan());

    public VideoFrameReference WithDrawOrder(ReadOnlySpan<Components.DrawOrder> draw_order)
    {
        DrawOrder = ComponentBatch.FromLoggable(draw_order,
            new ComponentDescriptor(ArchetypeName, "VideoFrameReference:draw_order", "rerun.components.DrawOrder"));
        return this;
    }

    public VideoFrameReference WithDrawOrder(params Components.DrawOrder[] draw_order) => WithDrawOrder(draw_order.AsSpan());

    /// <summary>Create an empty VideoFrameReference for partial updates. Use With*() to set fields.</summary>
    public static VideoFrameReference UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static VideoFrameReference ClearFields() => new();

    private VideoFrameReference() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(4);
        batches.Add(Timestamp);
        if (VideoReference != null) batches.Add(VideoReference);
        if (Opacity != null) batches.Add(Opacity);
        if (DrawOrder != null) batches.Add(DrawOrder);
        return batches;
    }
}
