// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Rerun.Net.Components;

namespace Rerun.Net.Archetypes;

/// <summary>
/// How we interpret the coordinate system of an entity/space.
/// 
/// For instance: What is "up"? What does the Z axis mean?
/// 
/// The three coordinates are always ordered as [x, y, z].
/// 
/// For example [Right, Down, Forward] means that the X axis points to the right, the Y axis points
/// down, and the Z axis points forward.
/// 
/// Make sure that this archetype is logged at or above the origin entity path of your 3D views.
/// 
/// ⚠ [Rerun does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
/// 
/// </summary>
public sealed partial class ViewCoordinates : IAsComponents
{
    private const string ArchetypeName = "rerun.archetypes.ViewCoordinates";

    public ComponentBatch Xyz { get; private set; }

    public ViewCoordinates(ReadOnlySpan<Components.ViewCoordinates> xyz)
    {
        Xyz = ComponentBatch.FromLoggable(xyz,
            new ComponentDescriptor(ArchetypeName, "ViewCoordinates:xyz", "rerun.components.ViewCoordinates"));
    }

    public ViewCoordinates(params Components.ViewCoordinates[] xyz) : this(xyz.AsSpan()) { }

    /// <summary>Create an empty ViewCoordinates for partial updates. Use With*() to set fields.</summary>
    public static ViewCoordinates UpdateFields() => new();

    /// <summary>Clear all fields, then use With*() to set specific ones.</summary>
    public static ViewCoordinates ClearFields() => new();

    private ViewCoordinates() { }

    public IReadOnlyList<ComponentBatch> AsBatches()
    {
        var batches = new List<ComponentBatch>(1);
        batches.Add(Xyz);
        return batches;
    }
}
