// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A reference to a range of time.
/// </summary>
public readonly record struct AbsoluteTimeRange(global::Rerun.Net.Datatypes.AbsoluteTimeRange Range) : ILoggable<AbsoluteTimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.AbsoluteTimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<AbsoluteTimeRange> data)
    {
        var inner = new global::Rerun.Net.Datatypes.AbsoluteTimeRange[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Range;
        return global::Rerun.Net.Datatypes.AbsoluteTimeRange.ToArrow(inner);
    }
}
