// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The active tab in a tabbed container.
/// </summary>
public readonly record struct ActiveTab(global::Rerun.Net.Datatypes.EntityPath Tab) : ILoggable<ActiveTab>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ActiveTab");

    public static IArrowArray ToArrow(ReadOnlySpan<ActiveTab> data)
    {
        var inner = new global::Rerun.Net.Datatypes.EntityPath[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Tab;
        return global::Rerun.Net.Datatypes.EntityPath.ToArrow(inner);
    }
}
