// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Angular speed, used for rotation speed for example.
/// </summary>
public readonly record struct AngularSpeed(double Speed) : ILoggable<AngularSpeed>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.AngularSpeed");

    public static IArrowArray ToArrow(ReadOnlySpan<AngularSpeed> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Speed);
        return builder.Build();
    }
}
