// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Whether empty cells in a dataframe should be filled with a latest-at query.
/// </summary>
public readonly record struct ApplyLatestAt(bool ApplyLatestAtValue) : ILoggable<ApplyLatestAt>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ApplyLatestAt");

    public static IArrowArray ToArrow(ReadOnlySpan<ApplyLatestAt> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.ApplyLatestAtValue);
        return builder.Build();
    }
}
