// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Whether the viewport layout is determined automatically.
/// </summary>
public readonly record struct AutoLayout(bool AutoLayoutValue) : ILoggable<AutoLayout>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.AutoLayout");

    public static IArrowArray ToArrow(ReadOnlySpan<AutoLayout> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.AutoLayoutValue);
        return builder.Build();
    }
}
