// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Whether or not views should be created automatically.
/// </summary>
public readonly record struct AutoViews(bool AutoViewsValue) : ILoggable<AutoViews>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.AutoViews");

    public static IArrowArray ToArrow(ReadOnlySpan<AutoViews> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.AutoViewsValue);
        return builder.Build();
    }
}
