// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The type of the background in a view.
/// </summary>
public enum BackgroundKindValue : byte
{
    Invalid = 0,
    GradientDark,
    GradientBright,
    SolidColor,
}

/// <summary>
/// The type of the background in a view.
/// </summary>
public readonly record struct BackgroundKind(BackgroundKindValue Value) : ILoggable<BackgroundKind>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.BackgroundKind");

    public static IArrowArray ToArrow(ReadOnlySpan<BackgroundKind> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
