// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The order of component columns (which remain always grouped by entity path) in the dataframe view.
/// 
/// Entities not in this list are appended at the end in their default order.
/// Entities in this list that are not present in the view are ignored.
/// </summary>
public readonly record struct ColumnOrder(global::Rerun.Net.Datatypes.EntityPath[] EntityPaths) : ILoggable<ColumnOrder>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ColumnOrder");

    public static IArrowArray ToArrow(ReadOnlySpan<ColumnOrder> data)
    {
        // Flatten all inner arrays and build offsets for ListArray
        var allItems = new System.Collections.Generic.List<global::Rerun.Net.Datatypes.EntityPath>();
        var offsets = new Int32Array.Builder();
        offsets.Append(0);
        foreach (var v in data)
        {
            foreach (var item in v.EntityPaths)
                allItems.Add(item);
            offsets.Append(allItems.Count);
        }
        var valuesArray = global::Rerun.Net.Datatypes.EntityPath.ToArrow(allItems.ToArray());
        var offsetsArray = offsets.Build();
        var listType = new Apache.Arrow.Types.ListType(
            new Apache.Arrow.Field("item", valuesArray.Data.DataType, false));
        var listData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, offsetsArray.ValueBuffer },
            new[] { valuesArray.Data });
        return new ListArray(listData);
    }
}
