// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The layout share of a column in the container.
/// </summary>
public readonly record struct ColumnShare(float Share) : ILoggable<ColumnShare>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ColumnShare");

    public static IArrowArray ToArrow(ReadOnlySpan<ColumnShare> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Share);
        return builder.Build();
    }
}
