// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

public readonly record struct ComponentColumnSelector(Datatypes.ComponentColumnSelector Selector) : ILoggable<ComponentColumnSelector>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ComponentColumnSelector");

    public static IArrowArray ToArrow(ReadOnlySpan<ComponentColumnSelector> data)
    {
        var inner = new Datatypes.ComponentColumnSelector[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Selector;
        return Datatypes.ComponentColumnSelector.ToArrow(inner);
    }
}
