// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The kind of a blueprint container (tabs, grid, …).
/// </summary>
public enum ContainerKindValue : byte
{
    Invalid = 0,
    Tabs,
    Horizontal,
    Vertical,
    Grid,
}

/// <summary>
/// The kind of a blueprint container (tabs, grid, …).
/// </summary>
public readonly record struct ContainerKind(ContainerKindValue Value) : ILoggable<ContainerKind>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ContainerKind");

    public static IArrowArray ToArrow(ReadOnlySpan<ContainerKind> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
