// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// One of four 2D corners, typically used to align objects.
/// </summary>
public enum Corner2DValue : byte
{
    Invalid = 0,
    LeftTop,
    RightTop,
    LeftBottom , // We put it on the left side by default so that it does not cover the newest data coming n on the right side.,
    RightBottom,
}

/// <summary>
/// One of four 2D corners, typically used to align objects.
/// </summary>
public readonly record struct Corner2D(Corner2DValue Value) : ILoggable<Corner2D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.Corner2D");

    public static IArrowArray ToArrow(ReadOnlySpan<Corner2D> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
