// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Whether a procedure is enabled.
/// </summary>
public readonly record struct Enabled(bool Visible) : ILoggable<Enabled>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.Enabled");

    public static IArrowArray ToArrow(ReadOnlySpan<Enabled> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.Visible);
        return builder.Build();
    }
}
