// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The kind of the 3D eye to view a scene in a [views.Spatial3DView].
/// 
/// This is used to specify how the controls of the view react to user input (such as mouse gestures).
/// </summary>
public enum Eye3DKindValue : byte
{
    Invalid = 0,
    FirstPerson,
    Orbital,
}

/// <summary>
/// The kind of the 3D eye to view a scene in a [views.Spatial3DView].
/// 
/// This is used to specify how the controls of the view react to user input (such as mouse gestures).
/// </summary>
public readonly record struct Eye3DKind(Eye3DKindValue Value) : ILoggable<Eye3DKind>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.Eye3DKind");

    public static IArrowArray ToArrow(ReadOnlySpan<Eye3DKind> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
