// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Configuration for the filter is not null feature of the dataframe view.
/// </summary>
public readonly record struct FilterIsNotNull(global::Rerun.Net.Blueprint.Datatypes.FilterIsNotNull FilterIsNotNullValue) : ILoggable<FilterIsNotNull>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.FilterIsNotNull");

    public static IArrowArray ToArrow(ReadOnlySpan<FilterIsNotNull> data)
    {
        var inner = new global::Rerun.Net.Blueprint.Datatypes.FilterIsNotNull[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].FilterIsNotNullValue;
        return global::Rerun.Net.Blueprint.Datatypes.FilterIsNotNull.ToArrow(inner);
    }
}
