// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

public readonly record struct FilterByRange(global::Rerun.Net.Blueprint.Datatypes.FilterByRange Range) : ILoggable<FilterByRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.FilterByRange");

    public static IArrowArray ToArrow(ReadOnlySpan<FilterByRange> data)
    {
        var inner = new global::Rerun.Net.Blueprint.Datatypes.FilterByRange[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Range;
        return global::Rerun.Net.Blueprint.Datatypes.FilterByRange.ToArrow(inner);
    }
}
