// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The target distance between two nodes.
/// 
/// This is helpful to scale the layout, for example if long labels are involved.
/// </summary>
public readonly record struct ForceDistance(double Distance) : ILoggable<ForceDistance>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ForceDistance");

    public static IArrowArray ToArrow(ReadOnlySpan<ForceDistance> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Distance);
        return builder.Build();
    }
}
