// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Specifies how often this force should be applied per iteration.
/// 
/// Increasing this parameter can lead to better results at the cost of longer computation time.
/// </summary>
public readonly record struct ForceIterations(ulong Distance) : ILoggable<ForceIterations>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ForceIterations");

    public static IArrowArray ToArrow(ReadOnlySpan<ForceIterations> data)
    {
        var builder = new UInt64Array.Builder();
        foreach (var v in data)
            builder.Append(v.Distance);
        return builder.Build();
    }
}
