// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Frames per second for a sequence timeline.
/// </summary>
public readonly record struct Fps(double FpsValue) : ILoggable<Fps>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.Fps");

    public static IArrowArray ToArrow(ReadOnlySpan<Fps> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.FpsValue);
        return builder.Build();
    }
}
