// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Space between grid lines of one line to the next in scene units.
/// </summary>
public readonly record struct GridSpacing(float Distance) : ILoggable<GridSpacing>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.GridSpacing");

    public static IArrowArray ToArrow(ReadOnlySpan<GridSpacing> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Distance);
        return builder.Build();
    }
}
