// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// How many columns a grid container should have.
/// </summary>
public readonly record struct GridColumns(uint Columns) : ILoggable<GridColumns>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.GridColumns");

    public static IArrowArray ToArrow(ReadOnlySpan<GridColumns> data)
    {
        var builder = new UInt32Array.Builder();
        foreach (var v in data)
            builder.Append(v.Columns);
        return builder.Build();
    }
}
