// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// All the contents in the container.
/// </summary>
public readonly record struct IncludedContent(global::Rerun.Net.Datatypes.EntityPath Contents) : ILoggable<IncludedContent>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.IncludedContent");

    public static IArrowArray ToArrow(ReadOnlySpan<IncludedContent> data)
    {
        var inner = new global::Rerun.Net.Datatypes.EntityPath[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Contents;
        return global::Rerun.Net.Datatypes.EntityPath.ToArrow(inner);
    }
}
