// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// How should the horizontal/X/time axis be linked across multiple plots
/// </summary>
public enum LinkAxisValue : byte
{
    Invalid = 0,
    Independent = 1,
    LinkToGlobal = 2,
}

/// <summary>
/// How should the horizontal/X/time axis be linked across multiple plots
/// </summary>
public readonly record struct LinkAxis(LinkAxisValue Value) : ILoggable<LinkAxis>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.LinkAxis");

    public static IArrowArray ToArrow(ReadOnlySpan<LinkAxis> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
