// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Indicate whether the range should be locked when zooming in on the data.
/// 
/// Default is `false`, i.e. zoom will change the visualized range.
/// </summary>
public readonly record struct LockRangeDuringZoom(bool LockRange) : ILoggable<LockRangeDuringZoom>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.LockRangeDuringZoom");

    public static IArrowArray ToArrow(ReadOnlySpan<LockRangeDuringZoom> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.LockRange);
        return builder.Build();
    }
}
