// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// If playing, whether and how the playback time should loop.
/// </summary>
public enum LoopModeValue : byte
{
    Invalid = 0,
    Off,
    Selection,
    All,
}

/// <summary>
/// If playing, whether and how the playback time should loop.
/// </summary>
public readonly record struct LoopMode(LoopModeValue Value) : ILoggable<LoopMode>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.LoopMode");

    public static IArrowArray ToArrow(ReadOnlySpan<LoopMode> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
