// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Name of the map provider to be used in Map views.
/// </summary>
public enum MapProviderValue : byte
{
    Invalid = 0,
    OpenStreetMap,
    MapboxStreets,
    MapboxDark,
    MapboxSatellite,
    MapboxLight,
}

/// <summary>
/// Name of the map provider to be used in Map views.
/// </summary>
public readonly record struct MapProvider(MapProviderValue Value) : ILoggable<MapProvider>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.MapProvider");

    public static IArrowArray ToArrow(ReadOnlySpan<MapProvider> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
