// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Distance to the near clip plane used for `Spatial2DView`.
/// </summary>
public readonly record struct NearClipPlane(float NearClipPlaneValue) : ILoggable<NearClipPlane>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.NearClipPlane");

    public static IArrowArray ToArrow(ReadOnlySpan<NearClipPlane> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.NearClipPlaneValue);
        return builder.Build();
    }
}
