// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Tri-state for panel controls.
/// </summary>
public enum PanelStateValue : byte
{
    Invalid = 0,
    Hidden,
    Collapsed,
    Expanded,
}

/// <summary>
/// Tri-state for panel controls.
/// </summary>
public readonly record struct PanelState(PanelStateValue Value) : ILoggable<PanelState>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.PanelState");

    public static IArrowArray ToArrow(ReadOnlySpan<PanelState> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
