// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A playback speed which determines how fast time progresses.
/// </summary>
public readonly record struct PlaybackSpeed(double Speed) : ILoggable<PlaybackSpeed>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.PlaybackSpeed");

    public static IArrowArray ToArrow(ReadOnlySpan<PlaybackSpeed> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Speed);
        return builder.Build();
    }
}
