// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The current play state.
/// </summary>
public enum PlayStateValue : byte
{
    Invalid = 0,
    Paused,
    Playing,
    Following,
}

/// <summary>
/// The current play state.
/// </summary>
public readonly record struct PlayState(PlayStateValue Value) : ILoggable<PlayState>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.PlayState");

    public static IArrowArray ToArrow(ReadOnlySpan<PlayState> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
