// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// An individual query expression used to filter a set of [datatypes.EntityPath]s.
/// 
/// Each expression is either an inclusion or an exclusion expression.
/// Inclusions start with an optional `+` and exclusions must start with a `-`.
/// 
/// Multiple expressions are combined together as part of [archetypes.ViewContents].
/// 
/// The `/**` suffix matches the whole subtree, i.e. self and any child, recursively
/// (`/world/**` matches both `/world` and `/world/car/driver`).
/// Other uses of `*` are not (yet) supported.
/// </summary>
public readonly record struct QueryExpression(Utf8 Filter) : ILoggable<QueryExpression>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.QueryExpression");

    public static IArrowArray ToArrow(ReadOnlySpan<QueryExpression> data)
    {
        var inner = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Filter;
        return Utf8.ToArrow(inner);
    }
}
