// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The container that sits at the root of a viewport.
/// </summary>
public readonly record struct RootContainer(Uuid Id) : ILoggable<RootContainer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.RootContainer");

    public static IArrowArray ToArrow(ReadOnlySpan<RootContainer> data)
    {
        var inner = new Uuid[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Id;
        return Uuid.ToArrow(inner);
    }
}
