// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

public readonly record struct SelectedColumns(Datatypes.SelectedColumns SelectedColumnsValue) : ILoggable<SelectedColumns>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.SelectedColumns");

    public static IArrowArray ToArrow(ReadOnlySpan<SelectedColumns> data)
    {
        var inner = new Datatypes.SelectedColumns[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].SelectedColumnsValue;
        return Datatypes.SelectedColumns.ToArrow(inner);
    }
}
