// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A text log column
/// </summary>
public readonly record struct TextLogColumn(global::Rerun.Net.Blueprint.Datatypes.TextLogColumn TextLogColumnValue) : ILoggable<TextLogColumn>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.TextLogColumn");

    public static IArrowArray ToArrow(ReadOnlySpan<TextLogColumn> data)
    {
        var inner = new global::Rerun.Net.Blueprint.Datatypes.TextLogColumn[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].TextLogColumnValue;
        return global::Rerun.Net.Blueprint.Datatypes.TextLogColumn.ToArrow(inner);
    }
}
