// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A timeline column in a text log table.
/// </summary>
public readonly record struct TimelineColumn(Datatypes.TimelineColumn TimelineColumnValue) : ILoggable<TimelineColumn>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.TimelineColumn");

    public static IArrowArray ToArrow(ReadOnlySpan<TimelineColumn> data)
    {
        var inner = new Datatypes.TimelineColumn[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].TimelineColumnValue;
        return Datatypes.TimelineColumn.ToArrow(inner);
    }
}
