// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A reference to a time.
/// </summary>
public readonly record struct TimeInt(global::Rerun.Net.Datatypes.TimeInt Time) : ILoggable<TimeInt>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.TimeInt");

    public static IArrowArray ToArrow(ReadOnlySpan<TimeInt> data)
    {
        var inner = new global::Rerun.Net.Datatypes.TimeInt[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Time;
        return global::Rerun.Net.Datatypes.TimeInt.ToArrow(inner);
    }
}
