// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A time range on an unspecified timeline using either relative or absolute boundaries.
/// </summary>
public readonly record struct TimeRange(global::Rerun.Net.Datatypes.TimeRange TimeRangeValue) : ILoggable<TimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.TimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<TimeRange> data)
    {
        var inner = new global::Rerun.Net.Datatypes.TimeRange[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].TimeRangeValue;
        return global::Rerun.Net.Datatypes.TimeRange.ToArrow(inner);
    }
}
