// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A timeline identified by its name.
/// </summary>
public readonly record struct TimelineName(global::Rerun.Net.Datatypes.Utf8 Value) : ILoggable<TimelineName>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.TimelineName");

    public static IArrowArray ToArrow(ReadOnlySpan<TimelineName> data)
    {
        var inner = new global::Rerun.Net.Datatypes.Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return global::Rerun.Net.Datatypes.Utf8.ToArrow(inner);
    }
}
