// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Determines whether an image or texture should be scaled to fit the viewport.
/// </summary>
public enum ViewFitValue : byte
{
    Invalid = 0,
    Original,
    Fill,
    FillKeepAspectRatio,
}

/// <summary>
/// Determines whether an image or texture should be scaled to fit the viewport.
/// </summary>
public readonly record struct ViewFit(ViewFitValue Value) : ILoggable<ViewFit>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ViewFit");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewFit> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Value);
        return builder.Build();
    }
}
