// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Hash of a viewer recommendation.
/// 
/// The formation of this hash is considered an internal implementation detail of the viewer.
/// </summary>
public readonly record struct ViewerRecommendationHash(ulong Value) : ILoggable<ViewerRecommendationHash>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ViewerRecommendationHash");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewerRecommendationHash> data)
    {
        var builder = new UInt64Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
