// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Whether a view is maximized.
/// </summary>
public readonly record struct ViewMaximized(Uuid ViewId) : ILoggable<ViewMaximized>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ViewMaximized");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewMaximized> data)
    {
        var inner = new Uuid[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].ViewId;
        return Uuid.ToArrow(inner);
    }
}
