// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The origin of a view.
/// </summary>
public readonly record struct ViewOrigin(global::Rerun.Net.Datatypes.EntityPath Value) : ILoggable<ViewOrigin>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ViewOrigin");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewOrigin> data)
    {
        var inner = new global::Rerun.Net.Datatypes.EntityPath[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return global::Rerun.Net.Datatypes.EntityPath.ToArrow(inner);
    }
}
