// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The range of values on a given timeline that will be included in a view's query.
/// 
/// Refer to `VisibleTimeRanges` archetype for more information.
/// </summary>
public readonly record struct VisibleTimeRange(global::Rerun.Net.Datatypes.VisibleTimeRange Value) : ILoggable<VisibleTimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.VisibleTimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<VisibleTimeRange> data)
    {
        var inner = new global::Rerun.Net.Datatypes.VisibleTimeRange[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Value;
        return global::Rerun.Net.Datatypes.VisibleTimeRange.ToArrow(inner);
    }
}
