// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Associates components of an entity to components of a visualizer.
/// </summary>
public readonly record struct VisualizerComponentMapping(global::Rerun.Net.Blueprint.Datatypes.VisualizerComponentMapping Mapping) : ILoggable<VisualizerComponentMapping>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.VisualizerComponentMapping");

    public static IArrowArray ToArrow(ReadOnlySpan<VisualizerComponentMapping> data)
    {
        var inner = new global::Rerun.Net.Blueprint.Datatypes.VisualizerComponentMapping[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Mapping;
        return global::Rerun.Net.Blueprint.Datatypes.VisualizerComponentMapping.ToArrow(inner);
    }
}
