// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// Visual bounds in 2D space used for `Spatial2DView`.
/// </summary>
public readonly record struct VisualBounds2D(Range2D Range2d) : ILoggable<VisualBounds2D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.VisualBounds2D");

    public static IArrowArray ToArrow(ReadOnlySpan<VisualBounds2D> data)
    {
        var inner = new Range2D[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Range2d;
        return Range2D.ToArrow(inner);
    }
}
