// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// ID for a visualizer instruction.
/// 
/// IDs are only guaranteed to be unique in the scope of a view.
/// For details see [archetypes.ActiveVisualizers].
/// </summary>
public readonly record struct VisualizerInstructionId(Uuid Visualizer) : ILoggable<VisualizerInstructionId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.VisualizerInstructionId");

    public static IArrowArray ToArrow(ReadOnlySpan<VisualizerInstructionId> data)
    {
        var inner = new Uuid[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].Visualizer;
        return Uuid.ToArrow(inner);
    }
}
