// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// The type of the visualizer.
/// </summary>
public readonly record struct VisualizerType(Utf8 VisualizerTypeValue) : ILoggable<VisualizerType>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.VisualizerType");

    public static IArrowArray ToArrow(ReadOnlySpan<VisualizerType> data)
    {
        var inner = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++)
            inner[i] = data[i].VisualizerTypeValue;
        return Utf8.ToArrow(inner);
    }
}
