// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Rerun.Net.Datatypes;

using Rerun.Net.Datatypes;
using Rerun.Net.Components;

namespace Rerun.Net.Blueprint.Components;

/// <summary>
/// A zoom level determines how much of the world is visible on a map.
/// </summary>
public readonly record struct ZoomLevel(double Zoom) : ILoggable<ZoomLevel>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.blueprint.components.ZoomLevel");

    public static IArrowArray ToArrow(ReadOnlySpan<ZoomLevel> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Zoom);
        return builder.Build();
    }
}
