// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Two [datatypes.TimeInt] describing a range of time.
/// </summary>
public readonly record struct AbsoluteTimeRange(TimeInt Min, TimeInt Max) : ILoggable<AbsoluteTimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.AbsoluteTimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<AbsoluteTimeRange> data)
    {
        throw new NotImplementedException("Complex field: min");
    }
}
