// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Angle in radians.
/// </summary>
public readonly record struct Angle(float Radians) : ILoggable<Angle>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Angle");

    public static IArrowArray ToArrow(ReadOnlySpan<Angle> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Radians);
        return builder.Build();
    }
}
