// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Annotation info annotating a class id or key-point id.
/// 
/// Color and label will be used to annotate entities/keypoints which reference the id.
/// The id refers either to a class or key-point id
/// </summary>
public readonly partial record struct AnnotationInfo(ushort Id, Utf8 Label, Rgba32 Color) : ILoggable<AnnotationInfo>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.AnnotationInfo");

    public static IArrowArray ToArrow(ReadOnlySpan<AnnotationInfo> data)
    {
        var idBuilder = new UInt16Array.Builder();
        foreach (var v in data) idBuilder.Append(v.Id);
        var idArray = (IArrowArray)idBuilder.Build();
        var labelTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) labelTmp[i] = data[i].Label;
        var labelArray = Utf8.ToArrow(labelTmp);
        var colorTmp = new Rgba32[data.Length];
        for (var i = 0; i < data.Length; i++) colorTmp[i] = data[i].Color;
        var colorArray = Rgba32.ToArrow(colorTmp);
        var fields = new Apache.Arrow.Field[] {
            new("id", idArray.Data.DataType, false),
            new("label", labelArray.Data.DataType, false),
            new("color", colorArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { idArray, labelArray, colorArray }, ArrowBuffer.Empty);
    }
}
