// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A binary blob of data.
/// </summary>
public readonly record struct Blob(byte[] Data) : ILoggable<Blob>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Blob");

    public static IArrowArray ToArrow(ReadOnlySpan<Blob> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = ubyte } }
    }
}
