// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A single boolean.
/// </summary>
public readonly record struct Bool(bool Value) : ILoggable<Bool>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Bool");

    public static IArrowArray ToArrow(ReadOnlySpan<Bool> data)
    {
        var builder = new BooleanArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
