// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A pair representing a channel ID and its associated message count.
/// </summary>
public readonly partial record struct ChannelCountPair(ushort ChannelId, ulong MessageCount) : ILoggable<ChannelCountPair>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ChannelCountPair");

    public static IArrowArray ToArrow(ReadOnlySpan<ChannelCountPair> data)
    {
        var channel_idBuilder = new UInt16Array.Builder();
        foreach (var v in data) channel_idBuilder.Append(v.ChannelId);
        var channel_idArray = (IArrowArray)channel_idBuilder.Build();
        var message_countBuilder = new UInt64Array.Builder();
        foreach (var v in data) message_countBuilder.Append(v.MessageCount);
        var message_countArray = (IArrowArray)message_countBuilder.Build();
        var fields = new Apache.Arrow.Field[] {
            new("channel_id", channel_idArray.Data.DataType, false),
            new("message_count", message_countArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { channel_idArray, message_countArray }, ArrowBuffer.Empty);
    }
}
