// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

namespace Rerun.Net.Datatypes;

/// <summary>
/// The innermost datatype of an image.
/// 
/// How individual color channel components are encoded.
/// </summary>
public enum ChannelDatatype : byte
{
    Invalid = 0,
    U8 = 6,
    I8 = 7,
    U16 = 8,
    I16 = 9,
    U32 = 10,
    I32 = 11,
    U64 = 12,
    I64 = 13,
    F16 = 33,
    F32 = 34,
    F64 = 35,
}
