// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// The description of a semantic Class.
/// 
/// If an entity is annotated with a corresponding [components.ClassId], Rerun will use
/// the attached [datatypes.AnnotationInfo] to derive labels and colors.
/// 
/// Keypoints within an annotation class can similarly be annotated with a
/// [components.KeypointId] in which case we should defer to the label and color for the
/// [datatypes.AnnotationInfo] specifically associated with the Keypoint.
/// 
/// Keypoints within the class can also be decorated with skeletal edges.
/// Keypoint-connections are pairs of [components.KeypointId]s. If an edge is
/// defined, and both keypoints exist within the instance of the class, then the
/// keypoints should be connected with an edge. The edge should be labeled and
/// colored as described by the class's [datatypes.AnnotationInfo].
/// 
/// </summary>
public readonly partial record struct ClassDescription(AnnotationInfo Info, AnnotationInfo[] KeypointAnnotations, KeypointPair[] KeypointConnections) : ILoggable<ClassDescription>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ClassDescription");

    public static IArrowArray ToArrow(ReadOnlySpan<ClassDescription> data)
    {
        var infoTmp = new AnnotationInfo[data.Length];
        for (var i = 0; i < data.Length; i++) infoTmp[i] = data[i].Info;
        var infoArray = AnnotationInfo.ToArrow(infoTmp);
        IArrowArray keypoint_annotationsArray = null!; // unsupported field type
        IArrowArray keypoint_connectionsArray = null!; // unsupported field type
        var fields = new Apache.Arrow.Field[] {
            new("info", infoArray.Data.DataType, false),
            new("keypoint_annotations", keypoint_annotationsArray.Data.DataType, false),
            new("keypoint_connections", keypoint_connectionsArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { infoArray, keypoint_annotationsArray, keypoint_connectionsArray }, ArrowBuffer.Empty);
    }
}
