// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 16-bit ID representing a type of semantic class.
/// 
/// </summary>
public readonly record struct ClassId(ushort Id) : ILoggable<ClassId>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ClassId");

    public static IArrowArray ToArrow(ReadOnlySpan<ClassId> data)
    {
        var builder = new UInt16Array.Builder();
        foreach (var v in data)
            builder.Append(v.Id);
        return builder.Build();
    }
}
