// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A helper type for mapping [datatypes.ClassId]s to class descriptions.
/// 
/// This is internal to [components.AnnotationContext].
/// </summary>
public readonly partial record struct ClassDescriptionMapElem(ClassId ClassId, ClassDescription ClassDescription) : ILoggable<ClassDescriptionMapElem>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ClassDescriptionMapElem");

    public static IArrowArray ToArrow(ReadOnlySpan<ClassDescriptionMapElem> data)
    {
        var class_idTmp = new ClassId[data.Length];
        for (var i = 0; i < data.Length; i++) class_idTmp[i] = data[i].ClassId;
        var class_idArray = ClassId.ToArrow(class_idTmp);
        var class_descriptionTmp = new ClassDescription[data.Length];
        for (var i = 0; i < data.Length; i++) class_descriptionTmp[i] = data[i].ClassDescription;
        var class_descriptionArray = ClassDescription.ToArrow(class_descriptionTmp);
        var fields = new Apache.Arrow.Field[] {
            new("class_id", class_idArray.Data.DataType, false),
            new("class_description", class_descriptionArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { class_idArray, class_descriptionArray }, ArrowBuffer.Empty);
    }
}
