// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

namespace Rerun.Net.Datatypes;

/// <summary>
/// Specified what color components are present in an [archetypes.Image].
/// 
/// This combined with [datatypes.ChannelDatatype] determines the pixel format of an image.
/// </summary>
public enum ColorModel : byte
{
    Invalid = 0,
    L = 1,
    RGB = 2,
    RGBA = 3,
    BGR,
    BGRA,
}
