// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct F16Buffer(ushort[] Data) : ILoggable<F16Buffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.F16Buffer");

    public static IArrowArray ToArrow(ReadOnlySpan<F16Buffer> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = ushort } }
    }
}
