// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct F32Buffer(float[] Data) : ILoggable<F32Buffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.F32Buffer");

    public static IArrowArray ToArrow(ReadOnlySpan<F32Buffer> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = float } }
    }
}
