// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A double-precision 64-bit IEEE 754 floating point number.
/// </summary>
public readonly record struct Float64(double Value) : ILoggable<Float64>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Float64");

    public static IArrowArray ToArrow(ReadOnlySpan<Float64> data)
    {
        var builder = new DoubleArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
