// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A single-precision 32-bit IEEE 754 floating point number.
/// </summary>
public readonly record struct Float32(float Value) : ILoggable<Float32>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Float32");

    public static IArrowArray ToArrow(ReadOnlySpan<Float32> data)
    {
        var builder = new FloatArray.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
