// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct I8Buffer(sbyte[] Data) : ILoggable<I8Buffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.I8Buffer");

    public static IArrowArray ToArrow(ReadOnlySpan<I8Buffer> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = byte } }
    }
}
