// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// The metadata describing the contents of a [components.ImageBuffer].
/// </summary>
public readonly record struct ImageFormat(uint Width, uint Height, PixelFormat PixelFormat, ColorModel ColorModel, ChannelDatatype ChannelDatatype) : ILoggable<ImageFormat>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ImageFormat");

    public static IArrowArray ToArrow(ReadOnlySpan<ImageFormat> data)
    {
        var widthBuilder = new UInt32Array.Builder();
        foreach (var v in data) widthBuilder.Append(v.Width);
        var heightBuilder = new UInt32Array.Builder();
        foreach (var v in data) heightBuilder.Append(v.Height);
        throw new NotImplementedException("Complex field: pixel_format");
    }
}
