// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A connection between two [datatypes.KeypointId]s.
/// </summary>
public readonly partial record struct KeypointPair(KeypointId Keypoint0, KeypointId Keypoint1) : ILoggable<KeypointPair>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.KeypointPair");

    public static IArrowArray ToArrow(ReadOnlySpan<KeypointPair> data)
    {
        var keypoint0Tmp = new KeypointId[data.Length];
        for (var i = 0; i < data.Length; i++) keypoint0Tmp[i] = data[i].Keypoint0;
        var keypoint0Array = KeypointId.ToArrow(keypoint0Tmp);
        var keypoint1Tmp = new KeypointId[data.Length];
        for (var i = 0; i < data.Length; i++) keypoint1Tmp[i] = data[i].Keypoint1;
        var keypoint1Array = KeypointId.ToArrow(keypoint1Tmp);
        var fields = new Apache.Arrow.Field[] {
            new("keypoint0", keypoint0Array.Data.DataType, false),
            new("keypoint1", keypoint1Array.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { keypoint0Array, keypoint1Array }, ArrowBuffer.Empty);
    }
}
