// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 3x3 Matrix.
/// 
/// Matrices in Rerun are stored as flat list of coefficients in column-major order:
/// ```text
/// column 0       column 1       column 2
/// -------------------------------------------------
/// row 0 | flat_columns[0] flat_columns[3] flat_columns[6]
/// row 1 | flat_columns[1] flat_columns[4] flat_columns[7]
/// row 2 | flat_columns[2] flat_columns[5] flat_columns[8]
/// ```
/// 
/// </summary>
public readonly record struct Mat3x3(float[] FlatColumns) : ILoggable<Mat3x3>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Mat3x3");

    public static IArrowArray ToArrow(ReadOnlySpan<Mat3x3> data)
    {
        var valuesBuilder = new FloatArray.Builder();
        foreach (var v in data)
            foreach (var elem in v.FlatColumns)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new FloatType(), false), 9);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
