// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 4x4 Matrix.
/// 
/// Matrices in Rerun are stored as flat list of coefficients in column-major order:
/// ```text
/// column 0         column 1         column 2         column 3
/// --------------------------------------------------------------------
/// row 0 | flat_columns[0]  flat_columns[4]  flat_columns[8]  flat_columns[12]
/// row 1 | flat_columns[1]  flat_columns[5]  flat_columns[9]  flat_columns[13]
/// row 2 | flat_columns[2]  flat_columns[6]  flat_columns[10] flat_columns[14]
/// row 3 | flat_columns[3]  flat_columns[7]  flat_columns[11] flat_columns[15]
/// ```
/// 
/// </summary>
public readonly record struct Mat4x4(float[] FlatColumns) : ILoggable<Mat4x4>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Mat4x4");

    public static IArrowArray ToArrow(ReadOnlySpan<Mat4x4> data)
    {
        var valuesBuilder = new FloatArray.Builder();
        foreach (var v in data)
            foreach (var elem in v.FlatColumns)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new FloatType(), false), 16);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
