// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

namespace Rerun.Net.Datatypes;

/// <summary>
/// Specifieds a particular format of an [archetypes.Image].
/// 
/// Most images can be described by a [datatypes.ColorModel] and a [datatypes.ChannelDatatype],
/// e.g. `RGB` and `U8` respectively.
/// 
/// However, some image formats has chroma downsampling and/or
/// use differing number of bits per channel, and that is what this [datatypes.PixelFormat] is for.
/// 
/// All these formats support random access.
/// 
/// For more compressed image formats, see [archetypes.EncodedImage].
/// </summary>
public enum PixelFormat : byte
{
    Invalid = 0,
    Y_U_V24_LimitedRange = 39,
    Y_U_V24_FullRange = 40,
    Y_U_V16_LimitedRange,
    Y_U_V16_FullRange,
    Y_U_V12_LimitedRange = 20,
    Y_U_V12_FullRange = 44,
    Y8_LimitedRange = 41,
    Y8_FullRange = 30,
    NV12,
    YUY2 = 27,
}
