// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// An infinite 3D plane represented by a unit normal vector and a distance.
/// 
/// Any point P on the plane fulfills the equation `dot(xyz, P) - d = 0`,
/// where `xyz` is the plane's normal and `d` the distance of the plane from the origin.
/// This representation is also known as the Hesse normal form.
/// 
/// Note: although the normal will be passed through to the
/// datastore as provided, when used in the Viewer, planes will always be normalized.
/// I.e. the plane with xyz = (2, 0, 0), d = 1 is equivalent to xyz = (1, 0, 0), d = 0.5
/// </summary>
public readonly record struct Plane3D(float[] Xyzd) : ILoggable<Plane3D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Plane3D");

    public static IArrowArray ToArrow(ReadOnlySpan<Plane3D> data)
    {
        var valuesBuilder = new FloatArray.Builder();
        foreach (var v in data)
            foreach (var elem in v.Xyzd)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new FloatType(), false), 4);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
