// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A Quaternion represented by 4 real numbers.
/// 
/// Note: although the x,y,z,w components of the quaternion will be passed through to the
/// datastore as provided, when used in the Viewer Quaternions will always be normalized.
/// </summary>
public readonly record struct Quaternion(float[] Xyzw) : ILoggable<Quaternion>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Quaternion");

    public static IArrowArray ToArrow(ReadOnlySpan<Quaternion> data)
    {
        var valuesBuilder = new FloatArray.Builder();
        foreach (var v in data)
            foreach (var elem in v.Xyzw)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new FloatType(), false), 4);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
