// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 1D range, specifying a lower and upper bound.
/// </summary>
public readonly record struct Range1D(double[] Range) : ILoggable<Range1D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Range1D");

    public static IArrowArray ToArrow(ReadOnlySpan<Range1D> data)
    {
        var valuesBuilder = new DoubleArray.Builder();
        foreach (var v in data)
            foreach (var elem in v.Range)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new DoubleType(), false), 2);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
