// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// An Axis-Aligned Bounding Box in 2D space, implemented as the minimum and maximum corners.
/// </summary>
public readonly record struct Range2D(Range1D XRange, Range1D YRange) : ILoggable<Range2D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Range2D");

    public static IArrowArray ToArrow(ReadOnlySpan<Range2D> data)
    {
        throw new NotImplementedException("Complex field: x_range");
    }
}
