// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// An RGBA color with unmultiplied/separate alpha, in sRGB gamma space with linear alpha.
/// 
/// The color is stored as a 32-bit integer, where the most significant
/// byte is `R` and the least significant byte is `A`.
/// 
/// </summary>
public readonly record struct Rgba32(uint Rgba) : ILoggable<Rgba32>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Rgba32");

    public static IArrowArray ToArrow(ReadOnlySpan<Rgba32> data)
    {
        var builder = new UInt32Array.Builder();
        foreach (var v in data)
            builder.Append(v.Rgba);
        return builder.Build();
    }
}
