// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// 3D rotation represented by a rotation around a given axis.
/// </summary>
public readonly partial record struct RotationAxisAngle(Vec3D Axis, Angle Angle) : ILoggable<RotationAxisAngle>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.RotationAxisAngle");

    public static IArrowArray ToArrow(ReadOnlySpan<RotationAxisAngle> data)
    {
        var axisTmp = new Vec3D[data.Length];
        for (var i = 0; i < data.Length; i++) axisTmp[i] = data[i].Axis;
        var axisArray = Vec3D.ToArrow(axisTmp);
        var angleTmp = new Angle[data.Length];
        for (var i = 0; i < data.Length; i++) angleTmp[i] = data[i].Angle;
        var angleArray = Angle.ToArrow(angleTmp);
        var fields = new Apache.Arrow.Field[] {
            new("axis", axisArray.Data.DataType, false),
            new("angle", angleArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { axisArray, angleArray }, ArrowBuffer.Empty);
    }
}
