// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Selection of a single tensor dimension.
/// </summary>
public readonly record struct TensorDimensionSelection(uint Dimension, bool Invert) : ILoggable<TensorDimensionSelection>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TensorDimensionSelection");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorDimensionSelection> data)
    {
        var dimensionBuilder = new UInt32Array.Builder();
        foreach (var v in data) dimensionBuilder.Append(v.Dimension);
        var invertBuilder = new BooleanArray.Builder();
        foreach (var v in data) invertBuilder.Append(v.Invert);
        var fields = new Apache.Arrow.Field[] {
            new Apache.Arrow.Field("dimension", new UInt32Type(), false),
            new Apache.Arrow.Field("invert", new BooleanType(), false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { dimensionBuilder.Build(), invertBuilder.Build() }, ArrowBuffer.Empty);
    }
}
