// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// An N-dimensional array of numbers.
/// 
/// The number of dimensions and their respective lengths is specified by the `shape` field.
/// The dimensions are ordered from outermost to innermost. For example, in the common case of
/// a 2D RGB Image, the shape would be `[height, width, channel]`.
/// 
/// These dimensions are combined with an index to look up values from the `buffer` field,
/// which stores a contiguous array of typed values.
/// 
/// </summary>
public readonly partial record struct TensorData(ulong[] Shape, string[] Names, TensorBuffer Buffer) : ILoggable<TensorData>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TensorData");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorData> data)
    {
        IArrowArray shapeArray = null!; // unsupported field type
        IArrowArray namesArray = null!; // unsupported field type
        var bufferTmp = new TensorBuffer[data.Length];
        for (var i = 0; i < data.Length; i++) bufferTmp[i] = data[i].Buffer;
        var bufferArray = TensorBuffer.ToArrow(bufferTmp);
        var fields = new Apache.Arrow.Field[] {
            new("shape", shapeArray.Data.DataType, false),
            new("names", namesArray.Data.DataType, false),
            new("buffer", bufferArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { shapeArray, namesArray, bufferArray }, ArrowBuffer.Empty);
    }
}
