// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Indexing a specific tensor dimension.
/// 
/// Selecting `dimension=2` and `index=42` is similar to doing `tensor[:, :, 42, :, :, …]` in numpy.
/// </summary>
public readonly record struct TensorDimensionIndexSelection(uint Dimension, ulong Index) : ILoggable<TensorDimensionIndexSelection>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TensorDimensionIndexSelection");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorDimensionIndexSelection> data)
    {
        var dimensionBuilder = new UInt32Array.Builder();
        foreach (var v in data) dimensionBuilder.Append(v.Dimension);
        var indexBuilder = new UInt64Array.Builder();
        foreach (var v in data) indexBuilder.Append(v.Index);
        var fields = new Apache.Arrow.Field[] {
            new Apache.Arrow.Field("dimension", new UInt32Type(), false),
            new Apache.Arrow.Field("index", new UInt64Type(), false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { dimensionBuilder.Build(), indexBuilder.Build() }, ArrowBuffer.Empty);
    }
}
