// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public enum TensorBufferTag : byte
{
    U8 = 0,
    U16 = 1,
    U32 = 2,
    U64 = 3,
    I8 = 4,
    I16 = 5,
    I32 = 6,
    I64 = 7,
    F16 = 8,
    F32 = 9,
    F64 = 10,
}

/// <summary>
/// The underlying storage for [archetypes.Tensor].
/// 
/// Tensor elements are stored in a contiguous buffer of a single type.
/// </summary>
public readonly record struct TensorBuffer(TensorBufferTag Tag, object? Data) : ILoggable<TensorBuffer>
{
    /// <summary>
    /// 8bit unsigned integer.
    /// </summary>
    public static TensorBuffer U8(object? data = null) => new(TensorBufferTag.U8, data);
    /// <summary>
    /// 16bit unsigned integer.
    /// </summary>
    public static TensorBuffer U16(object? data = null) => new(TensorBufferTag.U16, data);
    /// <summary>
    /// 32bit unsigned integer.
    /// </summary>
    public static TensorBuffer U32(object? data = null) => new(TensorBufferTag.U32, data);
    /// <summary>
    /// 64bit unsigned integer.
    /// </summary>
    public static TensorBuffer U64(object? data = null) => new(TensorBufferTag.U64, data);
    /// <summary>
    /// 8bit signed integer.
    /// </summary>
    public static TensorBuffer I8(object? data = null) => new(TensorBufferTag.I8, data);
    /// <summary>
    /// 16bit signed integer.
    /// </summary>
    public static TensorBuffer I16(object? data = null) => new(TensorBufferTag.I16, data);
    /// <summary>
    /// 32bit signed integer.
    /// </summary>
    public static TensorBuffer I32(object? data = null) => new(TensorBufferTag.I32, data);
    /// <summary>
    /// 64bit signed integer.
    /// </summary>
    public static TensorBuffer I64(object? data = null) => new(TensorBufferTag.I64, data);
    /// <summary>
    /// 16bit IEEE-754 floating point, also known as `half`.
    /// </summary>
    public static TensorBuffer F16(object? data = null) => new(TensorBufferTag.F16, data);
    /// <summary>
    /// 32bit IEEE-754 floating point, also known as `float` or `single`.
    /// </summary>
    public static TensorBuffer F32(object? data = null) => new(TensorBufferTag.F32, data);
    /// <summary>
    /// 64bit IEEE-754 floating point, also known as `double`.
    /// </summary>
    public static TensorBuffer F64(object? data = null) => new(TensorBufferTag.F64, data);

    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TensorBuffer");

    public static IArrowArray ToArrow(ReadOnlySpan<TensorBuffer> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Tag);
        return builder.Build();
    }
}
