// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 64-bit number describing either nanoseconds OR sequence numbers.
/// </summary>
public readonly record struct TimeInt(long Value) : ILoggable<TimeInt>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TimeInt");

    public static IArrowArray ToArrow(ReadOnlySpan<TimeInt> data)
    {
        var builder = new Int64Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
