// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

public readonly partial record struct TimeRange(TimeRangeBoundary Start, TimeRangeBoundary End) : ILoggable<TimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<TimeRange> data)
    {
        var startTmp = new TimeRangeBoundary[data.Length];
        for (var i = 0; i < data.Length; i++) startTmp[i] = data[i].Start;
        var startArray = TimeRangeBoundary.ToArrow(startTmp);
        var endTmp = new TimeRangeBoundary[data.Length];
        for (var i = 0; i < data.Length; i++) endTmp[i] = data[i].End;
        var endArray = TimeRangeBoundary.ToArrow(endTmp);
        var fields = new Apache.Arrow.Field[] {
            new("start", startArray.Data.DataType, false),
            new("end", endArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { startArray, endArray }, ArrowBuffer.Empty);
    }
}
