// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public enum TimeRangeBoundaryTag : byte
{
    CursorRelative = 0,
    Absolute = 1,
    Infinite = 2,
}

/// <summary>
/// Left or right boundary of a time range.
/// </summary>
public readonly record struct TimeRangeBoundary(TimeRangeBoundaryTag Tag, object? Data) : ILoggable<TimeRangeBoundary>
{
    /// <summary>
    /// Boundary is a value relative to the time cursor.
    /// </summary>
    public static TimeRangeBoundary CursorRelative(object? data = null) => new(TimeRangeBoundaryTag.CursorRelative, data);
    /// <summary>
    /// Boundary is an absolute value.
    /// </summary>
    public static TimeRangeBoundary Absolute(object? data = null) => new(TimeRangeBoundaryTag.Absolute, data);
    /// <summary>
    /// The boundary extends to infinity.
    /// </summary>
    public static TimeRangeBoundary Infinite(object? data = null) => new(TimeRangeBoundaryTag.Infinite, data);

    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.TimeRangeBoundary");

    public static IArrowArray ToArrow(ReadOnlySpan<TimeRangeBoundary> data)
    {
        var builder = new UInt8Array.Builder();
        foreach (var v in data)
            builder.Append((byte)v.Tag);
        return builder.Build();
    }
}
