// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct U32Buffer(uint[] Data) : ILoggable<U32Buffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.U32Buffer");

    public static IArrowArray ToArrow(ReadOnlySpan<U32Buffer> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = uint } }
    }
}
