// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct U8Buffer(byte[] Data) : ILoggable<U8Buffer>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.U8Buffer");

    public static IArrowArray ToArrow(ReadOnlySpan<U8Buffer> data)
    {
        throw new NotImplementedException(); // FbsArray { ElementType = FbsPrimitive { TypeName = ubyte } }
    }
}
