// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 32bit unsigned integer.
/// </summary>
public readonly record struct UInt32(uint Value) : ILoggable<UInt32>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.UInt32");

    public static IArrowArray ToArrow(ReadOnlySpan<UInt32> data)
    {
        var builder = new UInt32Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
