// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 16bit unsigned integer.
/// </summary>
public readonly record struct UInt16(ushort Value) : ILoggable<UInt16>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.UInt16");

    public static IArrowArray ToArrow(ReadOnlySpan<UInt16> data)
    {
        var builder = new UInt16Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
