// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 64bit unsigned integer.
/// </summary>
public readonly record struct UInt64(ulong Value) : ILoggable<UInt64>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.UInt64");

    public static IArrowArray ToArrow(ReadOnlySpan<UInt64> data)
    {
        var builder = new UInt64Array.Builder();
        foreach (var v in data)
            builder.Append(v.Value);
        return builder.Build();
    }
}
