// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Stores a tuple of UTF-8 strings.
/// </summary>
public readonly partial record struct Utf8Pair(Utf8 First, Utf8 Second) : ILoggable<Utf8Pair>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Utf8Pair");

    public static IArrowArray ToArrow(ReadOnlySpan<Utf8Pair> data)
    {
        var firstTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) firstTmp[i] = data[i].First;
        var firstArray = Utf8.ToArrow(firstTmp);
        var secondTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) secondTmp[i] = data[i].Second;
        var secondArray = Utf8.ToArrow(secondTmp);
        var fields = new Apache.Arrow.Field[] {
            new("first", firstArray.Data.DataType, false),
            new("second", secondArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { firstArray, secondArray }, ArrowBuffer.Empty);
    }
}
