// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

public readonly record struct Utf8(string Value) : ILoggable<Utf8>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Utf8");

    public static IArrowArray ToArrow(ReadOnlySpan<Utf8> data)
    {
        var enc = System.Text.Encoding.UTF8;
        var offsets = new int[data.Length + 1];
        var total = 0;
        for (var i = 0; i < data.Length; i++) { offsets[i] = total; total += enc.GetByteCount(data[i].Value ?? ""); }
        offsets[data.Length] = total;
        var valueBytes = new byte[total];
        var pos = 0;
        for (var i = 0; i < data.Length; i++) { var s = data[i].Value ?? ""; enc.GetBytes(s, 0, s.Length, valueBytes, pos); pos += enc.GetByteCount(s); }
        var offsetBytes = new byte[offsets.Length * 4];
        System.Buffer.BlockCopy(offsets, 0, offsetBytes, 0, offsetBytes.Length);
        var arrayData = new ArrayData(StringType.Default, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty, new ArrowBuffer(offsetBytes), new ArrowBuffer(valueBytes) });
        return new StringArray(arrayData);
    }
}
