// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A 16-byte UUID.
/// </summary>
public readonly record struct Uuid(byte[] Bytes) : ILoggable<Uuid>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.Uuid");

    public static IArrowArray ToArrow(ReadOnlySpan<Uuid> data)
    {
        var valuesBuilder = new UInt8Array.Builder();
        foreach (var v in data)
            foreach (var elem in v.Bytes)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new UInt8Type(), false), 16);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
