// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// A uint vector in 4D space.
/// </summary>
public readonly record struct UVec4D(uint[] Xyzw) : ILoggable<UVec4D>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.UVec4D");

    public static IArrowArray ToArrow(ReadOnlySpan<UVec4D> data)
    {
        var valuesBuilder = new UInt32Array.Builder();
        foreach (var v in data)
            foreach (var elem in v.Xyzw)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new UInt32Type(), false), 4);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
