// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// Presentation timestamp within a [archetypes.AssetVideo].
/// 
/// Specified in nanoseconds.
/// Presentation timestamps are typically measured as time since video start.
/// </summary>
public readonly record struct VideoTimestamp(long TimestampNs) : ILoggable<VideoTimestamp>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.VideoTimestamp");

    public static IArrowArray ToArrow(ReadOnlySpan<VideoTimestamp> data)
    {
        var builder = new Int64Array.Builder();
        foreach (var v in data)
            builder.Append(v.TimestampNs);
        return builder.Build();
    }
}
