// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;

namespace Rerun.Net.Datatypes;

/// <summary>
/// How we interpret the coordinate system of an entity/space.
/// 
/// For instance: What is "up"? What does the Z axis mean?
/// 
/// The three coordinates are always ordered as [x, y, z].
/// 
/// For example [Right, Down, Forward] means that the X axis points to the right, the Y axis points
/// down, and the Z axis points forward.
/// 
/// ⚠ [Rerun does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
/// 
/// The following constants are used to represent the different directions:
/// * Up = 1
/// * Down = 2
/// * Right = 3
/// * Left = 4
/// * Forward = 5
/// * Back = 6
/// </summary>
public readonly record struct ViewCoordinates(byte[] Coordinates) : ILoggable<ViewCoordinates>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.ViewCoordinates");

    public static IArrowArray ToArrow(ReadOnlySpan<ViewCoordinates> data)
    {
        var valuesBuilder = new UInt8Array.Builder();
        foreach (var v in data)
            foreach (var elem in v.Coordinates)
                valuesBuilder.Append(elem);
        var values = valuesBuilder.Build();
        var listType = new FixedSizeListType(new Field("item", new UInt8Type(), false), 3);
        var arrayData = new ArrayData(listType, data.Length, 0, 0,
            new[] { ArrowBuffer.Empty }, new[] { values.Data });
        return new FixedSizeListArray(arrayData);
    }
}
