// <auto-generated/>
// DO NOT EDIT — generated by Rerun.Net.CodeGen
#pragma warning disable CS0542 // member names shall not match enclosing type

using Apache.Arrow;
using Apache.Arrow.Types;
using System.Linq;

namespace Rerun.Net.Datatypes;

public readonly partial record struct VisibleTimeRange(Utf8 Timeline, TimeRange Range) : ILoggable<VisibleTimeRange>
{
    public static ComponentDescriptor Descriptor => new(null, null, "rerun.datatypes.VisibleTimeRange");

    public static IArrowArray ToArrow(ReadOnlySpan<VisibleTimeRange> data)
    {
        var timelineTmp = new Utf8[data.Length];
        for (var i = 0; i < data.Length; i++) timelineTmp[i] = data[i].Timeline;
        var timelineArray = Utf8.ToArrow(timelineTmp);
        var rangeTmp = new TimeRange[data.Length];
        for (var i = 0; i < data.Length; i++) rangeTmp[i] = data[i].Range;
        var rangeArray = TimeRange.ToArrow(rangeTmp);
        var fields = new Apache.Arrow.Field[] {
            new("timeline", timelineArray.Data.DataType, false),
            new("range", rangeArray.Data.DataType, false),
        };
        var structType = new Apache.Arrow.Types.StructType(fields);
        return new StructArray(structType, data.Length, new IArrowArray[] { timelineArray, rangeArray }, ArrowBuffer.Empty);
    }
}
